### ISSUE TITLE
y_commands problem

### ISSUE THREAD

**Issue by PatchwerkQWER** [pawn-lang/YSI-Includes#10]
Latest version of YSI (this). Without zeex compiler patches

Errors
pawnoYSI4\include\YSI..\YSI_Visual\y_commands/impl.inc(1329) : error 021: symbol already defined: "@yH_OnScriptInit@003"
pawnoYSI4\include\YSI..\YSI_Visual\y_commands/impl.inc(1330) : error 021: symbol already defined: "@yH_OnScriptInit@003"
pawnoYSI4\include\YSI..\YSI_Visual\y_commands/impl.inc(1369) : warning 209: function "@yH_OnScriptInit@003" should return a value

Thanks :)

**Comment by mokiding** [comment]
Yeah, i have this too with latest version, but version before was fine, and btw, it's same with zeex compiler patches or without them.

**Comment by PatchwerkQWER** [comment]
Yes, I Agree

**Comment by PT-Player** [comment]
He forgot put include y_hooks..

Go inside the file is giving that erro and put #include < YSI \ y_hooks > (without spaces).

**Comment by Y-Less** [comment]
The problem is in "y_commands.inc" - "y_hooks" is included before "y_iterate", but the latest version of "y_iterate" also includes "y_hooks".  Move the "y_hooks" include below "y_iterate" in "y_commands.inc".

**Comment by PatchwerkQWER** [comment]
Thank you @Y-Less now it works!
