### ISSUE TITLE
y_iterator endless loop issue.

### ISSUE THREAD

**Issue by qoor** [pawn-lang/YSI-Includes#100]
Source:
# include <a_samp>

new kick[MAX_PLAYERS];

forward SecTimer();

main()
{
    SetTimer("SecTimer", 1000, true);
    return 1;
}

public SecTimer()
{
    foreach (new i : playerList)
    {
        if (kick[i])
        {
            if (--kick[i] == 0) Kick(i);
        }
    }
}

public OnPlayerConnect(playerid)
{
    Iter_Add(playerList, playerid);
    return 1;
}

public OnPlayerDisconnect(playerid)
{
    Iter_Remove(playerList, playerid);
    return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
    if (strcmp(cmdtext, "/test", true) == 0)
    {
        kick[playerid] = 2;
        return 1;
    }
    return 0;
}

(When I type "/test" command, after 2 second foreach do endless loop)

If I use Kick function in foreach, foreach do endless loop.

I think it cause 'array[value] = value' is wrong at Iter_Remove function.

When "i" variable is 0 in foreach timer, First foreach is point to 0. And foreach is point to 0 again because array[0] value is 0.

**Comment by Y-Less** [comment]
That's not a y_iterate bug, it is a bug in your code - you should be using Iter_SafeRemove, which is designed to be usable within a loop.

**Comment by Y-Less** [comment]
Of course, I could ask why you aren't just using the default `Player` iterator, which already handles this and more.
