### ISSUE TITLE
Auto initialisation of iterator arrays.

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/YSI-Includes#103]
So I've finally figured out a way of making this automatic - no more "Iter_Init()", even on the old compiler.  However, I'm writing this post here because the technique actually has wider uses - I've seen a few people grapple with similar underlying problems.  To explain what I mean, I need to get in to what the actual underlying problem is.

Note that when using Zeex's compiler this whole issue can be side-stepped by using multi-dimensions array literals, but that doesn't work in all cases.  Note also that this technique is VERY messy!

The general problem is this: how do you call a function when a variable is declared?  It could be for any reason, e.g. registering a handle with a plugin.  I say this, because I remember someone asking me about this recently (I just don't remember who).  For local variables, this is dead easy:

``` pawn
new var = Func();
```

For globals as well, it is actually quite simple, and done in many places in YSI:

``` pawn
new var;
// "@OS_" prefix (example) scanned for.
@OS_var() { var = Func(); }
// Can be wrapped in a macro.
init var = func();
```

The problem is that these two methods are very different, and there is no generic macro that can do both.  So we need some syntax that somehow behaves differently in local and global contexts - and I realised that there is one: custom operators:

``` pawn
new var = CustomTag:0; // Global, not compiled as a function call.
new var = CustomTag:0; // Local, compiled as a function call.
```

So we have a piece of code which can initialise a local variable with a function call (not the best function call, but good enough with some return address assembly magic), and using the same syntax doesn't affect globals.  We then need a different piece of code that can initalise the globals separately, this is still a bit tricky and introduces one difference - public variables:

``` pawn
public @OS_var = CustomTag:0; // Global, not compiled as a function call.
new @OS_var = CustomTag:0; // Local, compiled as a function call.
```

That can be simply scanned for and initialised once in `OnScriptInit`.  The down-side is that you need to use "public".  But I still think this is better than the alternative.  Bear in mind that any macro wrapping all this will NOT include the delarataion type, so only the user knows the scope of each variable.  Asking them to remember to consistently use `public` for these globals instead of whatever custom name is in use I think is much better.  Having `LocalIterator:` and `GlobalIterator:` would not be nice `public Iterator:` and `new Iterator:` is, I think, much more consistent.  Not great, and local statics don't work, but it is the best I've come up with yet (and I have thought about it a lot (even though I know I shouldn't, these things are just sort of relaxing brain teasers for me)).

**Comment by Y-Less** [comment]
OK, because I realised that local statics still won't work, this is still a no-go.  And the restrictions still weren't great.

**Comment by Crayder** [comment]
Bummer, but I still like the general idea... And I think I might look for some uses for it...
