### ISSUE TITLE
Issue Y_INI and Windows Server 

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#106]
Good morning, 
I meet an issue where when I use Y_INI on Windows SA:MP server (such as local one for testing), all system which use Y_INI for saving INI files are not writing content. The file is created but nothing is saved it. However, when i test it on a linux SA:MP server, no problem appears for saving content.
It appears for anything which use Y_INI

Example: 

> new file[100];
> format(file,sizeof(file),"ladmin/config/server_configurations.ini");
> new INI:ini = INI_Open(file);
>       INI_WriteInt(ini, "ReadPms", 1);
>       INI_WriteInt(ini, "ReadCmds", 1);
>       INI_WriteInt(ini, "MaxAdminLevel", 5);
>       INI_WriteInt(ini, "AntiSpam", 1);
>       INI_WriteInt(ini, "AntiSwear", 1);
>       INI_WriteInt(ini, "ConnectMessages", 1);
>       INI_WriteInt(ini, "AdminCmdMessages", 1);
>       INI_WriteInt(ini, "MustRegister", 0);
>       INI_Close(ini);

**Comment by Y-Less** [comment]
You've missed the most important part - the value of `file`, i.e. the filename.

**Comment by ghost** [comment]
Oh sorry, I didn't put in the example, but it is in my gamemode: Edited

**Comment by Y-Less** [comment]
Yes, I thought that was the case.  Windows is \, not /.

**Comment by Southclaws** [comment]
I thought the system-level fopen calls and thus the Pawn runtime was slash-agnostic? Or is it y_ini that enforces \ on windows and / on linux?

**Comment by ghost** [comment]
Currently, \ provides me : error 027: invalid character constant. However the file is created at the good place while using / with windows

**Comment by Y-Less** [comment]
You need "\" if you have a string, to stop it acting as the escape character.  Southclaw: honestly no idea, but when something doesn't work and something is obviously wrong, that's a good place to start.

**Comment by Y-Less** [comment]
Does that mean you solved the problem?

**Comment by SnMaxx** [comment]
Currently, i have this problem.
The YSI have any requirement for windows server 2012? use any .dll or something?

**Comment by Y-Less** [comment]
Nope.  It is purely PAWN.
