### ISSUE TITLE
Precisions concerning y_dialog

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#110]
Good afternoon, 

I would need precision concerning the include : y_dialog. Indeed, i didn't entirely understood the tutorial that is why i would need a confirmation about the use of it. I understood that we could use for a dialog with answer : inline and Dialog_ShowCallback. However, when an answer is not required, what does we have to use ?  Dialog_Show without id ? for example, Dialog_Show(playerid, DIALOG_STYLE_MSGBOX, "Title", "Message", "Button 1");  ?

Is it also possible to use in these dialogs, y_languages to translate currently in the dialogs?

Thanks!!

**Comment by Y-Less** [comment]
The inline callback still takes the "response" parameter, which is used to determine wether they pressed "ok" or "cancel" (or whatever the two buttons are).  If you only have one button the callback is still called, but you know what they pressed because there is only one option.

As for y_languages, yes, use `Text_<type>Box`:

``` pawn
Text_MessageBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2);
Text_InputBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2);
Text_ListBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2);
Text_PasswordBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2);
// Or the more generic:
Text_DialogBox(who, type, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2);
```

**Comment by Y-Less** [comment]
If you have the full YSI package, not just the includes, there are many default y_dialog language features:

``` pawn
loadtext core[ysi_dialog];

Text_MessageBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $DIALOG_OK, $DIALOG_NONE);
```

Full package here:

https://github.com/Misiur/YSI

Full list here (in English, browse the directory for other languages):

https://github.com/Misiur/YSI/blob/33c14380439f644298dde83715973246d29153a4/scriptfiles/YSI/text/core.EN#L210-L229

**Comment by ghost** [comment]
Thanks for the answer,
About: y_language
What if for example, I would like to include a string in a $CONTENT_TEXT, Let's imagin that the name of the player has to be included: Where shoud I include " GetName(player1)" for example ?

And what if with Y_dialog, I just want to show a dialog (an information dialog) where clicking on any button would just hide the dialog and that's all. Just for showing something in a dialog, what should i use?

**Comment by Y-Less** [comment]
All y_text functions are formatted, so:

``` pawn
Text_MessageBox(who, callback, $TEXT_TITLE, $CONTENT_TEXT, $BUTTON_1, $BUTTON_2, GetName(playerid));
```

However, y_text has inbuilt support for this, so use `%q` instead of `%s` and just pass a playerid not a name.

**Comment by ghost** [comment]
Alright, I will now be able to use y_language entirely: Last questions, with dialogs, how work the response, inline ?
Does the include y_dialog has to be included also because it is new style of dialogs for y_text ?
And I guess we don't need to put anything in YML file while translating a dialog ?

And thank you, i will begin to work in including this :)

**Comment by Y-Less** [comment]
I'm not sure what you mean with how do the responses work?  They are just normal inlines.

y_dialog needs to be included, yes, because it is used behind the scenes for y_text.

YML isn't needed, no.  That defines how the text looks, but you can't change that for dialogs.

**Comment by ghost** [comment]
Thanks it is exactly what i wanted to know, you were the light on the obscurity of my knowledge about this include
