### ISSUE TITLE
INI Parsefile function is not called

### ISSUE THREAD

**Issue by preguntator** [pawn-lang/YSI-Includes#114]
Hello, 
I use INI_ParseFile to load a system. However, the callback for setting value from the file is not called (loadh_data(id, name[], value[])) After debugging, the function i saw that this function is not called because it doesn't print what i asked for debugging. 
But, when i tried to use it in a blank test gamemode, it is working!

What could it be the problem? If you need any further code/info tell me

**Comment by Misiur** [comment]
1. What tag are you setting when saving file?
2. How exactly are you calling ParseFile?
3. Name of your function is exactly `loadh_data`?

**Comment by preguntator** [comment]
Hello, thanks for your message
1. I do not use any tags (however, ince again, it is loading perfectly when i try it on a bank gamemode (only this system in)
2. I'm talking about this : `INI_ParseFile(str1, "loadh_%s", .bExtra = true, .extra = id );`
3.  It is `function loadh_data(id, name[], value[])`Function is used via a macro that include, forward and public.

**Comment by Misiur** [comment]
Ok, so the thing is `"loadh_%s"` will try to call `loadh_tagname`. If you don't use any tags, it will (I think), try to call `loadh_` which you don't have. I'm not exactly sure why it works in empty gamemode, still, if you don't want to use a tag, just change `INI_ParseFile(str1, "loadh_%s", .bExtra = true, .extra = id );` to `INI_ParseFile(str1, "loadh_data", .bExtra = true, .extra = id );` and you're good to go

**Comment by preguntator** [comment]
ty A LOT !!! it is working
