### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by Dayvison** [pawn-lang/YSI-Includes#115]
I want to see my stack usage, but including y_iterate.

Tree functions use recursion:

```
Recursion: RelocateOpcodeNow
Recursion: bernstein
Recursion: rawMemset
```

I try just comment the functions.(Worked from the two last), but the `RelocateOpcodeNow`, give many errros. Have any way to solve this?

GM Try:

``` c++
#include    <a_samp>

// Plugins
#include    <profiler>
#include    <crashdetect>
#include    <sscanf2>
#include    <Pawn.CMD>
#include    <streamer>
#include    <mapandreas>

// Includes
#include    <YSI\y_iterate>

main()
{
}
```

**Comment by Y-Less** [comment]
This isn't a bug - there is nothing wrong with controlled recursion.

Also that function isn't even from YSI but amx_assembly, and even if you posted the issue there this still wouldn't be a bug.
