### ISSUE TITLE
y_text 

### ISSUE THREAD

**Issue by Ewwe** [pawn-lang/YSI-Includes#117]
HI, im trying to work with y_text and y_languages and i got error during compiling on this line :
**Text_Send(playerid,$BUTTON_NEXT);**
Error is following : undefined symbol **"DEFAULT_TEXT_SET"**

I found solution which needs update libs. But this issue still piss me up.
Thanks

**Comment by Crayder** [comment]
The issue here is that you didn't read, correct?

**Comment by Ewwe** [comment]
Issue is that y_text gives me error about undefined DEFAULT_TEXT_SET. I didnt found anythink how to fix it. Someone says that i need to update YSI. But i download latest zip with latest amx and still y_text gives me this error

**Comment by Y-Less** [comment]
You need something like the following at the top of the file:

``` pawn
loadtext file[section]
```

So if your `mode.EN` file looks like this:

```
[buttons]
BUTTON_PREV = Previous
BUTTON_NEXT = Next


[other]
SOMETHING = Value
```

You would have:

``` pawn
loadtext mode[buttons]; // To load the `[buttons]` tag of `mode.XX` files.

hook OnScriptInit()
{
    Langs_Add("English", "EN"); // To load "xx.EN" files.
}
```

I should note that if you have the full YSI package from here:

https://github.com/Misiur/YSI

You have many default texts included, such as these:

https://github.com/Misiur/YSI/blob/33c14380439f644298dde83715973246d29153a4/scriptfiles/YSI/text/core.EN#L210-L229

I don't know if those are what you are using.  If they are, people are correct that you will need to download that one, which has all the extra files, but a very old version of the code, then replace the `pawno\include` files with the ones from this repository.  Also, if they are, the code would become:

``` pawn
loadtext core[ysi_dialog];
```

Which obviously has the advantage of already having many translations.

**Comment by Y-Less** [comment]
There is a second way to solve the error - use an explicit text path instead of the per-file defaults set by `loadtext`:

``` pawn
Text_Send(playerid, $core[ysi_dialog]->DIALOG_NEXT);
```

**Comment by Y-Less** [comment]
A third way is:

``` pawn
Text_Send(playerid, $ysi_dialog->DIALOG_NEXT);
```

But that ONLY works for tags inside `core.XX`, since that is assumed to be the default when no other file is given.
