### ISSUE TITLE
y_interate.inc (229)

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#118]
Not sure on how to fix this, would like to know how:

`include\YSI\..\YSI_Visual\..\YSI_Players\y_groups\..\..\YSI_Data\y_iterate.inc(229) : warning 201: redefinition of constant/macro (symbol "_FOREACH_CUR_VERSION")`

Before you ask, I am using the latest version of Zeex Compiler, and AMX ASSEMBLY.

**Comment by Y-Less** [comment]
What flags are you compiling with?  Do you have `foreach.inc` (and if so, delete it).

**Comment by ghost** [comment]
That fixed it, thank you. I am not using any flags.

**Comment by Y-Less** [comment]
Possibly a bit late, but could you send me the version of foreach.inc that you were using please?  The code in both files is meant to detect and negotiate, but a few people do get this redefinition error that you did, so I'd like to know why.

**Comment by ghost** [comment]
https://github.com/karimcambridge/SAMP-foreach/blob/master/foreach.inc

**Comment by Y-Less** [comment]
Thanks.  That version SHOULD detect YSI, but clearly something is going wrong somewhere.  I'll look in to it for future reference, but don't worry about it.  The fact that you are using Zeex's compiler with no flags is useful, it could be because of `-Z` being omitted.
