### ISSUE TITLE
y_commands?

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#119]
In a modular gamemode with y_commands, do you need to include y_commands or is it fine to have it in one gamemode? Because my alternative commands aren't working for example:

animations.pwn:

```
#include <YSI\y_hooks>

hook OnScriptInit() {
    print("[OnScriptInit] Loading 'Server Core: Animations'...");
    Command_AddAltNamed("stopanim", "sa");
}

hook OnScriptExit(){
    print("[OnScriptExit] Unloading/Exiting 'Server Core: Animations'...");
}


YCMD:stopanim(playerid, params[], help)
{
    ClearAnimations(playerid);
    return 1;
}
```

But my question is why won't it work with my regular gamemode, like the command isn't registering? Do I need to include <YSI\y_commands> again?

**Comment by Y-Less** [comment]
If those are filterscripts, then yes you need to include it in them separately.  Also, "issues" are for bugs in the library - this isn't really one.
