### ISSUE TITLE
Y_Classes ignores OnPlayerSpawn

### ISSUE THREAD

**Issue by Admig0o** [pawn-lang/YSI-Includes#123]
Hello,

I have a problem with my classes.
When i am using Class_DisableSelection(OnPlayerConnect) and Class_ReturnToSelection(Logged in) it completely ignores the OnPlayerSpawn callback. I am getting spawned at 0,0,0.
I already debugged OnPlayerSpawn and its not printing anything.
I also updated YSI already to 4.0.

How can i fix this?

Admigo

**Comment by Crayder** [comment]
Just saying, you really shouldn't be using SetPlayerPos in OnPlayerSpawn (which I assume is what you're doing). You should use SetSpawnInfo.

**Comment by Admig0o** [comment]
No, i am using SetSpawnInfo. Its really strange. It only happens if i use the Class_DisableSelection function.

**Comment by Y-Less** [comment]
I will say that y_classes worked through a combination of bugs and odd behaviours - trying to make SA:MP do something it wasn't meant to do through strange combinations of function calls in obscure orders.  I tried to get it as stable as I could, but never fully...

**Comment by Admig0o** [comment]
Do you know how i can fix this? I only want to disable the class selection if the player is not logged in(OnPlayerConnect) and when they login they should return to the class selection.

**Comment by Y-Less** [comment]
That should work - it just sounds like the problem is OnPlayerSpawn.

**Comment by Admig0o** [comment]
How can the problem be on the OnPlayerSpawn callback if the callback not even getting called?  I am also using the Class_Goto function at OnPlayerRequestClass.

**Comment by Y-Less** [comment]
Yes, that IS the problem...  My point was what you said you wanted should work.

**Comment by Admig0o** [comment]
Yes indeed hehe.

**Comment by Y-Less** [comment]
Short answer: I don't know why the rest doesn't work right now, since it was an unstable mix of features in the first place...

**Comment by Admig0o** [comment]
What i did to fix this was replacing the Class_DisableSelection function with TogglePlayerSpectating(playerid, true); ,
