### ISSUE TITLE
Y_commands and y_groups

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#124]
As far I'm aware `GROUP_ADD` allows setting a command access for a single group, and at the same time disables access for all other groups. How would I go about allowing two (not hierarchically related) groups? 

Second question: I think using `OnPlayerCommandReceived` with error `COMMAND_DENIED` can allow me to show player message that they're not authorized to use the command instead of normal "command not found". Now, is there a simple way to get which groups are allowed to perform this specific command?

**Comment by Y-Less** [comment]
1) `GROUP_ADD` is basically a macro for:

``` pawn
Group_SetCommandDefault(YCMD:x, false);
Group_SetGlobalCommand(YCMD:x, false);
Group_SetCommand(group, YCMD:x, true);
```

To set for a second group, just copy the last line, or use the `GROUP_ADD` macro followed by another `Group_SetCommand` - the fact that the macro was used before won't affect any future calls.

2) The closest thing to a native method is:

``` pawn
foreach (new g : Group)
{
    if (Group_GetCommand(g, YCMD:whatever))
    {
    }
}
```

A faster way would be to add something like this to `YSI_Players\y_groups\_funcs.inc` (uncompiled and untested):

``` pawn
foreach (new Group:g : Bits(YSI_g_sElementMembership[commandID]))
{
}
```

May be some tag issues, and it needs wrapping in a function - I'll look in to it some more in a bit.

**Comment by Y-Less** [comment]
OK, I can't right now think of a fully generic solution that will match both the `Group_Func...` syntax (since the `...` is replaced in group function names by the current library having group functions declared for it) and the iterator special function syntax, which requries a specified start point.  The only way I can currently think of would be to define every combination of start point:

``` pawn
#define iterstart@Group_Commands iterstate(-1, 0, 0)
#define iterstart@Group_Areas iterstate(-1, 0, 0)
#define iterstart@Group_Vehicles iterstate(-1, 0, 0)
#define iterstart@Group_Zones iterstate(-1, 0, 0)
#define iterstart@Group_Classes iterstate(-1, 0, 0)
```

etc.  But that's not generic if you need a new one.

**Comment by Y-Less** [comment]
Interestingly, this worked amazingly well:

``` pawn

gforeign iterfunc Group_...s(bool:s);
gglobal iterfunc Group_...s(bool:s)
{
}
```

Actually pre-compiled correctly.

**Comment by Y-Less** [comment]
OK, this is the best I've come up with.  I was wanting to use foreach special iterator internal state to make the functions quicker (abstract `Bit_Mask` and `Bit_Slot`) but that would have required the macros above for initialisation:

``` pawn
// Tried doing "gglobal iterfunc Group_...s()", but it turned out to not work
// quite as well as I had hoped, especially once tags were introduced.  Instead
// we are just hard-coding the iterator prefix (which means that this in no way
// relies on "y_iterate".
gforeign _GROUP_MAKE_TAG:Iter_Func@Group_...s(idx, Group:g);
gglobal _GROUP_MAKE_TAG:Iter_Func@Group_...s(idx, Group:g)
{
    // "idx" doesn't have the "Group:" tag on it because of the way "y_iterate"
    // strips out certain tags.
    if (Group_IsValid(g))
    {
        GROUP_FIX(g);
        while (idx < _GROUP_MAKE_LIMIT)
        {
            if (Bit_Get(YSI_g_sElementMembership[idx], _:g))
                return _GROUP_MAKE_TAG:idx;
            ++idx;
        }
    }
    return _GROUP_MAKE_TAG:_GROUP_MAKE_LIMIT;
}

stock const
    _GROUP_MAKE_TAG:_GROUP_MAKE_TAG<iterstart@Group_...s> = _GROUP_MAKE_TAG:_GROUP_MAKE_LIMIT;

gforeign Group:Iter_Func@..._Groups(idx, _GROUP_MAKE_TAG:el);
gglobal Group:Iter_Func@..._Groups(idx, _GROUP_MAKE_TAG:el)
{
    // "idx" doesn't have the "Group:" tag on it because of the way "y_iterate"
    // strips out certain tags.
    if (idx == -1)
        idx = Group:0;
    else
        idx = GROUP_TEMP_FIX(Group:idx) + 1;
    while (idx < _MAX_GROUPS_G)
    {
        if (Bit_Get(YSI_g_sElementMembership[el], idx) && Group_IsValid(GROUP_MANGLE(idx)))
            return GROUP_MANGLE(idx);
        ++idx;
    }
    return INVALID_GROUP;
}

stock const
    Group:_GROUP_MAKE_NAME<iterstart@..._Groups> = INVALID_GROUP;
```

That gives you two special iterators:

``` pawn
    foreach (new i : Group_Commands(Group:2))
    {
    }
    foreach (new Group:i : Command_Groups(2))
    {
    }
```

The first one loops over every command in a group, the second one loops over every group that has a command.  However, y_groups has no way to determine element validity, so it is possible that this will currently return commands that have already been removed if they were previously part of a group.

Also, I say it gives you two iterators, but technically it gives you an infinite number of the form `Group_...s` and `..._Groups`, where `...` is any library configured for use with groups.

**Comment by Y-Less** [comment]
This should also work correctly with y_master, even when commands are in one script, groups are in another, and user code in a third (that's not the best way to do things, but it will work).
