### ISSUE TITLE
y_hooks doesn't work with timers

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/YSI-Includes#142]
I have absolutely no idea why.  I even at one point consulted Kalcor to see if the functions were called in some odd way, like caching the function address so that adjusting the pointer in the AMX header did nothing, but they aren't.  It SHOULD work, there's no reason why those public functions should be different to any other public function, but they are!

**Comment by Misiur** [comment]
Related #27 - some debugging I've done and results. I'm starting to think that some live memory visualiser would really help a lot of YSI issues (in theory OllyDBG could do, but it's polluted with samp-server stuff, not AMX only)

**Comment by Y-Less** [comment]
Yeah, I forgot that issue already existed!
