### ISSUE TITLE
y_text - $MY_TEXT not defined on Dialog_ShowCallback

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#143]
Is that normal? I just get an error, I think I'm doing everything okay. Aren't Player TextDraws supported or what's going on?

```
#include <YSI\y_text>
#include <YSI\y_languages>

loadtext myFile[all];

new Language:g_LangEN;
new Language:g_LangES;

public OnGameModeInit()
{
    g_LangEN = Langs_Add("EN", "English");
    g_LangEN = Langs_Add("ES", "Español");
    return 1;
}

/* Somewhere over there. */
PlayerTextDrawSetString(playerid, myPlayer_TD[playerid], $MY_TEXT);
```

myFile.EN
```
[all]
MY_TEXT = hello
```
myFile.ES
```
[all]
MY_TEXT = hola
```
Thanks a lot.

**Comment by Y-Less** [comment]
Only YSI functions support the $ syntax, that's a default function.  It would be good to hook them, but I haven't.

**Comment by Vasily-X** [comment]
I understand, I guess you won't update it anymore, right? If you do, here's a list with some functions:
```
TextDrawSetString
PlayerTextDrawSetString
SendClientMessage
SendClientMessageToAll

/* Would be great for format also, to do something like: */
format(string, sizeof(string), $MY_TEXT, var1, var2);
```
I know many things can be achieved with `Text_Send`, but support for TextDraws would be great though.

Thank you Y_Less!

**Comment by Y-Less** [comment]
It is only player TDs that aren't supported through y_td currently.

**Comment by Vasily-X** [comment]
I understand, I get undefined symbol with y_dialog (using y_inline) also:
`Dialog_ShowCallback(playerid, using inline Diag_Response, DIALOG_STYLE_MSGBOX, $LEAVE_SERVER_TITLE, $LEAVE_SERVER_BODY, $LEAVE_SERVER_BUT1, $LEAVE_SERVER_BUT2);`

@Y-Less, is it normal also? It's a YSI function.

Regards.

**Comment by Vasily-X** [comment]
Any news about this last one @Y-Less? Using conditions to check player's language pisses me off knowing it would be much easier with YSI.

Thank you.

**Comment by Y-Less** [comment]
Use the Text_Dialog functions - they are wrappers around the Dialog_ functions.

**Comment by Vasily-X** [comment]
@Y-Less
Oh, I didn't know they exist, thanks. I'll check the includes to enhance YSI's documentation.

**Comment by Y-Less** [comment]
Yeah, the documentation has always been lacking, and worse still since I deleted a load :(.
