### ISSUE TITLE
y_colours - Why AA as alpha value instead of FF?

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#145]
Just wondering why RGBA colors from `x11def.inc` use AA as alpha value instead of FF, applying them to TextDraws differences are remarkable. They don't match the _y_colours.png_ table either.

Any particular reason for this? @Y-Less 

EDIT: I've found also many Y_[COLOR] which use 00 for transparency, do they play any role there?

**Comment by Y-Less** [comment]
Historical - almost all colours used `AA` for alpha at one point, I don't know why, it was just a precedent that got set somewhere and everyone else used it.  You can set the alpha to anything you like though with a simple `|`.  Same for the `00` colours.
