### ISSUE TITLE
y_text - Loading wrong GameText style from LANG_DATA.yml

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#147]
I don't know if this is how it works in the last version or what, if I set the GameText style to 3 in LANG_DATA.yml, in-game I get one type less, in this case type 2.

Basically this is what it happens: [CONFIGURED_STYLE] - 1. So, now the interval is [1, 7) for GameText styles, not [0, 6]. 7 can not be used due a range condition.

I guess the error must be in `YSI_Players\y_text\styles.inc`, I'd like to know if this behaviour is normal before touching anything.

**Comment by Y-Less** [comment]
That's not normal, no.
