### ISSUE TITLE
YSI erros after update

### ISSUE THREAD

**Issue by PT-Player** [pawn-lang/YSI-Includes#148]
I just saw the updates you made on YSI @Y-Less , i tried to update to the lastest YSI but is giving me some errors..

Take a look:

`pawno\include\YSI\..\YSI_Coding\..\YSI_Core\y_utils.inc(631 -- 632) : error 017: undefined symbol "AsmSetErrorHandlerName"
pawno\include\YSI\..\YSI_Coding\y_hooks/impl.inc(403) : warning 217: loose indentation
pawno\include\YSI\..\YSI_Coding\y_hooks/impl.inc(404) : warning 217: loose indentation
pawno\include\YSI\..\YSI_Coding\y_hooks/impl.inc(405) : warning 217: loose indentation
pawno\include\YSI\..\YSI_Coding\y_hooks/impl.inc(406) : warning 217: loose indentation
pawno\include\YSI\..\YSI_Visual\..\YSI_Core\y_master/once.inc(161) : warning 201: redefinition of constant/macro (symbol "W@(@Zu:#%0:%1#,%2);return%3(%8)")
pawno\include\YSI\..\YSI_Visual\..\YSI_Core\y_master/once.inc(386) : error 035: argument type mismatch (argument 1)`

**Comment by Misiur** [comment]
Are those from Y_Less's fork? He said that it's not yet complete to be merged to master

**Comment by PT-Player** [comment]
@Misiur yes it is from @Y-Less fork

**Comment by Y-Less** [comment]
Use this one (Misiur's), mine is in flux as I'm porting to using JIT/code-parse.inc/md-sort.inc.  I've had to make custom versions of all of them, and a custom amx-assembly, so even if you get mine it probably still won't work till all those changes are pushed upstream.  The md-sort changes have been pulled, the JIT changes have been pulled to head but no new release has come out, the others I'm a named maintainer for so only have myself to blame for not having got the changes upstream.

**Comment by Y-Less** [comment]
Well I've pushed everything that's applicable.  You will still need to build the customised JIT plugin yourself if you want to use that, but otherwise all the includes are good (not well packaged yet, but I'm sure you can figure it out).

**Comment by PT-Player** [comment]
@Y-Less sorry open again i just want to say i need to use your last version because you fixed already the bug on y_dialogs finally i can use the normal and y_dialogs together.

Anyway thanks for all.

**Comment by Y-Less** [comment]
I'm pretty sure that fix is entirely independent of the others - just copy that one file for now if you can't get everything else working together.
