### ISSUE TITLE
Ysi 4.0(y_reading)

### ISSUE THREAD

**Issue by MrDinkles** [pawn-lang/YSI-Includes#15]
Ysi has a file reading problem,when i type the password it makes me login even if I type a wrong password

**Comment by Ahmad45123** [comment]
Where is y_reading ?
It doesn't even exist.

If you mean y_ini.. I am sure its a problem in your side because it works great for me.
Print both the stored password and the entered password and then make sure that both of them are not empty as if one of them are.. strcmp will still return 0.

**Comment by Misiur** [comment]
`reading.inc` is a part of `y_ini`. Seems like a problem with your code, not with the library. We need to see what you've tried, please create a topic on samp, or use pastebin like service and show it to us.

**Comment by MrDinkles** [comment]
my code works with older ysi http://pastebin.com/QqgcZS19

**Comment by pRaeF** [comment]
Maybe that's strcmp problem:
Are you sure hashpass and PlayerData[playerid][Password] is not null?

if(!strcmp(hashpass, PlayerData[playerid][Password], false))

in strcmp, if one of them null, it will return 0

**Comment by MrDinkles** [comment]
problem solved it was an error in INIParseFile

**Comment by Misiur** [comment]
Hey @MrDinkles, you mean `INI_ParseFile` in YSI, or your handler?
