### ISSUE TITLE
Question about y_xml

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#151]
I'm thinking to either make a house system with Y_INI or Y_XML. I have looked at everything but one of them is faster ? Or it is roughly the same ?

**Comment by Misiur** [comment]
I'm almost certain plain ini file, even with tags, is easier, and less time consuming to process than a XML document.

**Comment by Y-Less** [comment]
But that's not the point.  They are different systems for processing different types of data.  If your information is simple key-value pairs, then use an INI file.  If you data is hierarchical with lots of parameters for a single thing, then use XML.  You can't compare them on speed because they do totally different things - its nonsensical.

**Comment by ghost** [comment]
Alright, Let's use y_ini then; Thanks for these fast answers

**Comment by Y-Less** [comment]
A better question is: are you sure that this part of your code is the slow part?  If not, why are you worrying about it?

**Comment by ghost** [comment]
I have a very old gamemode and almost 80% of things are "outdated". As a consequence, i would like to use better and faster way for my house system which is currently annoying (DINI. To add an house, i have to restart the server). I'm looking since a long time on YSI and I saw these two ways of saving informations and that is why I wanted to know which one i should use :)

**Comment by ghost** [comment]
I had also another question when setting YSI on my server. I do not use everything but only some (flooding, iterate, ini soon, text).
When I made test, I sometimes had stack heap size errors or something like that. But, after fixing that, it is working on my test server. When the memory is allocated correctly on server start, Is it right I won't have any problems with this when my server is running. Is it only about the start of server ?

**Comment by Y-Less** [comment]
It is hard to say, but probably the vast majority of YSI's work is done at server startup - it puts a lot of effort in to the initial setup to make later code more efficient.  So yes, if your server starts without issues there's a good chance that YSI at least won't cause more problems further down the road - it is actually extremely lightweight once the server is running.  But if the problem wasn't YSI in the first place, then I can't guarantee that.

**Comment by ghost** [comment]
Is There a way to loop through all the xml file and for which parent elements parse their data in but i'd like to avoid to use XML_Addhandler (i have near 30 parent elements).

Thanks

**Comment by Y-Less** [comment]
I'm not sure what you mean sorry.

**Comment by ghost** [comment]
Let me give you an example;

```
<XML>
	<Parent_Element name"Race Name1">
		<1CP>blablabla</1CP>
	</Parent_Element>
	<Parent_Element name"Race Name2">
		<1CP>blablabla</1CP>
	</Parent_Element>
	<Parent_Element name"Race Name3">
		<1CP>blablabla</1CP>
	</Parent_Element>
</XML>
```

Lets imagin there are a lot of checkpoints (1CP, 2CP): I would like to go through the xml file, each parent element: Goto first parent elements: Take name and checkpoints, goto the second etc..

However, for taking data i want:  i have to do (new XML:file = XML_New(), XML_AddHandler, xml_parse) for each parent_elements. How could i avoid to use do it for all parent elements i have. And do it for all the file.

I hope it is better explained

**Comment by Y-Less** [comment]
I think I understand what you are thinking, but I also think you are doing it wrong.  You can have multiple copies of the same tag under each parent:

```xml
<XML>
	<Parent_Element name"Race Name1">
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
	</Parent_Element>
	<Parent_Element name"Race Name2">
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
	</Parent_Element>
	<Parent_Element name"Race Name3">
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
		<CP>blablabla</CP>
	</Parent_Element>
</XML>
```

So all you need is two handlers - `CP` and `Parent_Element`, the latter of which can loop over the results of its children.  The handlers are called from inside out, and in order of children, so the handler order for that example will be:

```xml
<XML>
	<Parent_Element name"Race Name1">
		<CP>blablabla</CP>  1
		<CP>blablabla</CP>  2
		<CP>blablabla</CP>  3
		<CP>blablabla</CP>  4
		<CP>blablabla</CP>  5
		<CP>blablabla</CP>  6
	</Parent_Element>  7
	<Parent_Element name"Race Name2">
		<CP>blablabla</CP>  8
		<CP>blablabla</CP>  9
		<CP>blablabla</CP>  10
		<CP>blablabla</CP>  11
	</Parent_Element>  12
	<Parent_Element name"Race Name3">
		<CP>blablabla</CP>  13
		<CP>blablabla</CP>  14
		<CP>blablabla</CP>  15
		<CP>blablabla</CP>  16
		<CP>blablabla</CP>  17
		<CP>blablabla</CP>  18
	</Parent_Element>  19
</XML>
```

So you can guarantee that all children are correct.  Whatever the `CP` handler returns becomes the value when you loop through all the children in the `Parent_Element` handler.

**Comment by ghost** [comment]
If I understand you correctly, if i do the code below, it will get all CP: from all "parent_element" as it is the exactly same name ? If yes ? how could i get the **name** in which parent element ?

```
new XML:file = XML_New();
XML_AddHandler(file, "Parent_Element", "Parsing");
XML_Parse(file, "file.xml");

function Parsing()
{
	static key[MAX_XML_ENTRY_NAME], val[MAX_XML_ENTRY_NAME]
	while(XML_GetKeyValue(key, val))
	{
		// key = CP, val = blablabla
	}
}

```

**Comment by Y-Less** [comment]
At some point, `key` will be `name`.  That loop loops over all children - tags and properties.

**Comment by ghost** [comment]
Thanks, I did tests and thanks to your explanations it is working as i wanted!
