### ISSUE TITLE
When setting any YSI includes linked with y_utils and y_cgen

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#152]
This happened since the little update which were done few days ago

C:\Users\Fqr\Desktop\MyGm\pawno\include\YSI\..\YSI_Storage\..\YSI_Core\y_utils.inc(694 -- 695) : error 017: undefined symbol "AsmSetErrorHandlerName"
C:\Users\Fqr\Desktop\MyGm\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\..\YSI_Internal\y_cgen.inc(90) : warning 231: state specification on forward declaration is ignored

Thanks for your help

**Comment by ghost** [comment]
I have fixed the first error caused by an out-dated amx_assembly (https://github.com/Zeex/amx_assembly/commit/3ccd086a5344a9c6c531ceba2de2a9c425a680c0) But the second warning remain

**Comment by Y-Less** [comment]
I fixed that in my fork, but I didn't know the mistake had ever been pushed upstream to Misiur's.  Just ignore it for now (since I can't remember the fix off the top of my head - check the commit log on my fork if you are really that bothered).

**Comment by Y-Less** [comment]
In fact, are you sure you are using the correct fork at all?  I don't think that first error should have appeared on Misiur's fork either...
