### ISSUE TITLE
Warnings @ Pawn Compiler 3.10.1

### ISSUE THREAD

**Issue by ehylla93** [pawn-lang/YSI-Includes#154]
**LATEST VERSION OF YSI IS USED**

Using Pawn Compiler 3.10.1 will force the following warnings:

```
D:\Program Files (x86)\Pawno\include\YSI\..\YSI_Coding\..\YSI_Core\..\YSI_Storage\y_amx.inc(1010) : warning 208: function with tag result or global variables as arguments is used before definition, forcing reparse
D:\Program Files (x86)\Pawno\include\YSI\..\YSI_Coding\y_inline/impl.inc(1468) : warning 208: function with tag result or global variables as arguments is used before definition, forcing reparse
D:\Program Files (x86)\Pawno\include\YSI\..\YSI_Coding\y_inline/impl.inc(1630) : warning 208: function with tag result or global variables as arguments is used before definition, forcing reparse
Pawn compiler 3.10.1	 	 	Copyright (c) 1997-2006, ITB CompuPhase

3 Warnings.
```
The following includes have been used:

```
#include <YSI\y_va>
#include <YSI\y_commands>
#include <YSI\y_stringhash>
#include <YSI\y_timers>
#include <YSI\y_inline>
#include <YSI\y_ini>
```

**Comment by Crayder** [comment]
Do you have the latest includes, after the last commit?

**Comment by ehylla93** [comment]
Yep, I just downloaded it again for this test.

**Comment by Y-Less** [comment]
I've not tested against that compiler yet - it only came out yesterday and I've been VERY busy at work!  But yes, I'm not too surprised that kicks up a few warnings (although I wouldn't have thought those variables would be subject to the relevant bug, but who knows).  Just ignore them for now.

**Comment by Y-Less** [comment]
I've looked in to them a bit more.  I think the problem is that they are called with globals, but although the globals are in use elsewhere (which would mean the bug that warning was introduced for wouldn't happen) those other uses are elided due to being uncalled `stock`s.  Forwarding them may help, as might some other solutions like force-including the relevant globals.

**Comment by Y-Less** [comment]
Maybe @Zeex has an idea?  Relevant parts:

Three functions:

https://github.com/Misiur/YSI-Includes/blob/46c4c138a657365a48c8668280970ec57d6ad4a8/YSI_Coding/y_inline/impl.inc#L1468

https://github.com/Misiur/YSI-Includes/blob/46c4c138a657365a48c8668280970ec57d6ad4a8/YSI_Coding/y_inline/impl.inc#L1630

https://github.com/Misiur/YSI-Includes/search?utf8=%E2%9C%93&q=AMX_ReadString

Uses of the only global variable in `AMX_ReadString`:

https://github.com/Misiur/YSI-Includes/search?utf8=%E2%9C%93&q=AMX_BASE_ADDRESS

All the y_inline function uses are internal.

**Comment by Zeex** [comment]
Try this build: https://ci.appveyor.com/project/Zeex/pawn/build/148/artifacts

**Comment by ehylla93** [comment]
This build also solve problems with YSI 3.1.
