### ISSUE TITLE
File reading issue

### ISSUE THREAD

**Issue by TahaR9** [pawn-lang/YSI-Includes#161]
Hello,
I've been using ysi 3.01 version in past, but when I moved my server to 4.0, I'm having issues with map reading. What i mean by that is, when a map loads from filterscript folder, it only loops whenever the map ends, same map is loaded again. I dont have this problem with YSI 3 but only with 4.0. When I start my server the first map is not loaded as well, but when the timer suppose after 1 min map ends, the next map starts, it loads, then that same map keeps repeating when timer is ended, it doesn't load objects or spawn values from any further maps however it does show on logs that its reading other map files, but the same map is loaded again with same objects. Server reads map objects from filterscript and written data like HumanSpawn, ZombieSpawn values from .ini files i.e 1.ini 2.ini etc.

Here is the code of ending map:
http://pastebin.com/EfSTBPmD

If there is anything else I need to provide, please do let me know.

**Comment by Y-Less** [comment]
None of your code to determine which map to load is anything to do with YSI.  The only YSI code in there is y_ini, which loads the file you tell it to, if the wrong file is selected, the wrong file will be loaded.

**Comment by TahaR9** [comment]
Also i forgot to mention, I am getting no errors when I compile script on compiler, but when I start up the server I get this warning on console:
*** YSI Warning: y_malloc set up via "CallLocalFunction", memory corruption is a remote possibility

Could this be the reason?

**Comment by Y-Less** [comment]
You aren't using y_inline with that code (y_inline uses y_malloc) so no, unless you are using that somewhere else.
