### ISSUE TITLE
Loop with y_ini

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#165]
Good evening, 

I'd like to loop though all the keys contained in a tag.  Could you think we could do something like that: 

[info]
Info1 =
Info2 =
Info3 = 
Info4 = 

Something like that

foreach(......)
{
      if(i == 3)
}

I'd like to check which key contains 3 in this tag. After, I'd like set this key. Do you think it could be possible ? 

Thanks

**Comment by Y-Less** [comment]
That's not really what INI files are for.  I mean you can, since y_ini calls the load callback once for each entry, so it is quite easy to read both the `name` and `value` inputs at the same time, but if you want more complex querying, a set of key/value pairs probably isn't the right way to go.

**Comment by Y-Less** [comment]
Closed as this isn't an issue.  If you have any follow-ups, open a new issue.
