### ISSUE TITLE
Mild unimportant repository organisational gripes

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/YSI-Includes#167]
It's always bothered me that this repo has no readme and a bunch of unused (confusingly named) branches!

- master: Latest commit on Mar 27, 2013 - not the semantic "master" branch!
- experimental-iterate: Latest commit on Oct 22, 2015 - I assume this is a feature-branch
- development: Latest commit on Jul 15, 2012 - isn't the entire repo pretty much "development"?
- current: Latest commit on Oct 1, 2012 - very "current"!

I know this project has years of ancient bits hanging off, and I'm aware (as is the case with most open source projects) contributors are just dedicating their various amounts of free time so things like this are generally not important or prioritised.

I recently had a conversation with someone who had never used YSI before and they were very confused as to 1. how to install it, 2. what the modules do, 3. the story behind the maintainers/ownership/development.

I'd be willing to help clean up the repo and write some basic documentation. The wiki is actually looking great so in terms of module documentation, it's fine. I just think a `readme.md` file for the front page would be useful (again, I'd be willing to contribute this so maintainers can focus on code!)

**Comment by Y-Less** [comment]
Yes!  Entirely this!  Thank you!  I am not good at branches:

![console2](https://cloud.githubusercontent.com/assets/991078/25313372/05ec6fd6-2825-11e7-9853-3062bc48f3e3.png)

That's a private project for a client of mine (hence some minor censoring of potentially important information in some places).  It is actually slightly worse than that - some merges aren't shown there since the mess was so bad I had to manually copy code between branches to fix them.

**Comment by Southclaws** [comment]
Haha, that is quite a tree you have there! I'm quite the opposite and have a bad habit of keeping everything in one branch while I write "stream of conscious" style then realise the last 10 commits really should be in another branch...

Anyway, I think I'll start with the readme as that will be the simple part, then I'll move `YSI.tl` to `master` as a pull request so others can review it and make sure everything is fine, then kill off the other branches. It would be nice to tag a stable release too. I'm also wondering how this project is versioned - as much as I like semantic versioning, I do find it's a pain to track and remember to keep up to date, I've always been in favour of versioning by year and week-number ("17w16" for example, with maybe a "-hotfix" or "-stable" suffix).

I also must ask, why is the main branch called YSI.tl and not master?
