### ISSUE TITLE
#define FOREACH_NO_PLAYERS errors (y_iterate)

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#168]
I got about 21 errors when I defined FOREACH_NO_PLAYERS before y_iterate, happened in clean gamemode. May you confirm also?

```
#include <a_samp>

#define FOREACH_NO_PLAYERS

#include <YSI-Includes\YSI\y_iterate>
```

**Comment by Y-Less** [comment]
Do you have "foreach" as well?  I can't reproduce this locally, but I don't have a stand-alone copy.

**Comment by Y-Less** [comment]
Fixed (locally, yet to push).  Thanks.
