### ISSUE TITLE
y_malloc JIT comptability

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#176]
Good evening, 

This issue is entirely interested for getting YSI-Includes more compatible with JIT plugin. My gamemode uses 3 YSI includes: y_colours, y_iterate and y_ini.

YSI is more and more compatible with JIT plugins: y_malloc was compatible (https://github.com/Misiur/YSI-Includes/commit/7c9fa55fbe8411ad3db18f2417e6a01811b820b8) during few weeks but the commit got reversed (https://github.com/Misiur/YSI-Includes/commit/46c4c138a657365a48c8668280970ec57d6ad4a8) due to few bugs or errors not really about y_malloc.

YSI lost as a consequence a comptability with y_malloc. Could something be done to get back this comptability ?

Sincerely

**Comment by Y-Less** [comment]
I can remember what the exact state of y_malloc on this branch is - it might work as-is with `YSI_NO_HEAP_MALLOC`.  But I can tell you that those parts you are using rely on y_hooks, which is NOT JIT compatable in the current branch.

If you really want JIT compatability try this one:

https://github.com/Y-Less/YSI-Includes/tree/Branch_JIT

y_hooks, y_malloc, and almost everything else except y_inline are ported and compatable.  However, you will also need to get md-sort, amx-assembly, and possibly another third-party include.

**Comment by ghost** [comment]
Thanks. The issue https://github.com/Misiur/YSI-Includes/issues/153 happens also on https://github.com/Y-Less/YSI-Includes/tree/Branch_JIT

https://github.com/Misiur/YSI-Includes/issues/153#issuecomment-275227516

**Comment by Y-Less** [comment]
It compiles for me, but that is very much a personal dev branch.

**Comment by Y-Less** [comment]
Make sure have the VERY latest code-parse.inc as well as the other things I listed.

**Comment by ghost** [comment]
Thanks, Indeed it is compiling perfectly with a blank GM. But creates internal problems with mine.



> C:\Users\john\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\y_inline/impl.inc(350) : error 017: undefined symbol "u@"
C:\Users\john\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\y_inline/impl.inc(350) : error 029: invalid expression, assumed zero
C:\Users\john\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\y_inline/impl.inc(350) : warning 215: expression has no effect
C:\Users\john\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\y_inline/impl.inc(350) : error 001: expected token: ";", but found "]"
C:\Users\john\pawno\include\YSI\..\YSI_Storage\..\YSI_Coding\y_inline/impl.inc(350) : fatal error 107: too many error messages on one line

**Comment by Y-Less** [comment]
I told you y_inline wasn't done.

**Comment by ghost** [comment]
Ho, Indeed I just saw that y_ini was using y_inline (https://github.com/Y-Less/YSI-Includes/blob/Branch_JIT/YSI_Storage/y_ini.inc#L211)

**Comment by Y-Less** [comment]
Ahh, y_ini includes it as an optional part, I'd need to make them less coupled.
