### ISSUE TITLE
y_commands crashing pawn

### ISSUE THREAD

**Issue by tappzy** [pawn-lang/YSI-Includes#178]
As you can see on the image i have y_commands and y_master included and when i try to compile it crashes pawn. When i remove that it compiles fine. Other YSI includes work. Anyone know whats going on? Do those libraries even work on YSI4? Thanks.

![e9tojpk](https://cloud.githubusercontent.com/assets/28908310/26376709/d277997c-400d-11e7-9756-fc5b8fb2977c.png)

**Comment by Y-Less** [comment]
Do you have a minimal repro you can post please?

**Comment by tappzy** [comment]
Here you go:

[TST_SRV.zip](https://github.com/Misiur/YSI-Includes/files/1028948/TST_SRV.zip)

It's a fresh samp package with only YSI in the includes, the gamemode used is bare.pwn

**Comment by Y-Less** [comment]
Are you sure you are on the latest version?  I replaced the files in that download with a new set directly from this repository and there were no issues.
