### ISSUE TITLE
YSI warnings

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#180]
_Today I downloaded YSI library and I get two compiler errors_

`C:\SA-MP Server\pawno\include\YSI_Data\..\YSI_Internal\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(336) : warning 202: number of arguments does not match definition
C:\SA-MP Server\pawno\include\YSI_Data\..\YSI_Internal\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(428) : warning 202: number of arguments does not match definition
Pawn compiler 3.10.2	 	 	Copyright (c) 1997-2006, ITB CompuPhase

2 Warnings.
[Finished in 4.4s]`

**Comment by Y-Less** [comment]
You need to update amx_assembly.  I'm actually surprised it compiled - I thought I put an error in for that case.

**Comment by ghost** [comment]
You can help me get the most recent version of amx_assembly ?

I downloaded amx_assembly from Zeex github profile and not working for me, there is another more version ?

**Comment by Y-Less** [comment]
Sorry, I didn't push the new version!

**Comment by Y-Less** [comment]
Done.

**Comment by ghost** [comment]
Now working, thanks @Y-Less
