### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tappzy** [pawn-lang/YSI-Includes#186]
Will there ever be a release or should we just continue downloading YSI.tl branch every time there's a commit? I'm asking because new people are kinda confused by all of this ...  🤔

**Comment by Y-Less** [comment]
Yes, there should be.

**Comment by Misiur** [comment]
I wanted to do this and even [created a checklist of stuff to be done before](https://github.com/Misiur/YSI-Includes/issues/58), but I couldn't get around and finish the stuff.

**Comment by Y-Less** [comment]
I don't even think it really needs that much effort.  Yes, there are open issues and that's a problem, but for an initial release, just stick amx_assembly and this together in a zip and call it a day.  Maybe combine with the extra scriptfiles stuff from the YSI repository.

The upcoming JIT-compatible version will absolutely require a release, since it now depends on amx_assembly, md-sort, code-parse, and possibly some others (but ironically not the JIT).

**Comment by Misiur** [comment]
Ok, I'll do it now. All JIT stuff is on your fork, so just packing YSI.tl with amx_assembly will be alright?

**Comment by Misiur** [comment]
If we'll stick to semver, I guess the JIT version will be version 5. For now I'll tag this one as v4.0.0

**Comment by Misiur** [comment]
[Here you go](https://github.com/Misiur/YSI-Includes/releases/tag/v4.0.0)

I thought it would be easy just using `git archive` but it doesn't work with submodules, and well, doesn't allow for more specific settings like folder structure.

I made a [small utility tool in node](https://github.com/Misiur/YSI-Release-Builder) to simplify this process.
Basically what it does:
1. Download YSI, YSI-Includes and amx_assembly
2. Create folder structure for quick copying
3. Copy YSI-Includes and amx_assembly to `pawno/include`
4. Copy YSI `scriptfiles` to `scriptfiles`
5. Remove YSI (not includes), and all `.git*` files and folders (if your server folder uses git it picks up garbage from YSI-AC for example)
6. Package it into a zip

So if anyone wants latest version if it's not yet released simply run it and you'll get a .zip

**Comment by Y-Less** [comment]
Very nice!

**Comment by Y-Less** [comment]
Thank you a lot!  I'm guessing looking at the code that its easy to add more dependencies.
