### ISSUE TITLE
y_text: Text not Found

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#191]
I followed up everything as instructed but for some reason y_text can't read the text and, to top it, stucks in some kind of infinite loop that freezes the server, only option to pkill -9 samp03svr.

Directory structure:
```
- gamemodes
|
|- TDM.amx
- scriptfiles
|
|- YSI
 |- mensajes_LANG_DATA.yml
 |- text
  |
  |- mensajes.ES
  |- mensajes.EN
```

TDM.pwn: https://pastebin.com/6FWCBDnx **(Updated)**
mensajes.ES: https://pastebin.com/rCPVdrNt
mensajes.EN: https://pastebin.com/jcxZb3h1

Server Log:
```
[15:40:41] Text_Render: Loop: p = 14, llen = 49, output = "Text Not Found"
[15:40:41] Text_Render: Final render?
[15:40:41] Text_Render: Yes!
[15:40:41] Text_Render: p = 14, output = "Text Not Found"
[15:40:41] 00000054 = T
[15:40:41] 00000065 = e
[15:40:41] 00000078 = x
[15:40:41] 00000074 = t
[15:40:41] 00000020 =  
[15:40:41] 0000004E = N
[15:40:41] 0000006F = o
[15:40:41] 00000074 = t
[15:40:41] 00000020 =  
[15:40:41] 00000046 = F
[15:40:41] 0000006F = o
[15:40:41] 00000075 = u
[15:40:41] 0000006E = n
[15:40:41] 00000064 = d
[15:40:41] Text_Render end
[15:40:41] Text_GetText: loop1 mode_text:all 0 -1 mode_text:all 109
```

Last line is an infinite loop that repeats like a million times. I double checked everything and nothing is missing. Using Ubuntu 16.04 64-bit, whole folder with chmod 777.

**Comment by Y-Less** [comment]
Those files are both in English, do you have a corrected link for the Spanish version?

**Comment by Misiur** [comment]
He posted this problem on the forum http://forum.sa-mp.com/showthread.php?p=3908923#post3908923 . So first question first @AGraber - did you change `$IDIOMA_ESPAÑOL` to `$IDIOMA_ESPANOL`, and did anything change?

**Comment by Y-Less** [comment]
Yes, the identifiers must match exactly, and I've never tested them with anything but latin (English) characters, not even ones from other similar languages (sorry).

**Comment by Y-Less** [comment]
Ahh, the forum version has the correct Spanish version link, so I'll test.

Side note, it is probably worth using "English" and "Español" exactly in both file versions - they are for langage selection so probably always want to be in their own language, regardless of what the current language setting is.  Or you can list all currently loaded languages from the `Langs_Add` functions.

**Comment by AGraber** [comment]
Well, firstly thanks for you support guys.
@Misiur , yep, I tried that and the same thing. What I did try (some silly test to see if anything change) was to change:

`Text_MessageBox(playerid, DialogIdiomaR, $TITULO_SELECCION_IDIOMA, $SELECCION_IDIOMA, $IDIOMA_ESPANOL, $IDIOMA_INGLES);`

To this
`Text_MessageBox(playerid, DialogIdiomaR, "asdf", "fdsa", "esp", "eng");`

Then the things changed a bit, but afterwards the same thing:
http://i.imgur.com/RnLoXs7.png

After clicking the dialog:
http://i.imgur.com/HvWuMJa.png

@Y-Less I did thought that using foreing characters would affect identifiers so I'm just restraining from using them and using similar characters, the thing I forgot was to change the Ñ but the thing is still the same

**Comment by Misiur** [comment]
I'm joining this issue as I wanted to use y_text in a project and hit this problem right away. I'll document my debug investigation here as well. 

It seems that Text_GetText does nothing, because of [a missing property](https://github.com/Misiur/YSI-Includes/blob/c06aa7d881e241560bb5664c98e318c817b49882/YSI_Players/y_text/impl.inc#L1091). 
So, in short - I think there is a missing call either to `Text_ResetLoaded`, or `Text_RefreshLoaded`. I'll try now explicitly calling each of them

**Comment by Y-Less** [comment]
OK, I will try and solve this - I gave up on the rewrite, there were just way too many corner-cases, I realised I was unlikely to ever be able improve on the existing implementation that way rather than just incremental fixes.

**Comment by Misiur** [comment]
I was wrong, `Text_RefreshLoaded` is called. However [`AMX_GetPublicNameSuffix` does not find the loadtext created public function](https://github.com/Misiur/YSI-Includes/blob/c06aa7d881e241560bb5664c98e318c817b49882/YSI_Players/y_text/impl.inc#L472). I'll dig deeper

**Comment by Misiur** [comment]
Oh! Great, thank you

**Comment by Misiur** [comment]
Yup, it's a `y_amx` issue.
```pawn
#include <a_samp>
#define _DEBUG 7

#include <YSI\y_utils>
#include <YSI\y_amx>

main() {}

public OnGameModeInit()
{
	new
		idx = 0,
		buffer[32]
	;

	print("Before");
	idx = 0;
	while ((idx = AMX_GetPublicNameSuffix(idx, buffer, _A<@_@@_>)))
	{
		print("Should happen");
	}
	print("After");

	return 1;
}

forward Test@_@@_();
public Test@_@@_()
{
	return 1;
}
```

```
Before
AMX_GetNameSuffix called: 0, 0, "", 1077960512
AMX_GetBaseCount called: 0, 0, 0
After
```

Looping through `AMX_GetPublicName` shows that the function is in publics header. I can't go further as `AMX_GetNameSuffix` is too advanced for me :(

**Comment by Misiur** [comment]
I dumped a lot of prints into the `AMX_GetNameSuffix ` then compared it with `AMX_GetEntrySuffix`. I noticed that even though basecount said 21, only 10 functions were listed. I took a closer look: Is this doubled `idx++` on purpose? https://github.com/Misiur/YSI-Includes/blob/c06aa7d881e241560bb5664c98e318c817b49882/YSI_Storage/y_amx.inc#L639 and https://github.com/Misiur/YSI-Includes/blob/c06aa7d881e241560bb5664c98e318c817b49882/YSI_Storage/y_amx.inc#L677

Removing one of them now lists all functions (but it doesn't work yet)

Also is it normal that public header strings are packed?

**Comment by Misiur** [comment]
All right, I learned bit magic and understood the code deeply, just to find out it was the rogue `idx++` the whole time, and I just tested incorrectly.
![image](https://user-images.githubusercontent.com/752692/29412494-580bdace-8359-11e7-8362-b5c1341d04dd.png)
y_text working, I'll add PR now
