### ISSUE TITLE
Rename amx_assembly.inc to y_thirdparty.inc

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/YSI-Includes#194]
The current name doesn't match the existing naming scheme, may in future be wrong when there are more third party libraries, and is confusing since it talks about amx_assembly the library (not itself).

**Comment by Y-Less** [comment]
I'd do it right now if I wasn't on my phone, this is just a reminder to myself.

**Comment by BeardedFire** [comment]
I cant find this amx_assembly and everytime i try to compile my script i get this msg: "\pawno\include\YSI\..\YSI_Storage\..\YSI_Internal\y_thirdpartyinclude.inc(47) : fatal error 111: user error: Please update "https://github.com/Zeex/amx_assembly" to get "deref()" i did that what it says, update so what do i do please help ?

**Comment by Y-Less** [comment]
What do you mean you can't find it? The link is right there in the error message!

**Comment by BeardedFire** [comment]
I did download and install that but there isnt a file called that /:

**Comment by Misiur** [comment]
Not really following. File callled what? The whole folder is amx_assembly, just put it in pawno/include

**Comment by BeardedFire** [comment]
All i got from that download was a bunch of files and non called amx_assembly

**Comment by Y-Less** [comment]
The whole thing is amx_assembly, put all the files in a single directory called amx_assembly. Anyway, there should have been one file called that - the zip file.

**Comment by BeardedFire** [comment]
Ohh so i just put it all from the zip in own folder called that and put it in \pawno\includes ? If so then thanks for the help

**Comment by Y-Less** [comment]
Yes, you can actually put it in a lot of different places and YSI will do its best to find them.

**Comment by BeardedFire** [comment]
Ok i actually just dropped all the files and such in includes folder lol

**Comment by Y-Less** [comment]
Yes, it did occur to me that that is probably the most obvious place that YSI doesn't try.

**Comment by BeardedFire** [comment]
I will make a folder do the rename and just out it in server folder and see if that helps

**Comment by BeardedFire** [comment]
I just made a folder in my root folder and called it " y_thirdparty.inc" dropped all the files in the rar there same error. Put the folder in includes same error

**Comment by Y-Less** [comment]
Why did you name it that? We already told you what to call it !

**Comment by BeardedFire** [comment]
I tried that aswell

**Comment by Misiur** [comment]
Can you write down your current folder structure?

**Comment by BeardedFire** [comment]
\pawno\includes\amx_assembly (where i put all the files from the rar)

**Comment by Misiur** [comment]
Do you by any chance have now both "pawno\include" and "pawno\includes"? If so, make sure only "pawno\include" exists

**Comment by BeardedFire** [comment]
Ohhh didnt mean that s there its only \pawno\include

**Comment by Misiur** [comment]
Well, that's weird. Look at my configuration:
![image](https://user-images.githubusercontent.com/752692/29942167-371ebede-8e95-11e7-81a1-6a76fc63b442.png)
![image](https://user-images.githubusercontent.com/752692/29942182-43add388-8e95-11e7-80b6-6e3dd1bba308.png)

**Comment by BeardedFire** [comment]
I have nothing in the regular "amx" folder hmmm

**Comment by Misiur** [comment]
But you said you have `amx_assembly `. This might not help, but try renaming it, then we'll know for sure

**Comment by BeardedFire** [comment]
the folder called "amx" was all empty, i had those files u had in amx just in regular include folder. just put them in amx, but i got a 2nd folder called amx_assembly where i put all the files from the rar, which u got just in "include"

**Comment by Misiur** [comment]
That's a bit confusing. Mind taking a few screenshots? (You can just paste in comment box here, it'll upload images automatically)

**Comment by BeardedFire** [comment]
![image](https://user-images.githubusercontent.com/31486997/29942773-57a7d972-8e97-11e7-8cce-92ffca516919.png)
![image](https://user-images.githubusercontent.com/31486997/29942780-5e18035e-8e97-11e7-9c51-bd8969bc3b9e.png)
 JUST put it like that it removed the error from pawno, but now i got warnings on stuff i didnt have warning on before:
![image](https://user-images.githubusercontent.com/31486997/29942837-81762812-8e97-11e7-98cd-b674fe1b6e59.png)

**Comment by Misiur** [comment]
That's good, the core problem is solved. I guess you've upgraded from YSI 3? `Sum` and `Random` are used in YSI 4, you have to rename your variables.

**Comment by BeardedFire** [comment]
so then instead of Sum and Random then just choose a different name ?

**Comment by Misiur** [comment]
Yup.

**Comment by BeardedFire** [comment]
Ok thank you, thank you both for the help (:
