### ISSUE TITLE
using YSI on macOS?

### ISSUE THREAD

**Issue by douq** [pawn-lang/YSI-Includes#195]
Hey,

is there any way to use YSI on macOS without changing every blackslash to slash? On macOS the directions are like YSI/y_commands and not YSI\y_commands. Is there any chance to use it without changing every single file from YSI?

I'm using Zeex's PAWN Compiler which is compatible with macos.

Greets

**Comment by Y-Less** [comment]
YSI uses both \ and / for different reasons, and the difference is important.  I'd just say this is a common issue with MacOS - their expensive OS is clearly superior in every way, except in the one way that an OS matters - actually running programs.

In short, no clue, and I have no intention of ever giving that company any money to try and find out.  Sell your mac, buy an equivalent windows computer for half the price, and pocket the difference.

**Comment by Dayvison** [comment]
https://github.com/Adejair/y_routes
You can use this
