### ISSUE TITLE
ptask: array sizes do not match

### ISSUE THREAD

**Issue by rt-2** [pawn-lang/YSI-Includes#198]
Hi, I try:
```
ptask test55[6000](playerid)
{
	printf("test55 for %i", playerid);
	return 1;
}
```
and it gives me this error on the first line:
```
error 047: array sizes do not match, or destination array is too small
```
Now I'm not sure how to use this as there is no documentation on y_timer, precisely ``ptask``?
Thank you,
rt-2

**Comment by IstuntmanI** [comment]
Found these:
https://github.com/Misiur/YSI-Includes/issues/65
http://forum.sa-mp.com/showthread.php?t=579089

Are you sure that you redefined ```MAX_PLAYERS``` correctly, right after including a_samp, just like [I told you on forums](http://forum.sa-mp.com/showpost.php?p=3914428&postcount=3) ? It looks like it is indeed the problem.

Internally I found these lines:
https://github.com/Misiur/YSI-Includes/blob/b99644e1cbe3220bc3704d0dc94fb1f5e5c56f82/YSI_Coding/y_timers/impl.inc#L260
https://github.com/Misiur/YSI-Includes/blob/b99644e1cbe3220bc3704d0dc94fb1f5e5c56f82/YSI_Coding/y_timers/impl.inc#L455
So if ```MAX_PLAYERS``` doesn't have the same value when including ```y_timers``` and when using ```ptask```, it will give you that error.

**Comment by rt-2** [comment]
Yeah ok with further investigation the filterscript that I was doing my test on was configured like you said.
Wow you're a real detective I think I would hire you if I had the money.
Thank you, and sorry for wasting your time.
rt-2
