### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#199]
@Y-Less 
Now that we have official releases, should we adhere to semver? It's not a problem with bugfixes, but say you release your JIT rewrite. Should we bump the major version then? Or as it doesn't introduce BC breaks;  just a minor version? Just thinking aloud, I for one don't like major versions in double digits, though all opensource projects I observe moved to semver. Thoughts?

**Comment by Y-Less** [comment]
I don't like major version bumps generally, unless they are a major rewrite. Even the JIT probably doesn't warrant it (but if anything now will, that is it, especially as requiring more dependencies could be seen as breaking).

**Comment by Misiur** [comment]
Alright, so settled, semver but with conservative dispensing of new major versions. If JIT brings new deps then I think we can bump the verision, rest should stick with minor and patch designators.
