### ISSUE TITLE
Text_GetText not working

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#200]
I decided to implement `Text_Format` as per https://github.com/Misiur/YSI-Includes/issues/20#issuecomment-122580664 . So, the first step is using `Text_GetText`. However something is wrong with the function flow.
```
Text_GetStandard called
Text_GetStandard: 0, -1531307741, -1531307741 y_players:auth y_players:auth
Text_FindEntry called: 0, 13650820
Text_GetStandard: found 0, 13650820, 2
Text_GetStandard: 2, -1, 0, 1
Text_Format/Text_GetText: Text Not Found
```
Something is wrong with `YSI_g_sLangIndex`

This issue is for tracking debug steps.

**Comment by Misiur** [comment]
Alright, it seems `Text_AddEntry` is called before `Text_LoadLocals`, that's a start

Or not - `AddEntry` is called from within `LoadLocals`

Either way, using `YSI_g_sLangIndex` is not what we want, as we want to pass language id manually. I think we can't use `Text_GetText` for our purposes

Or not v2. `Text_GetStandard` uses language parameter correctly, it's just `YSI_g_sTextEntries[slot][e_TEXT_ENTRY_POINTERS]` which has incorrect values.

I did a small temporary change:
```diff
diff --git a/YSI_Players/y_text/impl.inc b/YSI_Players/y_text/impl.inc
index cbf37c1..f52bfa1 100644
--- a/YSI_Players/y_text/impl.inc
+++ b/YSI_Players/y_text/impl.inc
@@ -756,12 +762,14 @@ static stock Text_LoadLocals()
 			langs = Langs_GetLanguageCodes();
 			while ((pos = chrfind('|', langs, pos)) != -1)
 			{
+				++YSI_g_sLangIndex;
+				P:5("Loading %s", YSI_g_sTextSets[i][e_TEXT_SETS_NAME]);
 				format(YSI_g_sCurLoadTextFile, sizeof (YSI_g_sCurLoadTextFile), "YSI/text/%.*s.%.2s", offset, YSI_g_sTextSets[i][e_TEXT_SETS_NAME], langs[pos - 2]);
 				INI_ParseFile(YSI_g_sCurLoadTextFile, "Text_INILoad", _, true, offset + 1, _, true);
 				++pos;
-				++YSI_g_sLangIndex;
 				// We can add code here to load the data from y_styles.
 			}
+			P:5("Text_LoadLocals: %d", YSI_g_sLangIndex);
 			//format(YSI_g_sCurLoadTextFile, sizeof (YSI_g_sCurLoadTextFile), "%.*s", offset, YSI_g_sTextSets[i][e_TEXT_SETS_NAME]);
 			P:6("Text_LoadLocals: Loading style %s (%d)", YSI_g_sCurLoadTextFile, offset);
 			//_Styles_ParseOne(YSI_g_sCurLoadTextFile);
@@ -991,10 +999,13 @@ forward Text_GetStandard(searc
```
and it works, but will probably fail with more than 1 language.

It seems `Text_GetStandard` can't be used with parameters in string (I'm testing on 
`LOGIN_BOX_TEXT = Please enter your passphrase.\nAttempt %d/%d`). I've got to write my own implementation I guess

**Comment by Misiur** [comment]
Alright, I've got prototype working
```pawn
stock _Text_Format(dest[], size, Language:lang, style, search[], ident[], ...)
{
	P:4("Text_Format: %s %d %d %d %s %s", dest, size, _:lang, style, search, ident);

	Text_GetText(search, ident, lang);
	new
		style[E_STYLE_DATA],
		label[E_3D_DATA]
	;
	// Add style settings here
	_Format_SetStyleData(TEXT_MASTER, 0, style[E_STYLE_DATA], label[E_3D_DATA])
	Format_Render(INVALID_PLAYER_ID, lang, dest, size, 0, e_FORMAT_FLAGS_NONE, YSI_g_sReturnText, 0);

	return 1;
}
```

Now only to set styles correctly and it might just work

**Comment by Y-Less** [comment]
Currently you need to forward all the parameters yourself to Format_Render, but that is simpler with y_va now.  The old methods did this:

```pawn
			new
				arg_cur = arg_end,
				ret;
			do
			{
				#emit LOAD.S.pri            arg_cur
				#emit LOAD.I
				#emit PUSH.pri
				arg_cur -= 4;
			}
			while (arg_cur > arg_start);
```

Then called `Format_Render` with all the extra data already on the stack.  The even better method would be to read the data from the previous stack frame, but I don't do that yet.  Also, `_Format_SetStyleData` is important as you might have guessed because the formatting depends on how the text will be displayed, for line lengths and colours.

**Comment by Misiur** [comment]
Yup, I've checked if y_text includes y_va and it already does so one problem fewer. As for style, I think I'll restrict `style` argument only to user-provided style types in the `.yml` file. Then all I'll need to do is utilize `Styles_GetData` and all is set.

**Comment by Misiur** [comment]
Oh. It looks like you can't specify type/style "dialog" in `.yml` file, as it's missing in [`Styles_EntryTag` ](https://github.com/Misiur/YSI-Includes/blob/8d493a210ad908b43f34682d90d2aac327ed7267/YSI_Players/y_text/styles.inc#L194-L269). Am I missing something or that's just not implemented?

**Comment by Y-Less** [comment]
Dialogs are done separately.

**Comment by Misiur** [comment]
Alright, I'm almost done. Two final questions: 
1. Can you define multiple style types for single text? Like this
```pawn
<YML>
  <group name="all">
    <entry name="LOGIN_BOX_TEXT" style="player" />
    <entry name="LOGIN_BOX_TEXT" style="0" time="4000" />
  </group>
</YML>
```
2. If a text contains newline and type is set to gametext, will it convert `\n` into `~n~`?

**Comment by Y-Less** [comment]
1) No.  How would that work?  It would have to be shown twice.

2) It should do.

**Comment by Misiur** [comment]
By 1 I meant that you could use the same text in either SCM or Dialog and it would select the corresponding style. 2 is probably broken, I'll take a look after I'm finished here.

Anyway, last hurdle and I'm done: https://github.com/Misiur/YSI-Includes/blob/8d493a210ad908b43f34682d90d2aac327ed7267/YSI_Players/y_text/styles.inc#L187-L192 - this always executes. I'll dig into properties values to see what's going on.

**Comment by Misiur** [comment]
Oh shit, I had mismatching tags. It works fine now!

https://github.com/Misiur/YSI-Includes/tree/feature/text_format

It works almost correctly. But newlines are broken for all except dialogs :(

Also it needs macroed names for all types, because who's gonna remember `e_STYLE_TYPE_GT_0`.

**Comment by Misiur** [comment]
Alright, added macros. Now onto the actual part:
```pawn
new message[256];
Text_Format_Dialog(message, sizeof message, Langs_GetPlayerLanguage(playerid), $LOGIN_BOX_TEXT, 1, 3);
Text_PasswordBox(playerid, using inline HandleLogin, $LOGIN_BOX_TITLE, message, $LOGIN_BOX_LOGIN, "");
```

This is tricky, but gotta do it somehow.

**Comment by Y-Less** [comment]
The dialogs already do formatting.

**Comment by Y-Less** [comment]
```pawn
Text_PasswordBox(playerid, using inline HandleLogin, $LOGIN_BOX_TITLE, $LOGIN_BOX_TEXT, $LOGIN_BOX_LOGIN, "", 1, 3);
```

**Comment by Y-Less** [comment]
The only thing they don't format are the titles and buttons, because writing it to do four formats in one function was ridiculous.

**Comment by Misiur** [comment]
Huh, should've checked earlier. But whatever, Text_Format may still be useful
