### ISSUE TITLE
Hooking custom publics

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#202]
I think I've already asked this question a few years ago. Anyway, I have a "OnPlayerRegister" public and would like to be able to just use "hook OnPlayerRegister". However I get
```
Y\player/impl.inc(218) : error 017: undefined symbol "ALS_DO_PlayerRegister"
Y\player/impl.inc(218) : error 017: undefined symbol "ALS_G_INT"
```

I see there's [a list](https://github.com/Misiur/YSI-Includes/blob/8d493a210ad908b43f34682d90d2aac327ed7267/YSI_Core/y_als/impl.inc#L205-L296) of hookable publics. Is there a way to extend it?

**Comment by Southclaws** [comment]
I've been hooking custom callbacks [for quite a while](https://github.com/Southclaws/ScavengeSurvive/search?utf8=%E2%9C%93&q=hook+On&type=) so I'm guessing this is just an issue introduced in recent changes.

**Comment by Misiur** [comment]
Oh! That's good. Maybe the suspect should be how I call it:
```pawn
call OnPlayerRegister(playerid);
```

I'll take a closer look

Yup, that's the culprit. Gotta think this one over some more

**Comment by Y-Less** [comment]
That's just a wrapper for `CallLocalFunction`, and only works for default callbacks where their types are known.  But adding more is just a case of duplicating the macros.

**Comment by Southclaws** [comment]
Possibly, I call all my events via `CallLocalFunction` if that helps in any way.

Edit:

> and only works for default callbacks

it has worked for all custom events triggered by my SIF library, and all events throughout the SS code

**Comment by Misiur** [comment]
Alright this worked
```#define ALS_DO_PlayerRegister<%0> %0<PlayerRegister,i>(end:playerid)```

**Comment by Y-Less** [comment]
> it has worked for all custom events triggered by my SIF library, and all events throughout the SS code

I was talking about `call` not `hook`, the latter works fine for all publics now (it didn't use to, but that was a different implementation before amx_assembly allowed for code generation).
