### ISSUE TITLE
ptask filterscript problem

### ISSUE THREAD

**Issue by rt-2** [pawn-lang/YSI-Includes#203]
Hi, ``ptask`` doesn't seem to be called in some filterscript.
How I tested:
 - Everytime I wanted to test ``ptask``, was by connecting a player after reloading the FS.
 - There is 10 Fs loaded, if I load the 10th FS it doesn't work;
 - If I unload the 9th FS, and load my previous FS in the 9th position instead of the 10th, all works;
 - a normal ``task`` would work in all conditions;
Thank you,
rt-2

**Comment by Y-Less** [comment]
Could you produce a small test case please, say using `SendRconCommand` to demonstrate this semi reliably?

**Comment by rt-2** [comment]
After restarting I couldn't reproduce the issue dang it.

**Comment by Y-Less** [comment]
So can I close it?

**Comment by rt-2** [comment]
Yeah I will reopen if I have more infos
