### ISSUE TITLE
y_hooks  "symbol already defined"

### ISSUE THREAD

**Issue by FabricioAndre** [pawn-lang/YSI-Includes#204]
Hey, 
I updated to YSI 4.0 and now y_hooks is causing errors.
Image: http://imgur.com/a/469vs

@edit
It's only happening with OnPlayerConnect and Disconnect.

**Comment by Misiur** [comment]
Put y_hooks include below y_dialog, that should fix it. Maybe even below y_inline

**Comment by FabricioAndre** [comment]
hmm, it worked, thx!
