### ISSUE TITLE
y_text Text_Send doesn't work with anything other than a single player

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#210]
As in title. I'll dig through debug data now.

**Comment by Misiur** [comment]
Oh, should've searched first: #150 #66

**Comment by Misiur** [comment]
https://github.com/Misiur/YSI-Includes/commit/c5c24282f6e7fe2e4e07888a3fc69dac85768f63 Got groups working, that's a start

**Comment by Misiur** [comment]
Now trying `ALL_PLAYERS`. It looks like `Iter_Begin(Player)` returns `1000`. Hmm

**Comment by Misiur** [comment]
Back to working on it, currently debugging this

```pawn
#include <a_samp>
#include <YSI\y_iterate>

main() {
}

public OnGameModeInit()
{
	call OnPlayerConnect(1);
	call OnPlayerConnect(5);
	call OnPlayerConnect(10);

	foreach (new player:Player) {
		printf("Hello %d", player); //1, 5, 10
	}

	printf("%d", Iter_Begin(Player)); //1000 ?!
	printf("%d", Iter_End(Player)); //1000
}
```

Ok, I think I mistook `Iter_Begin` for `Iter_First`. Gotta read more carefully

**Comment by Misiur** [comment]
```pawn
#define Iter_Begin _ITER<Begin>
#define Iter_Begin_InternalA(%0,%1)    (F@s(%1)-F@s(%0))
#define Iter_Begin_InternalB(%0,%2,%1) (F@s(%1)-1-(%2))

#define Iter_End _ITER<End>
#define Iter_End_InternalA(%0,%1)    (F@s(%1)-F@s(%0))
#define Iter_End_InternalB(%0,%2,%1) (F@s(%1)-1-(%2))
```

Now this is confusing - `Iter_Begin` is exactly the same as `Iter_End`? I will go through commit history

**Comment by Misiur** [comment]
@Y-Less I checked and [it was always this way](https://github.com/Misiur/YSI/blob/767cf7ed0baf7dddbc8aacb2e8d06ba990c2cbbe/pawno/include/YSI/y_iterate.inc#L1103-L1118). Is it just an alias? Then why [this code](https://github.com/Misiur/YSI-Includes/blob/a1c7c2d487c681f858766ab1c5af1f47920a6eb6/YSI_Data/y_playerset.inc#L186-L187) does the check at all?

**Comment by Y-Less** [comment]
That should be `cur = Iter_First `.

**Comment by Y-Less** [comment]
They are the same because iterators are circular - you could go around and around if you wanted. So you know you are at the end when you get back to the start.

**Comment by Misiur** [comment]
I get it now. (and I should be bolder in my bugfix and just damn try to break something and see if it sticks)

Closed by https://github.com/Misiur/YSI-Includes/pull/213
