### ISSUE TITLE
Aliases don't inherit permissions

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#214]
When using
`Group_SetGlobalCommandDefault(false);`

```pawn
Command_AddAlt(YCMD:setadminlevel, "sal");

GROUP_ADD<AdminGroup[Y_PLAYER_ADMIN_MAX_LEVEL - 1]>
{
	@YCMD:setadminlevel;
}
```

Makes `sal` unusable as it has different permissions than `setadminlevel`.

**Comment by Y-Less** [comment]
That's by design, not a bug. They are separate commands as far as the system is concerned, they just have the same code. You could want some people to be able to only use one version, say a language specific variant.

**Comment by Y-Less** [comment]
If they inherit permissions, there is no way to give them different ones. If they don't, you can still give them the same ones manually. So this way allows for either requirement.
