### ISSUE TITLE
y_text removes tabulators

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#216]
It's a problem with for example tablist header dialog style.

**Comment by Y-Less** [comment]
I'm not sure what you mean, can you elaborate please?

**Comment by Misiur** [comment]
```pawn
#include <a_samp>

#define _DEBUG 7
#include <YSI\y_text>
#include <YSI\y_timers>

main() {
}

loadtext y[core];

new Language:EN;

public OnGameModeInit()
{
	EN = Langs_Add("EN", "English");

	defer Test();

	return 1;
}

timer Test[1]()
{
	new a[32];
	Text_Format_Dialog(a, sizeof a, EN, $TESTER);
	for(new i = 0; i != 32; ++i) {
		if (a[i] == '\t') {
			print("We have a tab!");
		}
	}

	print(a);
}
```
```
[core]
TESTER = Just\tA\tTest
```

`"We have a tab"` is not printed.

`Text_Format_Dialog` is in essence just uses [`_Text_SetDialogMode`](https://github.com/Misiur/YSI-Includes/blob/e1851f3a5c71088e7b74892716e6cb95cb8d9b43/YSI_Players/y_text/impl.inc#L2418). I noticed it using `Text_MessageBox` so it's not a flaw in `Text_Format`
