### ISSUE TITLE
y_text - loadtext issue when loading the same section on different files

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#218]
Hello, I have some code written on different files which are being included in another one when compiling, the structure looks something like this:

- main_file

- file_one

- file_two

Inside main_file:
```
#include <file_one>
#include <file_two>
```
Alright, if I load the language file inside file_one and I use, for example, Text_Send inside file_two using an identifier loaded previously I get an error (`undefined symbol "DEFAULT_TEXT_SET"`).

Loading the language file again inside file_two doesn't work either, I get an error also (`symbol already defined`).

I guess this makes sense somehow, it works loading different sections but should we define the same text twice or more (defining a new identifier and a new section) if we wanna use the same message on different files? 

I didn't research about this one to be honest, maybe this is how it works after all, but I'd to know what you think about. In my opinion fixing the first method would be the way to go but I don't know how difficult it would be.

Thank you.

**Comment by Misiur** [comment]
Simply include `y_text` again in each file using `loaddtext` (this will only include `y_unique`, don't worry)
