### ISSUE TITLE
y_text error

### ISSUE THREAD

**Issue by AndiChs** [pawn-lang/YSI-Includes#22]
Hey!
I found a new bug in y_text library. The following functions return error when are used:
Text_DialogBox
Text_PasswordBox
Text_ListBox
Text_InputBox
Text_MessageBox
Thanks for developing the YSI includes.
Have a nice day!

**Comment by AndiChs** [comment]
I have the following function:
FUNCTION:SetPlayerDMVCheckpoint(playerid, CP)  
{
if(CP < 16)
{
inline OnDMVDialog(pid, dialogid, response, listitem, string:inputtext[])
{
// some code
return 1;
}
//SetPlayerRaceCheckpointEx(playerid, 0,DMV_CHECKPOINT[CP][0], DMV_CHECKPOINT[CP][1], DMV_CHECKPOINT[CP][2], DMV_CHECKPOINT[CP+1][0], DMV_CHECKPOINT[CP+1][1], DMV_CHECKPOINT[CP+1][2], 5, CP);
if(CP == 5)
{
Text_MessageBox(playerid, using inline OnDMVDialog, $DMV_DIALOG_TITLE, $FIFTH_CHECKPOINT_DMV_DIALOG, $DIALOGS_OK, $DIALOGS_CANCEL);
}
else if(CP == 10)
Text_Send(playerid, $TENTH_CHECKPOINT_DMV);
}
else
SetPlayerCheckpointEx(playerid, DMV_CHECKPOINT[CP][0], DMV_CHECKPOINT[CP][1], DMV_CHECKPOINT[CP][2], 5, CP);
return 1;
}

I receive error on line:
Text_MessageBox(playerid, using inline OnDMVDialog, $DMV_DIALOG_TITLE, $FIFTH_CHECKPOINT_DMV_DIALOG, $DIALOGS_OK, $DIALOGS_CANCEL);

Errors:
Carabines.pwn(272) : error 017: undefined symbol "DEFAULT_TEXT_SET"
Carabines.pwn(272) : error 017: undefined symbol "FIFTH_CHECKPOINT_DMV_DIALOG"
Carabines.pwn(272) : error 029: invalid expression, assumed zero
Carabines.pwn(272) : fatal error 107: too many error messages on one line

**Comment by Y-Less** [comment]
Two problems:

1) No "loadtext" in that file.

2) You aren't using the latest version - the second error was fixed a while ago.

**Comment by AndiChs** [comment]
I am sorry for this dumb question. From where i can download the newest version? My version is from here:https://github.com/Misiur/YSI-Includes .

**Comment by Y-Less** [comment]
Oh, I thought the fix had been committed after this issue:

https://github.com/Misiur/YSI-Includes/issues/17

The solution is in there and tested, but it seems it never made it to this repo.

**Comment by AndiChs** [comment]
Thanks a lot Y!

**Comment by Misiur** [comment]
Hey, just merged that into our repo: https://github.com/Misiur/YSI-Includes/pull/23
