### ISSUE TITLE
Dynamic commands?

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#221]
Is it possible to create commands during runtime?

**Comment by Y-Less** [comment]
I suppose so.  Adding new names for existing commands is trivial with `Command_AltName`, but if you actually want it to do something, you would need a way to add code.  Fortunately, there is a way to add code:

https://github.com/oscar-broman/samp-introspect

It won't allow for very complex new commands, but will do something.

**Comment by Misiur** [comment]
Hm, I've got to rethink that - I wanted to allow users to create their own commands (let's say for opening gates), but introspect gives too much power. I think going with whitelist of already existing commands is better

**Comment by Y-Less** [comment]
If you just have a limited list of features you want them to be allowed to apply to areas of their choice, that's much simpler.
