### ISSUE TITLE
Y_HOOKS problem

### ISSUE THREAD

**Issue by zikamemos1** [pawn-lang/YSI-Includes#222]
![cause](https://user-images.githubusercontent.com/14327710/30243159-24793a2a-957a-11e7-8b89-825cb490abbc.png)
I ask what can cause this? I just changed my ALS method to this and I have no idea about which callback is getting that problem

**Comment by zikamemos1** [comment]
already fixed it ty

**Comment by Southclaws** [comment]
@zikamemos1 for people with the same problem find this via searching, please provide your solution so others may benefit!

**Comment by zikamemos1** [comment]
It was related with OnPlayerEnterDynamicCP and HOOK_REPLACEMENT.

**Comment by Misiur** [comment]
So you fixed it by using `OnPlayerEnterDynCP`? Or something else? Please elaborate. We could make the error more verbose

**Comment by zikamemos1** [comment]
Yes, I fixed it using OnPlayerEnterDynCP. Btw I think HOOK_REPLACEMENT isn't working at all.

**Comment by Y-Less** [comment]
Can you provide an example of that?  There are a lot of tests that say otherwise.  I've no doubt there are missed corner-cases, but I'm pretty sure there are no major holes to the point of it "not working at all".

**Comment by Y-Less** [comment]
Or to put it in a less arrogant way - do you have a minimal repro I can test please?

**Comment by zikamemos1** [comment]
Sorry, I wasn't trying to be arrogant. My eng is just bad. It's  hard to me to explain as I said my eng is bad but  I got that makepublicpointer using HOOK_REPLACEMENT. Sorry again, I really love everything you do with YSI.

**Comment by Y-Less** [comment]
I actually meant my first post was arrogant.

**Comment by Misiur** [comment]
@zikamemos1 so the hook is not working with string replacement?

**Comment by zikamemos1** [comment]
@Misiur  yes

**Comment by Y-Less** [comment]
Again:

> Can you provide an example of that?

I need a repro to test against.

**Comment by Y-Less** [comment]
@zikamemos1 do you have some code I can test please?  Then I can isolate the problem and prove it is fixed.

**Comment by zikamemos1** [comment]
hey @Y-Less  its working fine it was my fault  sorry for causing trouble

**Comment by Y-Less** [comment]
No problem.  Thanks, closed.
