### ISSUE TITLE
An idea for passing arbitrary data to dialog events

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/YSI-Includes#224]
Originally posted here: https://github.com/Open-GTO/mdialog/issues/4

I had a think about this, initially thought it would be easy but then realised storing n arbitrary arguments which could be cells or arrays might be a little more complicated. Then I realised y_va had some changes too so thought I'd bring it up here for some discussion.

This was in the context of Emmet's easyDialog originally and I was going to fork that and implement it there but it might fit better in y_dialog.

The general idea is that you have some event where you have some data that you want passed into the dialog interact event later on, right now you need to devise your own way of storing that data then recalling it once the interact event fires:

```pawn
// you have some `targetid` player ID and you want to access that ID in the dialog response event
// as well as a string and a float for example
Dialog_Open(playerid, "OnMyDialog", "title", "body", "Accept", "Close", "dsf", targetid, someString, someFloat)
```
So the dialog call function has a format specifier string similar to `CallLocalFunction`, this then calls an event with the following signature:
```pawn
public OnMyDialog(playerid, playerid, response, listitem, inputtext, targetid, someString[], Float:someFloat)
```

Thoughts?

**Comment by Y-Less** [comment]
You could use an inline callback, then you get closures already.

**Comment by Southclaws** [comment]
I chatted with the original poster and we both agreed y_inline has caused problems in the past with corrupting the stack - apologies for no issues with repro but it was super difficult to actually repro the issue, I switched dialogs from y_dialog inlines to another library and the crashes stopped. Unfortunately, I did it all in one go because of conflicting symbols in both libraries.

I had a hunch it was sqlite-improved queries running inside inline functions which I think does quite a bit of emit-magic to work with pointers. Which I also removed a while back (hence the use of Redis).

Either way, I've heard a few stories with y_inline, I do like the library but it might be worth giving people an alternative with the ability to pass context through. Just my two cents, I don't actually know how difficult this task is to be honest!

**Comment by Y-Less** [comment]
I'd rather just fix the original than work on doing two ways of doing something.  With that, you'd still need memory allocation and the like, which is often the most common cause of y_inline problems when using heap allocation instead of global memory allocation.  Speaking of which - that could also be the problem.  y_inline doesn't work with normal heap allocated objects like pass-by-reference variables.  So if you use any of those in the closure they won't work.
