### ISSUE TITLE
Groups invalid memory access

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#226]
I can't pinpoint it at the moment, but after updating YSI (I'll check from which commit specifically) I get
```
[debug] Run time error 5: "Invalid memory access"
[debug] AMX backtrace:
[debug] #0 000c3d78 in public Group:_Group_Create@ ()  at D:\Blabla\pawno\include\a_mysql_yinline.inc:176
```

**Comment by Misiur** [comment]
Oh damn, there's quite a lot of commits since then. https://github.com/Misiur/YSI-Includes/commit/153fc2fc852dc17a92328ed1b139b375c84e39d7 is where I had started

**Comment by Y-Less** [comment]
`git bisect`

**Comment by Y-Less** [comment]
I would suspect that the majority are irrelevant, but y_groups does some funky things with compiler passes, as does documentation...

**Comment by Misiur** [comment]
Huh, and I always traversed `git blame` manually. Pretty cool tool, tho not really useful with YSI (there are often follow-up commits fixing what was broken in previous one), and I had to manually apply my branch's commit with added functionality (it even kindly allowed me to keep my changes even when checkouting history's commits).

Either way, I manually checked out back in history: https://github.com/Misiur/YSI-Includes/commit/c589b319ee2f73d0d6006e3226a3d2e6b8835834 this guy breaks stuff. I'll read into it and see what's going on

**Comment by Misiur** [comment]
Found it: https://github.com/Misiur/YSI-Includes/blob/c589b319ee2f73d0d6006e3226a3d2e6b8835834/YSI_Coding/y_inline/impl.inc#L428 `frm` was previously assigned the resolve value, now it isn't and bad stuff happens

**Comment by Misiur** [comment]
https://github.com/Misiur/YSI-Includes/pull/228

**Comment by Y-Less** [comment]
> Pretty cool tool, tho not really useful with YSI (there are often follow-up commits fixing what was broken in previous one),

This is my main issue with git - there's no groups of commits unless you do everything in feature branches and merge in.  Sometimes you want three small commits together as one thing, where you can track the progress but none work individually.  People say do that then squash, but I don't like destroying the history.
