### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by elhanan1233** [pawn-lang/YSI-Includes#227]
im trying to Compile S&S gamemode and some of the files missing!
`pawno\include\YSI\..\YSI_Coding\..\YSI_Coding\y_malloc.inc(139) : fatal error 100: cannot read from file: "..\YSI_Internal\amx_assembly"`
this file dosent exist in the latest version

**Comment by Misiur** [comment]
Do you by any chance have `amx_assembly` or just `amx` folder in your pawno includes folder?

**Comment by Y-Less** [comment]
Are you sure youu updated all the files?  `amx_assmbly.inc` was renamed to `y_thirdpartyinclude.inc` to avoid confusion with the `amx_assembly` library itself.  However, all other files (including `y_malloc`, I just checked) were updated to point to the new location.

**Comment by elhanan1233** [comment]
i just fixed it. but now im stuck with a new issue. the issue is that
there is file in pawno\include\YSI_Coding\y_va called impl.inc since the new update this file gives me error
on southclaw Scavenge and survive gamemode... it gives me argument errors. let me show you example


`C:\Users\Administrator\Desktop\S&S - Old Days\pawno\include\strlib.inc(1641) : error 021: symbol already defined: "sprintf"
C:\Users\Administrator\Desktop\S&S - Old Days\pawno\include\strlib.inc(1715) : error 047: array sizes do not match, or destination array is too small
sss/utils/message.pwn(85) : warning 213: tag mismatch
sss/utils/message.pwn(93) : warning 213: tag mismatch
sss/utils/message.pwn(101) : warning 213: tag mismatch
sss/utils/message.pwn(109) : warning 213: tag mismatch
sss/utils/debug.pwn(78) : warning 213: tag mismatch
sss/core/server/activity-log.pwn(90) : warning 213: tag mismatch
sss/core/admin/core.pwn(554) : error 035: argument type mismatch (argument 3)
sss/core/admin/core.pwn(586) : error 035: argument type mismatch (argument 3)
sss/core/player/commands.pwn(49) : error 035: argument type mismatch (argument 3)
sss/core/player/commands.pwn(113) : error 035: argument type mismatch (argument 3)
sss/core/player/commands.pwn(135) : error 035: argument type mismatch (argument 3)
sss/core/player/whitelist.pwn(254) : error 035: argument type mismatch (argument 3)
sss/core/admin/ban.pwn(239) : error 035: argument type mismatch (argument 3)
sss/core/admin/level1.pwn(232) : error 035: argument type mismatch (argument 3)
sss/core/admin/level1.pwn(274) : error 035: argument type mismatch (argument 3)
sss/core/admin/level3.pwn(147) : error 035: argument type mismatch (argument 3)
sss/core/admin/player-list.pwn(304) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/area69.pwn(594) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/area69.pwn(616) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/ranch.pwn(135) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/ranch.pwn(158) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/ranch.pwn(209) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/ranch.pwn(215) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/ranch.pwn(225) : error 035: argument type mismatch (argument 3)
sss/world/puzzles/mtchill.pwn(270) : error 035: argument type mismatch (argument 3)
C:\Users\Administrator\Desktop\S&S - Old Days\gamemodes\ScavengeSurvive.pwn(715) : warning 209: function "Master_OnScriptExit" should return a value
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase
`

**Comment by Southclaws** [comment]
Since quite a few people have been having issues while I've been off that project, I've recently updated the `redis` branch with the changes required for the new YSI changes and a makefile goal for installing dependencies, provided you have some version of `make` available, you can run `make dependencies` and everything will be installed to `gamemodes/vendor/` directory then run `make dev-windows` to compile it provided you have `pawncc.exe` on your system `PATH`.

**Comment by Y-Less** [comment]
If you still have issues, post in SS issues, unless you determine this is a YSI bug.
