### ISSUE TITLE
y_text no longer including y_unique

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#230]
https://github.com/Misiur/YSI-Includes/commit/457245ca4874844bdfd9615552817a82a07bf400#diff-f44a7278ee3e1dbfd086746b05a702fb

This is a problem for me. Can you explain why you removed it?

**Comment by Y-Less** [comment]
Accident.

**Comment by Misiur** [comment]
https://github.com/Misiur/YSI-Includes/commit/387550448550fadd7cd0f2a770be5e8c414290d6 done
