### ISSUE TITLE
[y_groups] Group_SetCommand isn't working

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#231]
Hello guys, check the next code and read the comments in order to see what's going on. Basically `Group_SetCommand` doesn't have any effect. I didn't add the command in the next code, it's just a normal YCMD command, nothing to see.

https://pastebin.com/2QRXav4Z

I'm using all these YSI includes:
```
#include <YSI-Includes\YSI\y_iterate>
#include <YSI-Includes\YSI\y_bit>
#include <YSI-Includes\YSI\y_text>
#include <YSI-Includes\YSI\y_languages>
#include <YSI-Includes\YSI\y_commands>
#include <YSI-Includes\YSI\y_timers>
#include <YSI-Includes\YSI\y_inline>
#include <YSI-Includes\YSI\y_groups>
```

Thank you.

PD: I assume this is related somehow to issue #179.

**Comment by Y-Less** [comment]
One point, that may or may not be related - alternate commands have their own permissions.  Disabling one version of a command will not disable them all.  I explained the reasons quite recently actually, but in short - this way you can choose to tie them together or not; the other way you would not be able to separate them at all.

**Comment by Vasily-X** [comment]
So you mean that `Group_SetCommand` must be used on each alternative name? @Y-Less 

Just tried that, doesn't work either. I can use both commands and I'm not in the `g_Spawned` group.

**Comment by Y-Less** [comment]
I did mean that, but clearly that's not the issue.  Try including y_groups first - I know order shouldn't matter, but y_groups is special.

**Comment by Vasily-X** [comment]
I changed the code, no results yet:
```
#include <a_samp>
#include <y_groups>
#include <y_commands>

new Group:g_Spawned;

YCMD:help(playerid, params[], help)
{
    // ...
    return 1;
}

public OnGameModeInit()
{
    g_Spawned = Group_Create();

    Command_AddAlt(YCMD:help, "ayuda");

    GROUP_ADD<g_Spawned>
    {
	@YCMD:help;
	@YCMD:ayuda;
    }
    return 1;
}

public OnPlayerConnect(playerid)
{
    Group_SetPlayer(g_Spawned, playerid, false);

    if(Language[playerid] == g_English)
    {
        Command_SetPlayer(YCMD:help, playerid, true);
        Command_SetPlayer(YCMD:ayuda, playerid, false);
    }
    else
    {
        Command_SetPlayer(YCMD:help, playerid, false);
	Command_SetPlayer(YCMD:ayuda, playerid, true);
    }
    return 1;
}
```
It doesn't work, I can use the command while I'm not in the `g_Spawned` group. I'll research about this, if you can help me out with it I'd appreciate it.

Thank you.

**Comment by Y-Less** [comment]
I used this code:

```pawn
#include <a_samp>

#define _DEBUG 5

#include <YSI\y_groups>
#include <YSI\y_commands>
#include <YSI\y_languages>

new Group:g_Spawned;
new Group:g_GEnglish;
new Group:g_GSpanish;
new Language:g_English;

YCMD:help(playerid, params[], help)
{
	SendClientMessage(playerid, -1, "HELP");
	// ...
	return 1;
}

main () {}

public OnGameModeInit()
{
	g_English = Langs_Add("English", "EN");
	g_Spawned = Group_Create();
	g_GEnglish = Group_Create();
	g_GSpanish = Group_Create();

	Command_AddAlt(YCMD:help, "ayuda");

	GROUP_ADD<g_Spawned>
	{
		@YCMD:help;
		@YCMD:ayuda;
	}
	Group_SetCommand(g_GEnglish, YCMD:help, true);
	Group_SetCommand(g_GSpanish, YCMD:ayuda, true);
	return 1;
}

public OnPlayerConnect(playerid)
{
	Group_SetPlayer(g_Spawned, playerid, false);

	if(Langs_GetPlayerLanguage(playerid) == g_English)
	{
		Group_SetPlayer(g_GEnglish, playerid, true);
//		Command_SetPlayer(YCMD:help, playerid, true);
//		Command_SetPlayer(YCMD:ayuda, playerid, false);
	}
	else
	{
		Group_SetPlayer(g_GSpanish, playerid, true);
//		Command_SetPlayer(YCMD:help, playerid, false);
//		Command_SetPlayer(YCMD:ayuda, playerid, true);
	}
	return 1;
}
```

And it worked fine.  Generally you shouldn't mix `X_SetPlayer` and `Group_SetX` - the groups system abstracts from the basic per-player permissions and essentially takes over.  Using both will put the command's permissions out of sync with what y_groups thinks they should be.

**Comment by Y-Less** [comment]
I've had a look.  It did seem to be correctly checking permissions, but `OnPlayerCommandText` wasn't returning 0.  So I've re-imported some functions that were "to be ported" for several years now.

**Comment by Vasily-X** [comment]
That's a good way of doing it actually, yes.

Anyway, as far as I know, you said long time ago that if one of the groups has a command enabled and another one doesn't (assuming the player is inside two groups), the player will be able to use that command.

Okay, so if I'm waiting on OnPlayerRequestClass (not in `g_Spawned` yet) and I'm inside `g_GEnglish` group, I can use the `/help` command even if I didn't spawn, right? Good, that's how y_groups works.

Well, what I was trying to do is set all commands for `g_Spawned` group and then use `Command_SetPlayer` in order to let (or not) the player to use a command alternative name while he is in `g_Spawned`.

After this discussion, I suppose that each command has a "group" which contains the players who can use it. So, the player would be in two groups again (`g_Spawned` and `YCMD:x_Group`), so maybe that's why I can use the command in OnPlayerConnect without being in `g_Spawned`. Am I right? If I am, is there anything I can do to avoid this behavior?

I tried with `OnPlayerCommandReceived` also but I get "SERVER: Unknown command" always.
```
public e_COMMAND_ERRORS:OnPlayerCommandReceived(playerid, cmdtext[], e_COMMAND_ERRORS:success)
{
    if(!Group_GetPlayer(g_Spawned, playerid))
    {
        return COMMAND_ZERO_RET;
    }
    return COMMAND_OK;
}
```

Thank you.

**Comment by Y-Less** [comment]
Use `return COMMAND_DENIED` and `Command_SetDeniedReturn(true);`.  `COMMAND_ZERO_RET` means exactly that - return 0 from `OnPlayerCommandText`.  The other return values can be configured to mean and return different things.  For example:

`COMMAND_ZERO_RET` - Usually returned from a command itself when you want the command to have executed, but still show `unknown command`.
`COMMAND_UNDEFINED` - Command doesn't exist (return 0).
`COMMAND_DENIED` - Player can't use the command (return 1).
`COMMAND_HIDDEN` - Player can't use the command, pretend it doesn't exist at all (return 0).
`COMMAND_DISABLED` - Commands are totally disabled for this player (return 0 or 1, up to you really).
`COMMAND_BAD_PREFIX`, `COMMAND_INVALID_INPUT`, `COMMAND_NO_PLAYER` - Errors.

Most of these can be configured using the new functions I added.  I need to make the defaults slightly better - I think `COMMAND_DENIED` and `COMMAND_DISABLED` should default to returning 1 from `OnPlayerCommandText`.  You might want to look in to `YSI_g_sDisabledPlayers` (which currently has no `Set` function); however, note that this will disable ALL of their commands, with no option to override at all (I might change that, so `OnPlayerCommandReceived` can force processing regardless - in fact, that should probably be able to override any settings at all if desired).

**Comment by Y-Less** [comment]
Right, I've changed the code slightly so now if the return should be `COMMAND_DISABLED` or `COMMAND_DENIED`, `OnPlayerCommandReceived` is still called and can return `COMMAND_OK` to override and still call the function.  Nothing else can be overridden, since those are genuine errors that literally mean a valid command has not been received.  The callback will still be called for your information, but overriding makes no sense since there is nothing valid to call.

**Comment by Y-Less** [comment]
Closed in https://github.com/Misiur/YSI-Includes/commit/3d50b5d2fe8e19417df03e7825b7a55e5fa4d72e

**Comment by Vasily-X** [comment]
Okay, seems that using `Command_SetDeniedReturn` and returning `COMMAND_DENIED` on `OnPlayerCommandReceived` behaves okay now.

I don't know if the next one is the best code I might use there, but it works. Just in case of anyone else needs this:

```
public OnGameModeInit()
{
    Command_SetDeniedReturn(true);
    Group_SetGlobalCommandDefault(false);

    Command_AddAlt(YCMD:help, "ayuda");

    GROUP_ADD<g_Spawned>
    {
        @YCMD:help;
        @YCMD:ayuda;
    }

    GROUP_ADD<g_GroupEN>
    {
	@YCMD:help;
    }

    GROUP_ADD<g_GroupES>
    {
        @YCMD:ayuda;
    }
    return 1;
}

public e_COMMAND_ERRORS:OnPlayerCommandReceived(playerid, cmdtext[], e_COMMAND_ERRORS:success) 
{
    if(!Group_GetPlayer(g_Spawned, playerid))
    {
	Text_Send(playerid, $CMD_DEN_TXT);
	return COMMAND_DENIED;
    }

    switch(success)
    {
    	case COMMAND_DENIED:
    	{
    		Text_Send(playerid, $CMD_DEN_TXT);
    		return COMMAND_DENIED;
    	}
    	case COMMAND_UNDEFINED:
    	{
    		Text_Send(playerid, $CMD_UNDEF_TXT);
    		return COMMAND_OK;
    	}
    }
    return success;
}
```
