### ISSUE TITLE
[y_text] Text_DialogBox - \t on DIALOG_STYLE_TABLIST_HEADERS doesn't work

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#232]
Seems the tab symbols `\t` aren't processed, they don't work.

Text defined: `CREATE_MENU_LIST = Item\tAmount\n{DEEP_SKY_BLUE_2}1. {WHITE}Garage\t%d`

**Comment by Misiur** [comment]
Duplicate https://github.com/Misiur/YSI-Includes/issues/216 - will look later today

**Comment by Vasily-X** [comment]
I suppose the next code must be changed somehow in order to do not affect dialogs.
```
case '\t':
{
	// Somehow display a tab.  Maybe keep track of characters
	// displayed and show "n % 4" spaces.
	arg = 4 - (p & 0x03); // The number of spaces to add.
	static
		sTabs[] = "    ";
	for (new __added; (__added = Format_DoAddString(output, sTabs[4 - arg], p, arg, llen, fakePos)); arg -= __added)
	{
		if (fade) //flags & 4)
		{
			state y_render_fade : y_render_fade_fake;
		}
		else
		{
			Y_RENDER_DO_DISPLAY()
		}
	}
}
```
Location: `YSI_Players\y_text\render.inc` - line 1601

Gonna research about it. Any info related to is welcome @Y-Less.

Thank you.
