### ISSUE TITLE
[y_text] Keys (~k~~KEY_NAME~) don't work on client messages or gametexts

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#235]
I guess that's because of Y_Less didn't add support for them, back in the days keys couldn't be used in client messages. I'll look into this.

EDIT: just realized they don't work on GameTexts either! 

Regards.

**Comment by Vasily-X** [comment]
Okay, I found Format_GetKeys:
https://github.com/Misiur/YSI-Includes/blob/6aa029a027aabf17555b2073426ac1a363641a86/YSI_Players/y_text/load.inc#L193

Seems it compresses the key string using https://github.com/Misiur/YSI-Includes/blob/6aa029a027aabf17555b2073426ac1a363641a86/YSI_Players/y_text/load.inc#L101.

Not sure how correct is that after all, given:
https://github.com/Misiur/YSI-Includes/blob/6aa029a027aabf17555b2073426ac1a363641a86/YSI_Players/y_text/load.inc#L976

On the other hand, I think this bug is caused by `Text_Render`, I didn't find any rendering code for keys yet. Only this:
```
case '\04':
{
	P:6("Text_Render: Key");
	++idx;
}
```
Maybe the key string is not being unpacked, not sure.

**Comment by irinel1996** [comment]
Sadly no progress on this one yet. May you guys take a look into it, please? @Y-Less @Misiur
