### ISSUE TITLE
[y_als/y_hooks] "call" issue on new callbacks

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#245]
Hi, do I have to define custom callbacks inside `y_als` in order to use `call` or `hook` on them? If they're not defined I get an `undefined` error when using `call`. Should I add them inside the `ALS` enum from `y_als/impl.inc`?

Thank you.

**Comment by Southclaws** [comment]
You shouldn't need to modify the library source - hooking custom callbacks works as long as they are called via `CallLocalFunction`.

**Comment by Y-Less** [comment]
You don't need to do anything for `hook`.  If you want to support `call` as well, which as @Southclaws says is just a wrapper around `CallLocalFunction`, you need the following macros.  Note that they can be defined anywhere before your call, you don't have to edit `y_als`:

```pawn
#define ALS_R_DialogResponse 1
#define ALS_DO_DialogResponse<%0> %0<DialogResponse,iiiis>(more:playerid,more:dialogid,more:response,more:listitem,end_string:inputtext[])
```

The `ALS_R_Callback` macro defines the default return.  `ALS_DO_Callback` is everything else - name, specifier string, and parameters.  If there are no parameters, use `(none:)`.  If they have no tag use `(more:x)`.  If they have no tag, and are the last parameter, use `(end:x)`.  If they are a float use `(Float:x)` or `(Float_end:x)`.  Strings use `(string:)`.  For more examples, just look at the existing ones.

I should update the macros slightly - `more:` would make more sense as `_:` to match the real tags.

**Comment by Vasily-X** [comment]
Oh, so using forward once and CallLocalFunction for calling that function from somewhere should be enough. Right?

If one of the parameters is a bool should I do more_bool:param or more:bool:param?

**Comment by Y-Less** [comment]
Yes.
