### ISSUE TITLE
Problems (server crash)

### ISSUE THREAD

**Issue by Zile420** [pawn-lang/YSI-Includes#246]
I have a problem 
picture:  http://prntscr.com/hbxu7d

**Comment by Y-Less** [comment]
Are you on the latest version?  And why are you posting text as an image?

**Comment by Zile420** [comment]
I do not know, it was easier for me
Yes, the latest version

**Comment by Y-Less** [comment]
Well anyway, I'd need to see your code.

**Comment by Zile420** [comment]
I'm sorry that you were waiting for an answer, I was not able to answer you
the problem was nex-ac, simply your package is not compatible with its newer version because the boy has darkened that antique but it does not matter I did it all I now use your pack fine nice everything works and I have everything I do not use other codes
