### ISSUE TITLE
y_text color

### ISSUE THREAD

**Issue by AndiChs** [pawn-lang/YSI-Includes#25]
Hey ! 
I think i have found a new bug in y_text. All the texts i send via Text_Send are red and if i change their color in mode_text_LANG_DATA the texts are black.
Example: 
Gamemode:
Text_Send(playerid, $WELCOME_BACK, SERVER_NAME, GetPlayerUsername(playerid));
mode_text.RO:
WELCOME_BACK = [%s] Bine ai revenit pe server,%s.
mode_text_LANG_DATA:
I can't post the code from here,i don't know why but github block it.
![image](https://cloud.githubusercontent.com/assets/13057135/8394282/0e90a9e8-1d39-11e5-9024-0c8c1860d0ce.png)

Result:
![image](https://cloud.githubusercontent.com/assets/13057135/8394307/77c81a36-1d39-11e5-8fbb-85d7a881a70c.png)

**Comment by Misiur** [comment]
Hm, it seems you have 2 `%s` placeholders, yet you don't pass them. Have you tried text without placeholders, or passing them?

**Comment by AndiChs** [comment]
Sorry, my fault. I didn't copy this code from gamemode.I enter it without checking the gamemode
Text_Send(playerid, $WELCOME_BACK,)
This is from the gamemode:
Text_Send(playerid, $WELCOME_BACK, SERVER_NAME, GetPlayerUsername(playerid));

**Comment by Misiur** [comment]
Reproduced. I'll take a look into it now.

**Comment by Misiur** [comment]
y_text is far more vast than I imagined it would be. Data is read properly from XML. Then some bitmagic commences. I have hunch that it might to do with colour fading failing. There is abandoned incomplete newer version, and the old one doesn't have unit tests so no help there. I'll try to trace what exactly is wrong soon

**Comment by AndiChs** [comment]
Ok, thanks a lot.
Can i help you with something?

**Comment by Misiur** [comment]
You can try my method to finding stuff like that: enable `#define _DEBUG 7`, then follow functions in call stack, and add your messages to find where exactly the value changes. I was somewhere near https://github.com/Misiur/YSI-Includes/blob/98f958e95941407871a6ab693a9698176bc13670/YSI_Players/y_text/render.inc#L154 , as `YSI_g_sTempStyle` carries the colour data. Compile, run, read server_log, rinse and repeat (there is no ollydbg for pawn)

**Comment by Y-Less** [comment]
The mess that is y_text, vast and without unit tests, is the whole reason the new one was in development.  It is so big because it does a silly amount of stuff that isn't documented and even I've forgotten about!  If you can get a copy of that server log with debugging, I might be able to give you a few pointers.

**Comment by Y-Less** [comment]
I might also be able to tell you what the bit magic does if you can point to the code you are referring to.

**Comment by Y-Less** [comment]
Actually, IIRC a lot of the complexity comes from supporting text fades, such as:

```
{>GREEN}%s{RED}
```

That will neatly fade from green to red regardless of how long the inserted string is.  This, sadly, means that some colours can't be calculated and inserted in advance (as does the fact that messages can be `SendClientMessage`, `GameTextForPlayer`, or more).

**Comment by Misiur** [comment]
Test mode

``` pawn
#include <a_samp>
#define _inc_a_samp
#define _DEBUG 7
#include <YSI\y_text>
#include <YSI\y_languages>

loadtext core[ysi_text];

new 
    Language:gLEnglish; 

main() {}

public OnGameModeInit()
{
    gLEnglish = Langs_Add("EN", "English");

    return 1;
}

public OnPlayerConnect(playerid) 
{ 
    Langs_SetPlayerLanguage(playerid, gLEnglish);
    Text_Send(playerid, $YSI_TEXT_NOT_FOUND, "Foobar");
    return 1;
}
```

Log
https://gist.github.com/Misiur/9eae9731ae17ba3e531f

I used `YSI_TEXT_NOT_FOUND` with colour changed to X11_NAVYBLUE, and added
`P:3("Colour is %06x", style[E_STYLE_DATA_COLOUR]);` to Styles_GetData

**Comment by Y-Less** [comment]
Sometimes, I really hate debug level 7!  I've started and instantly close a server, yet still ended up with a 54Mb logfile...

**Comment by Misiur** [comment]
Ok, so let's narrow it a little bit

``` pawn
stock GetColourHash(hash, alpha = 0xAA)
{
    P:3("GetColourHash called: %i, %i", hash, alpha);
    alpha &= 0xFF;
    // Do the REVERSE hash from YHash
    P:4("We are here");
    #pragma tabsize 4
    #if _YSI_USE_X11
        #include "y_colours/x11switch"
    #endif
    #pragma tabsize 4
    P:4("Now here");
    // Do the default code here.
    for (new i = 0; i != MAX_TEXT_COLOURS; ++i)
    {
        new
            iColor = YSI_g_sColours[i][0];
        if (iColor == hash)
        {
            P:4("Returning this %06x", YSI_g_sColours[i][1]);
            return alpha | YSI_g_sColours[i][1];
        }
        else if (iColor == 0)
        {
            P:4("Failing");
            return 0;
        }
    }
    return 0;
}
```

```
[19:14:04] XML_GetKeyValue ending: "colour", "X11_LIGHT_SALMON_4"
[19:14:04] ishex called: "X11_LIGHT_SALMON_4"
[19:14:04] isnumeric called: "X11_LIGHT_SALMON_4"
[19:14:04] GetColour called: "X11_LIGHT_SALMON_4", 170
[19:14:04] YHash called: "LIGHT_SALMON_4", 0, 0, -1, 0
[19:14:04] GetColourHash called: 350379251, 170
[19:14:04] We are here
[19:14:04] Now here
[19:14:04] Failing
[19:14:04] Style colour is 000000
```

x11switch matches [this case](https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Server/y_colours/x11switch.inc#L376-L412), but fails to find anything in switch table. No idea what now

**Comment by Misiur** [comment]
Ok, we've found the culprit

``` pawn
#include <a_samp>
#define _inc_a_samp
#define _DEBUG 7
#include <YSI\y_colours>

main () {
    printf("%06x", GetColour("X11_LIGHT_SALMON_4"));
}
```

@Y-Less have you written x11switch by hand, or generated it somehow? If generated, do you have the generator script?

**Comment by Misiur** [comment]
Ok, so it was commited by @oscar-broman , and I dug deep to find previous version without cached table - https://github.com/Misiur/YSI/blob/767cf7ed0baf7dddbc8aacb2e8d06ba990c2cbbe/pawno/include/YSI/internal/y_x11switch.inc . It works, but of course I'd rather have version with cached table working. I guess it worked earlier, but I didn't see any changes to `GetColour` in YSI-Includes and YSI repositories. I'll try to reach out to him

**Comment by oscar-broman** [comment]
I remember how I did this - I compiled it as `.lst` then added the numbers up.

**Comment by Y-Less** [comment]
I never reproduced the results because I had no idea how you did it in the first place.  I knew about using `-l`, but that only gave a sum and I couldn't be bothered to evaluate the answer myself for them all.

**Comment by oscar-broman** [comment]
After that I just did search & replace to make it do a ton of `printf` statements, then building the switch statement up again using the output.

**Comment by Misiur** [comment]
I did something similar yesterday, though in JS with .replace (and failed as can't force 32 bit mode). I'll write up generator utility, `value & 0x1` mask shouldn't be a problem, though the magic`0x02480120` mask will have to wait.
