### ISSUE TITLE
INI_Int Stop Working

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#252]
I am using INI_Int.

INI_ParseFile(FileName, "LoadDamar_%s", false, true, i);

INI_Int("Type", Damarlar[ DamarID ][DamarType]);

But freezing working samp server when the gamemode started.

I am using latest version YSI v4

**Comment by MaxAndolini** [comment]
@Misiur @Y-Less

**Comment by Y-Less** [comment]
I seriously doubt that is the problem line.  Can you add some print statements and actually confirm that?

**Comment by Y-Less** [comment]
Or does it still fail when using fixes.inc?

**Comment by MaxAndolini** [comment]
I am not using fixes.inc and I approve of this. I have tested it many times and found out from this line.

@Y-Less

**Comment by EvoturK** [comment]
When we use INI_Int like "INI_Int("Type", AnotherArray[ DamarID ]);", it works. But when we use two dimensional array like Damarlar[ DamarID ][DamarType] it doesn't work. 

@Y-Less

**Comment by Y-Less** [comment]
Again, I really don't see how that can be caused by y_ini itself.  Are you sure the arrays and indices are correct?  Not out of bounds?  Have you tried running with crashdetect?  Please do as I say and actually prove that this is a y_ini problem, since there are literally thousands of y_ini uses around and no-one else has ever noticed an issue as fundamental as "integers don't load".  There are many poorly tested corners of YSI, this is not one.

**Comment by EvoturK** [comment]
We runned server with crashdetect. I'm sending screenshot of codes, the file and console.

These screenshots are codes that we have problem with:
https://i.hizliresim.com/POgqP7.jpg
https://i.hizliresim.com/g9B5Zb.jpg

This is our array:
https://i.hizliresim.com/9DO42r.jpg

This is our file:
https://i.hizliresim.com/qJrYPQ.jpg

And console:
https://i.hizliresim.com/MarEL2.jpg

When i was using YSI v1's y_ini i didn't have problem. But when i use YSI v4's y_ini, i get this problem. In file "Type" key's value is 0 but y_ini gets 14. It makes array out of bound problem.

@Y-Less

**Comment by Southclaws** [comment]
[Use markdown and surround code/logs in ``` not screenshots.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

**Comment by Y-Less** [comment]
Indeed, images of code are one of the worst ways you can post things!

**Comment by Y-Less** [comment]
Can you please provide a minimal repro (code and file) to test?

**Comment by EvoturK** [comment]
This is test script and ini file.

@Y-Less 

[Y_INI Test.zip](https://github.com/Misiur/YSI-Includes/files/1560236/Y_INI.Test.zip)

**Comment by MaxAndolini** [comment]
@Y-Less

**Comment by Misiur** [comment]
Yup, this is a bug, but completely different than what you've thought. 

@Y-Less 
```
[dmr]
Type = 0
X = 993.683044
Y = -1272.814208
Z = 14.479687
```
Result
```
[11:09:06] Read Type as 0
[11:09:06] Read  as 993.683044
[11:09:06] Read  as -1272.814208
[11:09:06] Read  as 14.479687
```

It's https://github.com/Misiur/YSI-Includes/issues/192 again, looks like there was a regression somewhere.

Reapplied in https://github.com/Misiur/YSI-Includes/commit/b13adad4dba9bbffc648129261e7ec647d955c54

@EvoturK @MaxAndolini update YSI and report back, thanks

**Comment by EvoturK** [comment]
Problem fixed. Thanks.

@Y-Less @Misiur

**Comment by Misiur** [comment]
Great! I hope this doesn't come back, but in case it does please create a new issue and ping me.
