### ISSUE TITLE
Why/how does multiple includes of the same name work in YSI?

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/YSI-Includes#254]
Recently, on the Discord server, the topic of discussion has been silently ignoring includes.

I've been working with @PatrickGTR to try to get to the bottom of why his mode was not compiling with some pawncc flags but working fine with others. I'm still not sure but it might be -i or -D causing it - anyway that's a discussion for the compiler repo.

After some poking at the code and help from Hual who directed me to this part of the compiler:

https://github.com/Zeex/pawn/blob/master/source/compiler/sc2.c#L318-L338

Which seems like it cuts the include at `dirsep` to get just the file name without the path then uses that in the symbol table lookup.

So the issue with Patrick's codebase is it uses a lot of the same named include files in each module `main.inc`, `impl.inc` and so on. Some of these files were just being flat-out ignored by the compiler but when I made the filename and #include line unique, they were included in compilation.

So, my question is, why does YSI work fine? What's going on here? YSI has `impl.inc` littered throughout the codebase but everything is working okay here so I'd love to know why!

I'm trying to figure out a minimal repro for this so I can open an issue on Zeex/pawn about it as it's the source of much confusion for larger modular gamemodes.#

Thanks!

**Comment by Y-Less** [comment]
```pawn
#undef _inc_impl
```

**Comment by Misiur** [comment]
See also: https://github.com/Misiur/YSI-Includes/wiki/Include-Guards

**Comment by Southclaws** [comment]
Ah, didn't know there was documentation for this thanks!
