### ISSUE TITLE
No i'm not?!

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#260]
I download latest from relases, so ... How it can be old version?
EDIT: You are right, but still errors:
`C:\Users\iwanmf\Desktop\DB\pawno\include\YSI\..\YSI_Visual\y_commands/impl.inc(229) : error 025: function heading differs from prototype
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6528) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6563) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6589) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6630) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6654) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(6676) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(7652) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(7662) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(7847) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(7879) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(8210) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(8223) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(8236) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(8650) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(9159) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(9186) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(10312) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(10558) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(10837) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11213) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11231) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11254) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11373) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11738) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11748) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11758) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11766) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(11845) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(12488) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14397) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14433) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14469) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14530) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14542) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14554) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14566) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14578) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14588) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14598) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14608) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14618) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(14628) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(22512) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(23716) : error 025: function heading differs from prototype
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(23734) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(24043) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(24200) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(24282) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level
C:\Users\iwanmf\Desktop\DB\gamemodes\up-rp.pwn(25044) : warning 219: local variable "using_deprecated_foreach_syntax" shadows a variable at a preceding level`

**Comment by Y-Less** [comment]
Those warnings come when you use the old `foreach (Player, i)` instead of the "new" (only about 7 years old) `foreach (new i : Player)` syntax.

**Comment by Y-Less** [comment]
And looking at that first warning, I still don't believe you are using the latest version - there's nothing relevant on [line 229](https://github.com/Misiur/YSI-Includes/blob/b13adad4dba9bbffc648129261e7ec647d955c54/YSI_Visual/y_commands/impl.inc#L229)
