### ISSUE TITLE
y_hooks how to call callback first

### ISSUE THREAD

**Issue by pawnoholic** [pawn-lang/YSI-Includes#267]
Good day, I was lost in the implementationI my server protection.

How to properly implement a call to definitely hook first?

First hook OnGameModeInit declarated in main.pwn, the second declared after first in protection.inc.

I need to call OnGameModeInit first in protection.inc.

**Comment by Southclaws** [comment]
Check this out, afaik it still works properly: https://github.com/Southclaws/ScavengeSurvive/blob/master/gamemodes/ScavengeSurvive.pwn#L78-L94

**Comment by Y-Less** [comment]
They are called in declaration order, so if you include protection.inc first it will be called first.  You can get around it by mimicking what the macro does underneath:

```pawn
hook OnGameModeInit@000()
{
}
```

**Comment by Dayvison** [comment]
I use this, same Y-Less told above ^
`#define first_hook%1(%2) UNIQUE_FUNCTION<@yH_%1@0...>(%2);UNIQUE_FUNCTION<@yH_%1@0...>(%2)`
