### ISSUE TITLE
y_inline command - cpu went up to 100%

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#269]
Hey Misiur, yesterday you were helping me with updating my script to YSI 4 on SA:MP forum, went fine though.

This is what happened on my server when I used command using y_inline:
![image](https://user-images.githubusercontent.com/29288175/34778892-f4674bbe-f61e-11e7-93ca-50b7ba7e5d8d.png)
Server had ping, but it was not responding at all due to fact that CPU went to 100%
I have never investigated this on YSI 3.1, could you give me any advice please?

```
CMD:igroup(playerid, params[])
{
	new query[300];
	inline OnIGrpMemsLoad()
	{
		Hrac[playerid][IllegalGroupID] = cache_num_rows() == 0 ? 0 : cache_get_row_int(0, 0);
		Hrac[playerid][IllegalGroupMemberID] = 0;
		Hrac[playerid][IllegalGroupListActive] = false;
		Hrac[playerid][IllegalGroupInBank] = false;

		if(Hrac[playerid][IllegalGroupID] > 0)
		{
			cache_get_value_index(0, 1, query, sizeof(query));
			format(query, sizeof(query), ""BLUE"%s (ID %i)", query, Hrac[playerid][IllegalGroupID]);

			new body[1024] = ""WHITE"-", cas[20], h, h_dbID = cache_get_row_int(0, 3);
			if(h_dbID > 0)
			{
				h = GetHouseIDFromDbID(h_dbID);
				if(h != -255)
				{
					format(body, sizeof(body), ""WHITE"%s č. %i", house_index[hInfo[h][zone_id]][zone_name], hInfo[h][zone_count]);
				}
			}

			cache_get_value_index(0, 6, cas);
			strdel(cas, 10, strlen(cas));
			strreplace(cas, '-', ' ');

			new y, m, d;
			sscanf(cas, "iii", y, m, d);

			format(body, sizeof(body), ""INFO"Založeno: "WHITE"%i.%i.%i\n \n"INFO"Sídlo:\n%s\n \n"INFO"Způsob nákupu zbraní:\n"WHITE"%s\n \n"INFO"Počet členů: "WHITE"%i\n"INFO"V kase: "WHITE"$%i\n \n{E7532E}Opustit skupinu", d, m, y, body, cache_get_row_int(0, 5) == 1 ? ("Dovoz") : ("Výroba"), cache_get_row_int(0, 2), cache_get_row_int(0, 4));
			ShowPlayerDialog(playerid, 16, DIALOG_STYLE_LIST, query, body, "Potvrdit", "Zrušit");
		}
		else
		{
			Hrac[playerid][IllegalGroupID] = 0;
			SendClientMessage(playerid, COLOR_WRONG, "(( Na to, abys mohl použít tento příkaz, musíš být členem ilegální skupiny. ))");
		}
	}

	mysql_format(SQL, query, sizeof(query), "SELECT t.id i, r.name, (SELECT count(*) FROM illegal_members WHERE id = i) as count, r.site, r.bank, r.type, r.created	FROM illegal_members t LEFT JOIN illegal_main r ON t.id = r.id where t.member_id=%i LIMIT 1", Hrac[playerid][dbID]);
	mysql_pquery_inline(SQL, query, using inline OnIGrpMemsLoad, "");
	return 1;
}
```
Thank you

**Comment by Misiur** [comment]
Hello!
Can you show me `GetHouseIDFromDbID`? Also which command processor are you using?

**Comment by ghost** [comment]
Thank you for the response, I have been doing couple of tests of same gamemode on my windows test server and it's interesting, becouse sometimes, when I shut down and start server everything works fine and sometimes it does same thing as it did on linux - server just freezes.

I am using improved zcmd and here is the code

```
stock GetHouseIDFromDbID(_dbID)
{
	for(new i; i < MAX_HOUSES; i++)
	{       //i can now see here that IsHouseValid is completely useless here :D
		if(IsHouseValid(i) && hInfo[i][dbID] == _dbID)
		{
			return i;
		}
	}
	return -255; //house doesn't exist
}

forward IsHouseValid(houseid);
public IsHouseValid(houseid)
{
	if(houseid != -255 && hInfo[houseid][dbID] != -1)
	{
		return 1;
	}
	return 0;
}
```

I have also tried replacing pquery_inline with tquery_inline, but it didn't make a change at all

**Comment by ghost** [comment]
Also command processor does not affect it as I have tested it on one inline pquery in another callback and it did same thing too.

**Comment by ghost** [comment]
I'll just repost my statement from BlueG/MySQL issues.

"As last I want to say that I downgraded to YSI 3.1 and I have no problem with that anymore. Well, I doubt that here is something wrong in code as it's doing same thing in multiple different inline pquery calls. However, there must be something in my 150k RP gamemode that has some kind of negative impact on it. When I or someone will figure what it may be, I'll definitely update to latest YSI, but not for now.

Thank you!"

**Comment by Y-Less** [comment]
Without a minimal repro there is literally nothing I can do.

**Comment by ghost** [comment]
Well, I've been trying hard today. Went from redownloading includes, cutting down thousands of gamemode lines to it's minimal functionality, unincluding some old include stuff, nothing worked but I got to this:

When the server was "frozen" and I just sent any rcon command through my console window, this happened. After that server unfreezed and continued to run.

Update() is my public function, where the pquery_inline was called

```
[join] Andrew_Pearce has joined the server (2:127.0.0.1)
c
OnRconCommand: c
[debug] Run time error 6: "Invalid instruction"
[debug]  Unknown opcode 0x78 at address 0x00000000
[debug] AMX backtrace:
[debug] #0 00019818 in public OnRconCommand () at C:\Users\Jakub\Desktop\SFB v1.3.3\0.3.8\pawno\include\YSI\..\YSI_Coding\..\YSI_Coding\y_malloc/funcs.inc:789
[debug] #1 0000006f in public Update () at <unknown file>:0


```

**Comment by Y-Less** [comment]
That sounds like an allocation issue.  Maybe calling `Callback_Release` twice or using a callback after calling `Callback_Release`.

**Comment by Y-Less** [comment]
Could I see your minimal code with steps to reproduce the hang please?  Thanks.

**Comment by ghost** [comment]
Sure, I'll try my best. On last try, when I reproduced the hang the debug message even changed a bit:
```
c
OnRconCommand: c
[debug] Run time error 6: "Invalid instruction"
[debug]  Unknown opcode 0x78 at address 0x00000000
[debug] AMX backtrace:
[debug] #0 000079e0 in public OnRconCommand () at C:\Users\Jakub\Desktop\SFB v1.3.3\0.3.8\pawno\include\YSI\..\YSI_Coding\..\YSI_Internal\y_version.inc:222
[debug] #1 000197dc in public Update () at C:\Users\Jakub\Desktop\SFB v1.3.3\0.3.8\pawno\include\YSI\..\YSI_Coding\..\YSI_Coding\y_malloc/funcs.inc:785
```
I compiled gamemode with latest Zeex's compiler with -d3, latest YSI release, BlueG's MySQL R41-4.
I use inline_pqueries in two locations of my gamemode. A first one is inside of commands (using zcmd) and second location is just one inline pquery, inside of the timer's callback:

```
SetTimer("Update", 1000, 1);

//Inside of Update()

//other infoboxes above

else if (IsPlayerInRangeOfPoint(i, 2, -2521.6365, 2294.9038, 4.9844))
						{
						    if (!IsPlayerInAnyVehicle(i) && Hrac[i][InIB] == false )
						    {
								inline OnIllegalGroupGDCheck()
								{
									if(cache_num_rows() > 0 && cache_get_row_int(0, 0) == 1 && cache_get_row_int(0, 1) == 0)
									{
									    PlayerTextDrawSetString(i, TextdrawIB[i], "Nechat si vyrobit zbran muzes stisknutim klavesy '~k~~CONVERSATION_YES~'.");
	 									PlayerTextDrawShow(i, TextdrawIB[i]);
										PlayerPlaySound(i, 1084, 0, 0, 0);
										Hrac[i][InIB] = true;
									}
									else
									{
									    PlayerTextDrawSetString(i, TextdrawIB[i], "Nejsi zde vitany, mozna bys mel odejit.");
		 								PlayerTextDrawShow(i, TextdrawIB[i]);
										PlayerPlaySound(i, 1084, 0, 0, 0);
										Hrac[i][InIB] = true;
									}
								}
								format(string, sizeof(string), "SELECT gun_perm, type FROM illegal_members t LEFT JOIN illegal_main z ON t.id=z.id WHERE member_id=%i", Hrac[i][dbID]);
								mysql_pquery_inline(SQL, string, using inline OnIllegalGroupGDCheck, "");
						    }
						}
```

If neccesary, I can reproduce and post debug with command call too

**Comment by ghost** [comment]
This is what I've put on same bottom of OGMI callback and there's no problem anymore. 
```
inline FirstInlineFunction() {}
mysql_pquery_inline(SQL, "SELECT 1", using FirstInlineFunction, "");
```

**Comment by Misiur** [comment]
IIRC I asked already about what you mean by `latest YSI` and you said you download not from releases but using github's `Download ZIP`. Please confirm that is the case

I thought maybe inlines in timer are problematic, but could not reproduce. So, I'd like to ask you for:
1. All plugins you use
2. All includes you use
3. All foreign functions with `#emit` in them you pasted into your gamemode

**Comment by ghost** [comment]
I'm sorry for unclear information here. The only YSI I downloaded is the one from releases tab marked as latest release. As I said, it is not happening only from inline inside the timer. I'm using inlines in like 6 commands, where it does the same thing. I just reproduced it in timer, so I could be sure that it's not related to commands. I now realized, that I didn't say I use 0.3.8 RC-4 server (happened on both win and linux) I might try today to test it on 0.3.7, but YSI 3.1 was doing fine on 0.3.8.

```
#include <a_samp>
#include <sscanf2>
#include <YSI\y_timers>
#include <YSI\y_ini>
#include <a_mysql>
#include <a_mysql_yinline>
#include <streamer>
#include <zcmd>
#include <YSI\y_iterate>
#include <SmartChat> //I have tried to uninclude this
#include <SpikeStrip> //I have tried to uninclude this
#include <mdc> //I have tried to uninclude this
```

server.cfg
`plugins crashdetect streamer Whirlpool mysql sscanf`

I haven't found any #emit used in my gamemode.

Thanks.

**Comment by Misiur** [comment]
Oh! Can you download the includes via [github's download as zip](https://github.com/Misiur/YSI-Includes/archive/YSI.tl.zip)? I want to rule out it's not some older bug. A new release package is way overdue, and if the current one is buggy then it's doubly so.

Standard set up of includes and plugins, so definitely not the cause.

**Comment by ghost** [comment]
I feel so stupid right now. Downloaded latest zip, then compiler prompted me to download amx_assembly and it seems to be working flawlessly right now, thank you again.

**Comment by Y-Less** [comment]
Don't feel stupid!  A poor release system is on us, not you!  Glad you got it working, and sorry for all the pain it caused.
