### ISSUE TITLE
4.0.1 BIG PROBLEM ( TESTED ON BEFORE VERSIONS )

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#270]
So YSI isn't saving files good...It now save from bottom to top, i downgraded to older YSI and everything works fine 
http://forum.sa-mp.com/showthread.php?p=3980259#post3980259

**Comment by samp-pinch** [comment]
Someone fucks me hard, i did not change anything and started working, lol...xD

**Comment by Y-Less** [comment]
INI files don't have an order.  It doesn't matter what comes before what because, so y_ini saves in the most efficient order it can.  So it was working before and it is working now, even if the order is different.
