### ISSUE TITLE
Invalid instruction using y_va on a FS

### ISSUE THREAD

**Issue by Dayrion** [pawn-lang/YSI-Includes#271]
Hello. I was just testing some things and I fall on that errors.
***There is my code::***
```pawn
// In the include
APP(const message[], va_args<>)
	return printf("<aa> %s", va_return(message, va_start<1>));

// In the filterscript
CMD:test_i(playerid, params[])
{
	APP("Without param");
	APP("With param: %i", playerid);
	return 1;
}
```
This code doesn't crash in a gamemode but it does on a basic filterscript.
***Logs:***
```
[11:26:19] [debug] Run time error 6: "Invalid instruction"
[11:26:19] [debug]  Unknown opcode 0x208 at address 0x0003EB18
[11:26:19] [debug] AMX backtrace:
[11:26:19] [debug] #0 0003eb18 in APP(message[]=@00061cfc "Without params") at C:\Users\Utilisateur\Desktop\Server files\pawno\include\tests_a.inc:61
```
***List of includes used in the filterscript.***
```
#include <a_samp>
#include <izcmd>
#include <crashdetect>
#include <sscanf2>
#include <YSI\YSI\y_iterate>
#include <YSI\YSI\y_hooks>
#include <YSI\YSI\y_va>
#include <streamer>
```
I don't have anymore code than this command (except OnFilterScriptInit & OnFilterScriptExit but both of them return 1;)
Edit: That one doesn't crash and execute properly.
```pawn
APP(const message[], va_args<>)
{
	new string[300];
	va_format(string, sizeof(string), message, va_start<1>);
	return printf("<aa> %s", string);
}
```

**Comment by Y-Less** [comment]
Passing the return from `va_return` to a varargs function like `printf` is sketchy, sorry.

**Comment by Dayrion** [comment]
What do you mean @Y-Less ?

`va_return` can't be used in another function using va_args like my example?

**Comment by Y-Less** [comment]
No, functions like `printf` can't have `va_return` as a parameter because it messes up the heap.  I need to look in to it more.

**Comment by Dayrion** [comment]
It seems to be the same thing with `SendClientMessage`. Also, I saw you removed `sprintf`, why?

**Comment by Y-Less** [comment]
sprintf was a synonym for va_return, but conflicted with another popular include.  I would suggest you just use `va_format` if `va_return` doesn't work.

**Comment by FreddyB1** [comment]
I'm having the same issue using `SendClientMessage`, I never experienced such problem in earlier versions of YSI. I hope this gets fixed.

**Comment by Y-Less** [comment]
Can someone provide a minimal repro please, because I've run several tests on the latest version and been unable to reproduce a crash.

**Comment by Dayrion** [comment]
Code:
```pawn
#include <a_samp>
#include <YSI\YSI\y_va>

APP(message[], va_args<>)
	return printf("<prefix> %s", va_return(message, va_start<1>));

main()
{
	APP("Something");
	APP("Something, %i", 5);
}
```
Output:
```
[16:21:47] [debug] Run time error 6: "Invalid instruction"
[16:21:47] [debug]  Unknown opcode 0x208 at address 0x0000DEB4
[16:21:47] [debug] AMX backtrace:
[16:21:47] [debug] #0 0000deb4 in APP (message[]=@000051b8 "Something") at STests.pwn:5
[16:21:47] [debug] #1 0000dfac in main () at STests.pwn:10
[16:21:47] Script[gamemodes/STests.amx]: Run time error 6: "Invalid instruction"
```

**Comment by Y-Less** [comment]
OK.  Good news, I've replicated the crash.  Better news, the crash doesn't happen at all in the JIT branch.  Bad news, that means I need to figure out why they are different.

**Comment by Y-Less** [comment]
e67987f827907f291aee2ff08a980c6657ffd635
