### ISSUE TITLE
Branch_JIT | ptask - array sizes do not match, or destination array is too small

### ISSUE THREAD

**Issue by Kaperstone** [pawn-lang/YSI-Includes#272]
Apparently there isn't a way to specify a branch?

Anyway, I am using the JIT branch together with Zeex's Pawn libs and when I compile it gives me this error
```
timers.inc(3) : error 047: array sizes do not match, or destination array is too small
```
The timer has nothing in it, this is the entire code
```
ptask task[1000](playerid) {
  
}
```

**Comment by Y-Less** [comment]
Do you do this:

```pawn
#include <a_samp>
#include <YSI>
#undef MAX_PLAYERS
#define MAX_PLAYERS 10
```

?  If so, move the `MAX_PLAYERS` redefinition to before including YSI.

**Comment by Y-Less** [comment]
And be warned that Branch_JIT is not at all stable, and liable to strange changes at any moment.  I know for a fact that y_inline doesn't work yet since I've just been working on it.
