### ISSUE TITLE
y_iterate and malloc

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#275]
YSI\..\YSI_Coding\..\YSI_Coding\y_malloc/heapalloc.inc(132) : warning 235: public function lacks forward declaration (symbol "VA_OnScriptInit")

and

how to use auto iter_add for vehicles

	stock Iter_CreateVehicle(modelid, Float:x, Float:y, Float:z, Float:angle, color1, color2, respawn_delay, addsiren = 0)
	{
		#if _FOREACH_ACTORS
			new
				ret = CreateVehicle(modelid, x, y, z, angle, color1, color2, respawn_delay, addsiren);
		#else
			#pragma unused addsiren
			new
				ret = CreateVehicle(modelid, x, y, z, angle, color1, color2, respawn_delay);
		#endif
		broadcastfunc Iter_VehicleDo(true, ret);
		#if _FOREACH_LOCALS
			Iter_Add(LocalVehicle, ret);
		#endif
		return ret;
	}

#if _FOREACH_LOCALS ??

**Comment by Misiur** [comment]
[`_FOREACH_LOCALS` is by default set to `1`, unless you explicitly define `FOREACH_NO_LOCALS` (or if `SendChat` is defined, which is defined if you include `a_npc`)](https://github.com/pawn-lang/YSI-Includes/blob/e67987f827907f291aee2ff08a980c6657ffd635/YSI_Data/y_iterate.inc#L388-L393). As for the warning, are all YSI includes on top of your script? Which ones do you use and in what order?

**Comment by Y-Less** [comment]
Fixed, thanks.

What do you mean how do you use `Iter_Add` for vehicles?  It is done automatically, in that code you posted...

**Comment by MaxAndolini** [comment]
YSI\..\YSI_Coding\..\YSI_Coding\y_malloc/heapalloc.inc(132) : warning 235: public function lacks forward declaration (symbol "VA_OnScriptInit")
