### ISSUE TITLE
y_malloc

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#276]
YSI..\YSI_Coding..\YSI_Coding\y_malloc/heapalloc.inc(132) : warning 235: public function lacks forward declaration (symbol "VA_OnScriptInit")

Still unresolved.

**Comment by MaxAndolini** [comment]
And 
*** YSI Warning: y_malloc set up via "CallLocalFunction", memory corruption is a remote possibility

**Comment by Y-Less** [comment]
I'll look at the first warning later, not sure why it is still happening.  Can you try manually include `<YSI_Server\y_scriptinit>` before your other YSI includes please?

As for the second one, that's only a problem if you use `malloc` in `OnGameModeInit`.

**Comment by MaxAndolini** [comment]
Same again

#include <a_mysql>
#include <streamer>
#include <yom_buttons>
#include <ZCMD>
#include <sscanf2>
#include <crashdetect>
#include <YSI_Server\y_scriptinit>
#include <YSI\y_timers>
#include <YSI\y_utils>
#include <mSelection>
#include <gvar>
#include <discord-connector>
#include <geo_ip>
#include <easyDialog>
#include <callbacks>
#include <attachments>

And i dont use malloc.

**Comment by MaxAndolini** [comment]
@Y-Less

**Comment by Southclaws** [comment]
This was happening on CI builds for sampctl but recent commits seemed to have solved it:

https://travis-ci.org/Southclaws/sampctl/jobs/334624443#L536

**Comment by MaxAndolini** [comment]
Not solved.

**Comment by MaxAndolini** [comment]
@Y-Less @Southclaws @Misiur

**Comment by Misiur** [comment]
https://github.com/pawn-lang/YSI-Includes/issues/275#issuecomment-361373081

Did you update YSI to latest git version?

**Comment by MaxAndolini** [comment]
Yea i say still unresolved.

**Comment by Misiur** [comment]
```pawn
#include <a_samp>
#include <a_mysql>
#include <YSI_Server\y_scriptinit>
#include <YSI\y_timers>
#include <YSI\y_utils>

main() {
}
```
```
Pawn compiler 3.10.6	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Header size:           2104 bytes
Code size:           230840 bytes
Data size:            59312 bytes
Stack/heap size:   17039360 bytes; estimated max. usage=1414 cells (5656 bytes)
Total requirements:17331616 bytes

Done.
[Finished in 1.1s]
```

Can you fill in some other includes you have? The snippet you gave above is missing some of the includes.

**Comment by MaxAndolini** [comment]
I am using zeex compiler btw

**Comment by MaxAndolini** [comment]
```
#include <a_mysql>
#include <streamer>
#include <yom_buttons>
#include <ZCMD>
#include <sscanf2>
#include <crashdetect>
#include <YSI\y_timers>
#include <YSI\y_utils>
#include <mSelection>
#include <gvar>
#include <discord-connector>
#include <geo_ip>
#include <easyDialog>
#include <callbacks>
#include <attachments>
```

**Comment by MaxAndolini** [comment]
@Y-Less @Southclaws @Misiur @Zeex

**Comment by earltacs** [comment]
I am not any of the contributors nor developers but somehow have you tried testing to remove everything and add them back one by one see which include does that? like just use an empty .pwn and compile it looking for the problem... Maybe some include you are using are not compatible with the latest YSI library and causing some invalid messages to the compiler.

or maybe even try putting YSI libraries above of everything...

**Comment by Y-Less** [comment]
You do realise this is only a warning right?  You can safely ignore it, which is good because while I intend to get to it, other more important things keep coming up (like actual problems).

**Comment by Y-Less** [comment]
It is also a warning I fixed already and told you a week ago, and just double-checked that I fixed.  The commit is literally here:

https://github.com/pawn-lang/YSI-Includes/commit/5e1dc70bdc39f898166436fe5592ced259769fbf

If you are still getting the warning, either you didn't update or you've got some strange setup no-one else can reproduce (in which case we need way more information).
