### ISSUE TITLE
previewmodels

### ISSUE THREAD

**Issue by earltacs** [pawn-lang/YSI-Includes#278]
Are you gonna somehow implement this
[preview model](http://forum.sa-mp.com/showthread.php?t=570213) by gammix into y_dialog? or not? or has it been implemented already? just asking though.

**Comment by Y-Less** [comment]
I wasn't planning to myself, but I'm happy to accept a pull request.

**Comment by earltacs** [comment]
ohhh... okay .. I was already expecting that, I just had to ask to be sure :)
