### ISSUE TITLE
Support Custom Tags

### ISSUE THREAD

**Issue by pawnoholic** [pawn-lang/YSI-Includes#281]
Hi, can replace standart callbacks arguments for y_hook?

Example:
```
hook OnPlayerConnect(Player:id)
{
    return Y_HOOKS_CONTINUE_RETURN_1;
}
```

**Comment by Misiur** [comment]
If by `replace` you mean add a new tag to some parameters, then it compiles without warnings as under the hood it's a completely new function.

**Comment by pawnoholic** [comment]
Yes, it's true.

Then the problem is in the macro MAX_PLAYERS

```
#if defined MAX_PLAYERS
    #undef MAX_PLAYERS
#endif
#define MAX_PLAYERS (Player:1000)
```
should I correct the warning about tag mismatch?

I can rename the macro MAX_PLAYERS something else.

**Comment by pawnoholic** [comment]
Okey, no problem, I fixed.

```
#if defined MAX_PLAYERS
    #define _MAX_PLAYERS (Player:MAX_PLAYERS)
#else
    #define _MAX_PLAYERS (Player:1000)
#endif
```

**Comment by Y-Less** [comment]
Yeah, adding a tag to `MAX_PLAYERS` will mess up basically every include and existing piece of code there is.  Though there are advantages to having it tagged, since you can do:

```Func(MaybePlayer:playerid)
{
    new ValidPlayer:pid;
    if (ValidatePlayer(playerid, pid))
    {
        // Do stuff here with `pid`, which you now know is valid.
        // Any function that takes a `ValidPlayer:` tag can skip the normal checks.
    }
}

**Comment by pawnoholic** [comment]
there is whether what the univarsal method add custom tags?

```
#define MAX_WEAPON_TYPES (WeaponType:16)

new Iterator:WeaponTypes<MAX_WEAPON_TYPES>;

stock WeaponType:DefineWeaponType(...)
{
    new WeaponType:id = Iter_Free(WeaponTypes);

    Iter_Add(WeaponTypes, id);

    return id;
}
```

**Comment by Y-Less** [comment]
What?

**Comment by pawnoholic** [comment]
I changed my mind about tags.
