### ISSUE TITLE
Y_INI overwrites data

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#282]
```PAWN
new INI:File = INI_Open("data/settings.ini");
INI_SetTag(File, "Settings");
INI_WriteString(File, "name", gm_Name);
INI_WriteString(File, "version", gm_Version);
INI_Close(File);
```
Results into:
![image](https://user-images.githubusercontent.com/35696477/36385881-448641ec-1594-11e8-8fea-0da9490af7ad.png)

"name" overwrites "version" when I switch them:
```PAWN
new INI:File = INI_Open("data/settings.ini");
INI_SetTag(File, "Settings");
INI_WriteString(File, "version", gm_Version);
INI_WriteString(File, "name", gm_Name);
INI_Close(File);
```

If I add anything that is not `INI_WriteString` to the bunch, it freezes the server:
```PAWN
new INI:File = INI_Open("data/settings.ini");
INI_SetTag(File, "Settings");
INI_WriteString(File, "name", gm_Name);
INI_WriteString(File, "version", gm_Version);
INI_WriteInt(File, "some_int", 5);
INI_Close(File);
```

It also happens with integers and without a tag.

**EDIT**:
Doesn't seem to be malfunctioning in an empty gamemode.

**EDIT2**:
It works fine in an empty gamemode with the same includes as my main project. While in my main project, it doesn't matter where I put it, it malfunctions.

**EDIT3**:
The debug print in `INI_WriteString` prints the correct data too.

**EDIT4**:
It also happens after I strip everything else from my main project.

**Comment by ghost** [comment]
I got it working now. I had to include y_ini before my first OnGameModeInit call:
```PAWN
#include <YSI\y_ini>
//==================================================================================
//
//                                  ONGAMEMODEINIT
//
//==================================================================================

public OnGameModeInit()
{
    gamemode_Init();

    // Dummy class
    AddPlayerClass(281, 0.0, 0.0, 7.0, 0.0, 0, 0, 0, 0, 0, 0);

    #if defined main_OnGameModeInit
        return main_OnGameModeInit();
    #else
        return 1;
    #endif
}
#if defined _ALS_OnGameModeInit
    #undef OnGameModeInit
#else
    #define _ALS_OnGameModeInit
#endif

#define OnGameModeInit main_OnGameModeInit
#if defined main_OnGameModeInit
    forward main_OnGameModeInit();
#endif

//==================================================================================
//
//                                  INCLUDES
//
//==================================================================================

// YSI
#include <YSI\y_hooks>
#include <YSI\y_iterate>
#include <YSI\y_utils>
#include <YSI\y_timers>
```
Related to https://github.com/pawn-lang/YSI-Includes/issues/196#issuecomment-332768996 ? Because including y_utils before anything else instead of y_ini fixes the issue too.

**Comment by Y-Less** [comment]
That's a bit odd that that would solve that specifc issue.  However, all of YSI should probably come first.
