### ISSUE TITLE
y_utils

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#284]
YSI_Core\y_utils.inc(430) : warning 201: redefinition of constant/macro (symbol "isnull(%1)")

**Comment by Southclaws** [comment]
It seems you or another library you're using is redefining `isnull` before YSI is being included.

**Comment by Y-Less** [comment]
Yep.  There are at least two different common variations of the define about.  I have a better version, but I've refrained from putting it in YSI as it might cause more of these warnings.  However, if people get them anyway...

But yeah, find and remove the other definition.
