### ISSUE TITLE
[y_hooks/CrashDetect] Run time error on 'INVALID_X_ID'

### ISSUE THREAD

**Issue by ReinasL** [pawn-lang/YSI-Includes#286]
CrashDetect prints errors on hooked functions, when INVALID_PLAYER/VEHICLE/TEXTDRAW(etc.)_ID is used. ( only on hook'ed functions - public are fine )

In this case, player is falling and receiving, dmg from world ( issuerid - INVALID_PLAYER_ID ):

[debug] Run time error 4: "Array index out of bounds"
[debug] AMX backtrace:
[debug] #0 0005d174 in ?? (65535, 19478032) from basic.amx
[debug] #1 0003b59c in ?? (0, 65535, 1101876625, 54, 3, 1, 0, 0, 20, 0, ... <1073741813 arguments>) from basic.amx
[debug] #2 0000a0e4 in public OnPlayerTakeDamage (0, 65535, 1101876625, 54, 3) from basic.amx

**Comment by Misiur** [comment]
Which YSI branch?
You just create an empty hook and this happens?

**Comment by ReinasL** [comment]
Mistake on my end, i was running in callback debug mode - sending message to issuerid and not checking if it's actually valid "playerid".
