### ISSUE TITLE
y_hooks preventing same callback from getting called

### ISSUE THREAD

**Issue by Cubko** [pawn-lang/YSI-Includes#289]
Hey, I don't have any issue at this time, but I wonder if is it possible to do.

I hooked OnPlayerStateChange in an include (for anticheat purposes), which removes player from the vehicle after using a cheat to get in. However this also calls OnPlayerStateChange in gamemode, I'm not saying that here's something wrong, but I don't want to call it in this case. I got an idea, that I could do it through global variable check and just return 1 on top of callback, but maybe it's possible to do it by some better way I'm not aware of. Thank you.

**Comment by Y-Less** [comment]
Yes, return -1 or -2.

**Comment by Southclaws** [comment]
As far as I know, if your include comes first you can simply `return Y_HOOKS_BREAK_RETURN_1;`.

edit: Y_Less beat me by 17 seconds!

**Comment by Cubko** [comment]
Wow, thanks for the quick responses 😄 now I'm a bit smarter again
