### ISSUE TITLE
Text Not Found but all is ok

### ISSUE THREAD

**Issue by groot-samp** [pawn-lang/YSI-Includes#292]
I'm getting Text Not Found text, I'm using y_text and y_languages.
My code:
```
#include <YSI-Includes\YSI\y_hooks>

loadtext lang[vehicle_funcs];

anywhere in the same file: Text_Send(playerid, $MESSAGE_ERROR_TESTA);
```

text file:
`[vehicle_funcs]
MESSAGE_INFO_TESTA = test a
MESSAGE_INFO_TESTB = test b`

I have more sections in my text file, vehicle_funcs is the unique section that doesn't work.

Debug:
`__PS_S called: 0
Text_GetText: loop1 lang:vehicle_funcs| 0 18 lang:vehicle_funcs| 0
Text_GetStandard called
Text_GetStandard: 0, 2041437337, 1780165709
Text_GetStandard: 1, 2041437337, -742765799
Text_GetStandard: 2, 2041437337, 1780166173
Text_GetStandard: 3, 2041437337, -1384043049
Text_GetStandard: 4, 2041437337, -262892755
Text_GetStandard: 5, 2041437337, -373730485
Text_GetStandard: 6, 2041437337, 831874953
Text_GetStandard: 7, 2041437337, -933592937
Text_GetStandard: 8, 2041437337, -1896061697
Text_GetStandard: 9, 2041437337, 1780174696
Text_GetStandard: 10, 2041437337, 1583574388
Text_GetStandard: 11, 2041437337, 1221787792
Text_GetStandard: 12, 2041437337, 1071096670
Text_GetStandard: 13, 2041437337, -1420738688
Text_GetStandard: 14, 2041437337, 1255618546
Text_GetStandard: 15, 2041437337, -1666479782
Format_Render called: 0, 0, Text Not Found, 1022, 0, 0,  (+0)
Text_Render: Char
Format_DoAddChar: T 0 1022
Text_Render: Loop: p = 1, llen = 1021, output = "T"
Text_Render: Char
Format_DoAddChar: e 1 1021
Text_Render: Loop: p = 2, llen = 1020, output = "Te"
Text_Render: Char
Format_DoAddChar: x 2 1020
Text_Render: Loop: p = 3, llen = 1019, output = "Tex"
Text_Render: Char
Format_DoAddChar: t 3 1019
Text_Render: Loop: p = 4, llen = 1018, output = "Text"
Text_Render: Space
Format_DoAddChar:   4 1018
Text_Render: Loop: p = 5, llen = 1017, output = "Text "
Text_Render: Char
Format_DoAddChar: N 5 1017
Text_Render: Loop: p = 6, llen = 1016, output = "Text N"
Text_Render: Char
Format_DoAddChar: o 6 1016
Text_Render: Loop: p = 7, llen = 1015, output = "Text No"
Text_Render: Char
Format_DoAddChar: t 7 1015
Text_Render: Loop: p = 8, llen = 1014, output = "Text Not"
Text_Render: Space
Format_DoAddChar:   8 1014
Text_Render: Loop: p = 9, llen = 1013, output = "Text Not "
Text_Render: Char
Format_DoAddChar: F 9 1013
Text_Render: Loop: p = 10, llen = 1012, output = "Text Not F"
Text_Render: Char
Format_DoAddChar: o 10 1012
Text_Render: Loop: p = 11, llen = 1011, output = "Text Not Fo"
Text_Render: Char
Format_DoAddChar: u 11 1011
Text_Render: Loop: p = 12, llen = 1010, output = "Text Not Fou"
Text_Render: Char
Format_DoAddChar: n 12 1010
Text_Render: Loop: p = 13, llen = 1009, output = "Text Not Foun"
Text_Render: Char
Format_DoAddChar: d 13 1009
Text_Render: Loop: p = 14, llen = 1008, output = "Text Not Found"
Text_Render: Final render?
Text_Render: Yes!
Format_DoDisplay a: 0, 00FF00, "Text Not Found"
Text_Render: p = 14, output = "Text Not Found"
00000054 = T
00000065 = e
00000078 = x
00000074 = t
00000020 =
0000004E = N
0000006F = o
00000074 = t
00000020 =
00000046 = F
0000006F = o
00000075 = u
0000006E = n
00000064 = d
Text_Render end
__PS_N called: 0, 0`

**Comment by groot-samp** [comment]
If I change section name to `funcs_vehicle` works, it's a very strange thing ...

**Comment by Y-Less** [comment]
OK, that sounds like an issue with the section search and matching, not sure why, but as you have a solution this will have to be slightly low-priority.  Having said that, I have been working on y_text a bit recently.

**Comment by Y-Less** [comment]
But thanks for the details, that's actually quite useful.

**Comment by groot-samp** [comment]
It usually happens when section name starts with the letter v, examples:
```
vehicle_funcs
vfuncs
vc_funcs
```

`vehicle_funcs` is not working but `pvehicle_funcs` yes.
I can't understand the problem because I have others sections starting with letter `v` and they are working, for example:
`vc_mdlpreview
vc_editor`

**Comment by adri1samp** [comment]
It's a error with section names.
I've got same error with other sections, finally changed name sections to 'section_a, section_b, section_...' and it is working good.

**Comment by groot-samp** [comment]
It's a error with section names.
I've got same error with other sections, finally changed name sections to 'section_a, section_b, section_...' and it is working good.

**Comment by groot-samp** [comment]
Ok, finally solved, it was happen because I have more than 16 sections, and the limit is 16.
Just increased `Y_TEXT_MAX_SETS` and solved!
