### ISSUE TITLE
Linux path separators ?

### ISSUE THREAD

**Issue by RodrigoDornelles** [pawn-lang/YSI-Includes#293]
> Windows path separators `(\)` in #include directives are converted to native path separators on non-Windows platforms. On Linux they correspond to `(/)`

how to solve this problem? Errors are occurring because of this.
```pawno/include/YSI/../YSI_Coding/y_va.inc(125) : fatal error 100: cannot read from file: "..\YSI_Internal\y_globaltags"```

**Comment by Misiur** [comment]
It's a bit more complicated, see https://github.com/pawn-lang/compiler/wiki/File-Inclusion
Always use `\` when dealing with YSI, it does not matter if you are compiling on linux or windows.

**Comment by Y-Less** [comment]
This is now solved in 5.x (and it wasn't easy), but for now stick to `\`.
