### ISSUE TITLE
No more Iter_Init for 2d iterators when NESTED_ELLIPSIS is present

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#3]
If NESTED_ELLIPSIS is present, utilise it.

**Comment by Misiur** [comment]
Note: In foreach 3 there are two types of multiiterators (New `Iter<X, Y>` with different behaviour), so gotta watch out for those tricky detection macros.

**Comment by Y-Less** [comment]
I had already thought of this, it is in fact the reason I requested nested ellipses in the first place.  I would suggest making Iter_Init defined as nothing in that case, since then people can still use it or not.
