### ISSUE TITLE
OnDialogResponse not called when using (y_dialog & y_inline)

### ISSUE THREAD

**Issue by wuzi** [pawn-lang/YSI-Includes#31]
After including y_dialog and y_inline, OnDialogResponse is not being called.

Probably it changed the ID of the dialogs.
But i didn't use Dialog_Get function.

I want to port my dialogs to y_inline, but, there's too many and i want to keep the server running while i'm porting.

Is there any solution?

**Comment by Y-Less** [comment]
Yes - port them on your dev server and keep the live server running the old version until you finish.  Don't upload have done code to production!

**Comment by wuzi** [comment]
You're right, that's a bad habit of mine.
There's no need to hurry anyway.
