### ISSUE TITLE
y_va delay bug?

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#312]
Video [Bug shown cuz low English]:
https://vimeo.com/287803996
Function:
```
stock PDetector(playerid, Float:range, boja, const fmat[], va_args<>)
{
	new Float:Pos[3];
	GetPlayerPos(playerid, Pos[0], Pos[1], Pos[2]);
	foreach(new i : Player)
	{
		if(GetPlayerVirtualWorld(i) == GetPlayerVirtualWorld(playerid))
		{
			if(IsPlayerInRangeOfPoint(playerid, range, Pos[0], Pos[1], Pos[2]))
			{
				new str[145];
				va_format(str, sizeof (str), fmat, va_start<4>);
				return SendClientMessage(i, boja, str);
			}
		}
	}
	return 1;
}
```
And
```
stock SendAcMessage(boja, const fmat[], va_args<>)
{
	foreach(new i : Player)
	{
		if(PI[i][pAdmin] >= 1)
		{
			new str[145], str2[145];
			va_format(str, sizeof (str), fmat, va_start<2>);
			format(str2, sizeof(str2), ""CRVENA"// AC // "BELA"%s", str);
			return SendClientMessage(i, boja, str2);
		}
	}
	return 1;
}
```

**Comment by Y-Less** [comment]
So this only happens in 4.X because it tries to install y_va code lazily, instead of at mode start-up. The simplest way to fix it is to add this to `OnScriptInit`:

`va_format(Q@, 1, "");`

**Comment by samp-pinch** [comment]
Would this be fixed in 5.x? Or have some code so i can fix it now... It sucks cuz i add 5-10sec to server starting time :P

**Comment by Y-Less** [comment]
That is the fix.  It could be moved in to y_va itself, within OnScriptInit in there.  Would you like to make a pull request for that?

**Comment by Y-Less** [comment]
I just checked, this is fixed in 4.x already:

https://github.com/pawn-lang/YSI-Includes/blob/476f36b728359909dc955a49560c8e49fc8d072c/YSI_Coding/y_va/impl.inc#L244-L248
