### ISSUE TITLE
[Q] About declaring strings inside hooked public function

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#313]
Hi, I've been thinking about one thing lately and I can't figure correct answer. In short, I have gamemode separated in multiple fiiles, and I'm using y_hooks for getting callbacks work. To give an example, inside OnDialogResponse, I use one big string with 256 cells, that's because in most of dialogs I'm formatting string with something I need too output. Now the question, when I declare those strings in each hooked OnDialogResponse, does the used memory count together or it's getting called sequentionally? Thanks a lot!

**Comment by AGraber** [comment]
Hooks are internally just public functions which get called in order. When the function ends, the memory of your declared variables is freed as well, so this goes for hooks too.

**Comment by ghost** [comment]
Okay, thanks a lot for quick and clear answer!
