### ISSUE TITLE
[y_hooks] 'already defined' error when hooking functions in multiple includes

### ISSUE THREAD

**Issue by BlackBank** [pawn-lang/YSI-Includes#315]
For some reason i get an error if i use y_hooks in two(or more) includes, looks like y_unique is not working?

The error i get from the compiler:
```
symbol already defined: "@yH_OnPlayerDisconnect@003"
```

**Comment by Y-Less** [comment]
You need to include y_hooks in every file in which you use hooks (and include it last in those files).

**Comment by BlackBank** [comment]
I did include y_hooks in every file where hooks are used.

I use btw the follow path to include y_hooks in those files:
```
#include <YSI-Includes\YSI\y_hooks.inc>
```

I even did remove the library(sscanf, sql, etc) includes i use, but still i get the same error.

**Comment by Y-Less** [comment]
Last?

**Comment by BlackBank** [comment]
I did, but i tried yesterday without '.inc' in the include path and now it works for some reason...

No errors and it's working fine now.
