### ISSUE TITLE
[5.x] FINAL__ macro fails with tags

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#319]
```pawn
#include <a_samp>
#include <YSI_Server\y_scriptinit>

FINAL__ Text:WelcomeTextdraw = TextDrawCreate(40.0, 40.0, "Welcome!");

public OnPlayerConnect(playerid)
{
    TextDrawShowForPlayer(playerid, WelcomeTextdraw);
}

main(){}
```

This code fails because `FINAL__` doesn't consider the possibility of the value being tagged, causing the compiled code to look like the following:

```pawn
stock const  Text:WelcomeTextdraw ;@yI_Text:WelcomeTextdraw ();@yI_Text:WelcomeTextdraw (){ScriptInit_ForceFinal_(_: Text:WelcomeTextdraw ,_:( TextDrawCreate(40.0, 40.0, "Welcome!")));}
```

The resulting function has a tag of `@yI_Text:` and is called `WelcomeTextdraw` which is already defined and makes compilation fail:
```
test.pwn:4 (error) symbol already defined: "WelcomeTextdraw"
```

Some kind of tag parsing is required so the tags don't become part of the function

**Comment by Y-Less** [comment]
Fixed, thanks.  Part of the fix also now does full tag checks, so the compiler alerts you when the RHS is wrong.

**Comment by AGraber** [comment]
Don't forget to push the changes!
