### ISSUE TITLE
[4.x] y_va long string problem

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#321]
It seems like y_va's max formatting string is 145?
Because this code:
```
forward SendAntiCheatMessage(colour, const fmat[], {Float, _}:...);
public SendAntiCheatMessage(colour, const fmat[], {Float, _}:...)
{
	foreach( new i : Player )
	{
		if(PI[i][pAdmin] > 0)
		{
			new str[256], str2[145];
			va_format(str, sizeof (str), fmat, va_start<2>);
			format(str2, sizeof(str2), ""CRVENA"ANTICHEAT | "BELA"%s", str);
			SendClientMessage(i, colour, str2);
		}
	}
}
```
do not print full message, if i do str2[146] it just won't print anything ( In one example this print message than last 3 digits of color code... )

**Comment by Misiur** [comment]
This is not a limitation of y_va, but from samp itself: see https://wiki.sa-mp.com/wiki/Limits

**Comment by samp-pinch** [comment]
I saw that, but for LONGER messages with the SAME color count it works :/
I saw that, but i belive its SA:MP limit, i'll pass string to another line :D
