### ISSUE TITLE
[5.x] __REF nowhere to be found, compilation fails

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#323]
In `y_thirdpartyinclude.inc`, it is stated that to get `__REF`, `amx_assembly` must be updated, but there's no such definition in the latest `amx_assembly`
https://github.com/pawn-lang/YSI-Includes/blob/b79f10013c2a2d3d97010f00a7d467a75bb40bd6/YSI_Core/y_core/y_thirdpartyinclude.inc#L331-L335

Perhaps you have unpushed changes?

**Comment by AGraber** [comment]
Oh, I see now, it's in your fork. Merging Zeex/amx_assembly#34 will fix this.

**Comment by Y-Less** [comment]
Done, thanks.
