### ISSUE TITLE
Little y_Hooks scripting help?

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#324]
```
hook SendClientMessage(playerid, color, const message[])
{
	if(strfind(message, "yy", true) != -1 )
	{
		print("Founded it!");
		return 1;
	}
	else return print("xx");	
}
```
This does not even print "xx" (like SCM isn't executed but it is executed), how to fix this? :D 
I'm kinda new to hooking system :D

**Comment by Y-Less** [comment]
You can only hook callbacks, not functions.

**Comment by samp-pinch** [comment]
Oh, any idea to hide "Audio stream:" message? I saw that include before (HideAudioMsg.inc) but its deleted :\
( IT WAS WORKING, TESTED 100%, ITS POSSIBLE )

Can i make plugin and do magic with g_invoke?

**Comment by Y-Less** [comment]
No.  That message is there to protect content owners.  If you steal a song and stream it, people can see whose bandwidth you are leeching off.
