### ISSUE TITLE
__COMPILER_sNAMEMAX shouldn't matter to YSI

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#325]
Hardcoded lengths should now make use of this macro to be compatible with such compiler forks. Some libraries might actually benefit from this, not in the sense of "faster/optimized YSI", but considering that some YSI libraries like to expand symbols a lot for internal use (mainly y_hooks, no longer having to use short versions of callbacks, being more obvious on what is being hooked).

**Comment by Y-Less** [comment]
I know, but several things that manipulate publics, like y_hooks and y_inline, need updating, maybe other places I'm not sure. I also don't know the extent of required changes in dependencies.

**Comment by AGraber** [comment]
v5.05.0403 fixes this with proper `FUNCTION_LENGTH` usage and definition.
