### ISSUE TITLE
y_hooks repeating unique ids

### ISSUE THREAD

**Issue by brunorsch** [pawn-lang/YSI-Includes#329]
It seems that y_hooks is repeating the unique id used to differ functions. My mistake? Or a real error?

core/pickups.pwn(3) : error 021: symbol already defined: "@yH_OnGamemodeInit@003"
core/vehicles.pwn(3) : error 021: symbol already defined: "@yH_OnGameModeInit@003"
profs/limpador.pwn(44) : error 021: symbol already defined: "@yH_OnPlayerEnterCheckpoint@003"
profs/lixeiro.pwn(147) : error 021: symbol already defined: "@yH_OnPlayerEnterCheckpoint@003"
profs/lixeiro.pwn(228) : error 021: symbol already defined: "@yH_OnGameModeInit@003"

Sorry if info posted is not relevant, but I don't know what I can post to help. Thanks in advance.

**Comment by Y-Less** [comment]
Yes, your mistake.  You need to include y_hooks in ever file in which you use it.

**Comment by brunorsch** [comment]
I know. I was including y_hooks in every file. And it's the unique include of all the files.

If it's really my mistake, this is not the cause.

**Comment by spacemud** [comment]
Are you hooking the same callback twice in one file?

**Comment by Y-Less** [comment]
Or do you include other files after including y_hooks?  Bear in mind that if those other files also include y_hooks, you're basically overriding theinclude you just made.

**Comment by Y-Less** [comment]
Just wrote this:

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_hooks/faqs.md

**Comment by brunorsch** [comment]
No includes in the same file, I'm including just y_hooks, and no callback "overloading"

I'll make a more deep investigation, please give me a few minutes. Maybe I making a big mess here.

**Comment by brunorsch** [comment]
Ok, I don't know how, but I fixed it. 

I made a completely reinstall of YSI and re-included y_hooks in all files I wanna use, and magically it compiled. Surely was my mistake, but I don't know what was.
