### ISSUE TITLE
[5.x] Add equivalent of PREINIT__ and POSTINIT__ for script exits.

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#332]
Pretty simple, I use these a lot and I have some tasks that need to be executed at exit, and without that much control on order it would become a problem (ex. Saving misc. data before closing a Global Databse/File/Whatever handle).

I can implement it myself since the implementation for scriptinit is not that difficult and it's straight forward, but I just want to be sure what to name it: `POSTEXIT__` and `PREEXIT__` seem right for me.

**Comment by Y-Less** [comment]
Done
