### ISSUE TITLE
PREINIT__ functions expect "INIT_STRIP_TAGS__" 

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/YSI-Includes#338]
Related to 66c65b3a9d05b34e693b09720721ad6d59b96a5c, all `PREINIT__` functions now expect "INIT_STRIP_TAGS__" in the function:

```
PREINIT__ Something()
{
    return 1;
}
```

Would result in:
`(warning) tag mismatch: expected tag "INIT_STRIP_TAGS__", but found none ("_")`

**Comment by Y-Less** [comment]
Do you have a repro for this?  I copied and pasted that function and got nothing when compiling.

**Comment by AGraber** [comment]
Sorry, it happens when you do `return 1;` or any other number, I updated the code. I could do `return;` though.

**Comment by Y-Less** [comment]
The functions should be void, so yes just use 'return'.
