### ISSUE TITLE
[y_colours] Warning "_@_SetColourHash"

### ISSUE THREAD

**Issue by TheManyula** [pawn-lang/YSI-Includes#345]
I'm using the 5.x branch and the 3.10.9 pawn compiler. I've included ```#include <YSI_Server\y_colours>``` which gives me the following warning.

```(warning) symbol is never used: "_@_SetColourHash"```

Not really high priority but a simple "stock" should do. Thanks!

**Comment by Y-Less** [comment]
Care to make a pull request?

**Comment by TheManyula** [comment]
There you go: https://github.com/pawn-lang/YSI-Includes/pull/346
