### ISSUE TITLE
Slow?

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#347]
Hello world!
I **WAS** using Y_INI, Y_VA, Y_ITERATE...
I asked one developer and he said that if i include only Y_INI (example) that i will include alot of unnecessary stuff...
He said he doesn't use YSI only samp natives because as If he includes only y_commands (example) that its going to include lot of unnecessary code...

btw. that developer is the developer of the world no. 1 server in the world (SA:RPG developer) 👍

**Comment by Y-Less** [comment]
OK, and what does that have to do with speed?
