### ISSUE TITLE
[5.x] error 040: duplicate "case" label (value 10)

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#349]
`pawno\include\YSI_Storage\y_ini\y_ini_impl.inc(1098) : error 040: duplicate "case" label (value 10)`
I just downloaded 5.x branch from github button (I did not used sampctl cuz i do not know how cuz i get pawn.json error)...
Here is line:
`case '\1' .. ' ': {} // Whitespace, skip it.`

**Comment by tr1xy** [comment]
@Y-Less close this, please.
