### ISSUE TITLE
Problem with YSI 5.x

### ISSUE THREAD

**Issue by orsx** [pawn-lang/YSI-Includes#358]
I try to run my server, but always I get the error **Script[bare.amx]: Run time error 4: "Array index out of bounds"**.

Nothing works!

**Comment by Y-Less** [comment]
Try update amx_assembly - I believe I've fixed that now.

**Comment by orsx** [comment]
I already update amx_assembly, but it has not yet been commited - I think.

**Comment by George480** [comment]
Get it from here: https://github.com/Y-Less/amx_assembly

**Comment by orsx** [comment]
Thank you! it works.

**Comment by Y-Less** [comment]
Glad to hear it. And thanks for pointing out that I didn't push the changes upstream!
