### ISSUE TITLE
YSI Y_Va error.

### ISSUE THREAD

**Issue by denisbranisteanu** [pawn-lang/YSI-Includes#364]
Hello, i have a error "Bare `___` usage found - make sure it is a function parameter." when i'm trying to format with ysi va. When i use on localhost works, but don't work on a host.

**Comment by kazebravo** [comment]
Up.

I've checked it and this is related to amx_assembly.

@Y-Less can help us?

**Comment by Crayder** [comment]
@kazebravo Maybe it would help if you explained how exactly you determined what the problem was? Naturally I feel like this was an assumption based on some stuff you seen from crashdetect, but this information isn't always accurate to a point so more info from you would help.

**Comment by Y-Less** [comment]
Fixed.
