### ISSUE TITLE
Best way to get INI value without INI_ParseFile?

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#366]
Is it possible to read VALUE from ini file, ex:
Password=123456
I do not want to parse the file just open Name_Surname.ini and get Password's value...
Is it possible and how if yes?

**Comment by Y-Less** [comment]
Parse it with a different callback. Better yet, do that and put the password in its own tag.

**Comment by samp-pinch** [comment]
How could I do that?
I would assign it so owner can do like /inicheck [Name] and i want to print it in a textdraw, only that, I cannot parse it to PlayerInfo[id][pPass] cuz [id] is not connected or is alredy used so it would give other player wrong data...

**Comment by Y-Less** [comment]
Why are you printing passwords? And just save it to a different variable. You could even use an inline within the command.
