### ISSUE TITLE
Foreach overflow?

### ISSUE THREAD

**Issue by PatchwerkQWER** [pawn-lang/YSI-Includes#38]
HI,

I have problem with 2D iterator. Here are screenshots. First http://prntscr.com/7vn745

Second http://prntscr.com/7vn7b4

Code (first)

```
stock SellPlayerVehicle(playerid, modelid){
    new id = Iter_Free(PlayerVehicle[playerid]);
    if(id == -1) return -2;
    MsgF(playerid, -1, "SellPlayerVehicle - %d", id);
    Iter_Add(PlayerVehicle[playerid], id);
```

Code (Second)

```
stock SellPlayerVehicle(playerid, modelid){
    new id = Iter_Free(PlayerVehicle[playerid]);
    if(id == Iter_End(PlayerVehicle[playerid])) return -2;
    MsgF(playerid, -1, "SellPlayerVehicle - %d", id);
    Iter_Add(PlayerVehicle[playerid], id);
```

I don't know why it doesn't work (doesn't return -2). Some ideas?

Thanks

**Comment by Crayder** [comment]
Try: `if(id == -1)`

-1 means the iterator is full. Technically the end of the iterator doesn't mean it is full, but I see what you were trying to do.

**Comment by PatchwerkQWER** [comment]
I know. I always use `if(id == -1)`. You  can see first code. Here is solution with `id == -1`but it doesn't work. I don't know why.

**Comment by Crayder** [comment]
Try:

```
stock SellPlayerVehicle(playerid, modelid){
    new id = Iter_Free(PlayerVehicle[playerid]);
    if(Iter_Add(PlayerVehicle[playerid], id) == -1) return -1;
    MsgF(playerid, -1, "SellPlayerVehicle - %d", id);
```

Also, study up on multi-iterators. You shouldn't be using an iterator array for this vehicle ownership thing. Multiple players can't own the same vehicle (I'm guessing, if they can your script is weird), so a multi-iterator would be easiest to handle.

**Comment by Y-Less** [comment]
`Iter_Add` and `Iter_Free` return `cellmin` on failure:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Data/y_foreach/impl.inc#L960

The reason is that `-1` is now considered a valid value for some iterators.  In fact `cellmin` could be, but is less likely to be.  I like `cellmin` because it has no opposite value - it is NOT `-cellmax` (that is `cellmin + 1`.  In fact, it is more like `-0`, so I use it for invalid values.

This iterator will happily return `-1` as a valid value:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Data/y_foreach/iterators.inc#L252-L259

**Comment by Crayder** [comment]
What? Maybe that's why I was facing so many bugs not long ago. I've been using -1. 

How should a -1 situation be dealt with if it is somehow valid? Like, my script only requires indexes 0-99. Should I be checking for `cellmin` too? 

@PatchwerkQWER: The correct code would be:

```
stock SellPlayerVehicle(playerid, modelid){
    new id = Iter_Free(PlayerVehicle[playerid]);
    if(Iter_Add(PlayerVehicle[playerid], id) == cellmin) return -2;
    MsgF(playerid, -1, "SellPlayerVehicle - %d", id);
```

**Comment by Y-Less** [comment]
Just because your script only needs 0-99 doesn't mean they all do.  -1 is in theory valid in some iterators - even if you don't personally use it y_iterate still has to handle it, and does.

**Comment by PatchwerkQWER** [comment]
@Crayder You don't know how work my Vehicle System. It doesn't depend on vehicle id. So I doesn't need new multi iterator.

@Y-Less Okay, now it works.So, Can I use everywhere `cellmin` istead of `-1`? (If I get it)
