### ISSUE TITLE
[5.x] y_timers - Heap allocation is VERY unstable.

### ISSUE THREAD

**Issue by Vasily-X** [pawn-lang/YSI-Includes#381]
This code
```pawn
#include <a_samp>
#include <YSI_Coding\y_timers>

main() { }
```
produces this warning:
> warning 237: user warning: Heap allocation is VERY unstable.  Use `YSI_NO_HEAP_MALLOC` to disable it, or `YSI_YES_HEAP_MALLOC` to disable this warning.

Not really sure why it's happening.

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_malloc/faqs.md

**Comment by Y-Less** [comment]
I've tried to improve the message slightly, but sometimes I wonder if people even bother reading them:

https://github.com/pawn-lang/YSI-Includes/blob/3943b019475ae24cc16df30e0e8bf9abbdcb640c/YSI_Coding/y_malloc/y_malloc_warning.inc#L8

**Comment by CodeZulan** [comment]
Sir I defined #define YSI_NO_HEAP_MALLOC

It didn't give me warning but it only shows [Finished in 4.9s] after I compile it

**Comment by Y-Less** [comment]
Good?

**Comment by CodeZulan** [comment]
Nah it doesn't say the usual Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2017, ITB CompuPhase thingy
