### ISSUE TITLE
[4.x] y_commands _Command_IsPrefix euro sign

### ISSUE THREAD

**Issue by Mrucznik** [pawn-lang/YSI-Includes#382]
Hello. There is a bug, that causes run time error, when player type € on chat as a first character.

> [07/08/2019 16:21:59] Run time error 4: "Array index out of bounds"
> [07/08/2019 16:21:59]  Attempted to read/write array element at index 4 in array of size 4
> [07/08/2019 16:21:59] AMX backtrace:
> [07/08/2019 16:21:59] #0 000615d8 in @yH_OnPlayerText@004 (playerid=0, text[]=@04086bf8 "") at [...]\dependencies\YSI-Includes\YSI\..\YSI_Visual\y_commands/impl.inc:1326
> [07/08/2019 16:21:59] #1 00035578 in public OnPlayerText (0, 67660792) at [...]\dependencies\YSI-Includes\YSI_Data\..\YSI_Coding\..\YSI_Internal\y_cgen.inc:115

Code from impl.inc:1326
```pawn
mhook OnPlayerText(playerid, text[])
{
	// Is this prefix used anywhere?
	if (_Command_IsPrefix(text[0])) //1326
	{
		// The default return for OnPlayerText is opposite OnPlayerCommandText.
		return !Command_ReProcess(playerid, text, 0);
	}
	// Default return, do nothing.
	return 1;
}
```

This error occurs only when Y_COMMANDS_USE_CHARS is on.

**Comment by Y-Less** [comment]
Fixed, thanks.  I think you managed to find the only character for which this applies.
