### ISSUE TITLE
Multi-dimensional iterator ad Iter_SafeRemove crashing a server

### ISSUE THREAD

**Issue by PawnMario** [pawn-lang/YSI-Includes#383]
`                        new next_player_item = itemid;
						Iter_SafeRemove(PlayerItem[playerid], next_player_item, itemid);`
This will crashing the server. How i can a remove iter in a multi-dimensional iterator?

**Comment by Y-Less** [comment]
I doubt that's the problem, I'll need to see more surrounding code.

**Comment by PawnMario** [comment]
Okay its solved. My bad, i was a function here with normal SaveRemove. All looks good thanks.
