### ISSUE TITLE
Question about y_hooks order

### ISSUE THREAD

**Issue by samp-pinch** [pawn-lang/YSI-Includes#385]
Hello, how can I be sure that for example

```
hook OnGameModeExit()
{
	return Y_HOOKS_CONTINUE_RETURN_1;
}
```

inside "modules/core/server/database/api.inc"

will be executed **LAST** _or_ **AFTER**
```
hook OnGameModeExit()
{
	mysql_close(dbHandler);
	return Y_HOOKS_CONTINUE_RETURN_1;
}
```
inside "modules/core/players/database/api.inc" ?

I know there is a way but I forgot how :(

**Comment by vedrandev** [comment]
try to reboot your computer

**Comment by Y-Less** [comment]
Include the api first.
