### ISSUE TITLE
Dialog_Get returning wrong id

### ISSUE THREAD

**Issue by samphunter** [pawn-lang/YSI-Includes#39]
Dialog_Get will keep returning wrong id, if the dialogid is used manually (not via Dialog_ShowCallback), as y_dialog will not set it to -1. (none of the scripts claims ownership of dialog_ids allocated by Dialog_ObtainID)

**Comment by Misiur** [comment]
Thanks! I have 2 requests for future reference: Please create tests for your fixes (which fail without your fix), and run the tests at https://github.com/Misiur/YSI-Test-Suite (you might need to change code to match your number of cores), and create commit messages in english. I can't test this at the moment and I'll get back to this soonest tommorow evening, I hope this doesn't brake anything.

**Comment by samphunter** [comment]
Not sure where to ask, but 81 tests fail with my setup (116 on some settings). I tested it before my merge, and it fails as well. Is this normal (known bugs), or is my setup wrong?

**Comment by Misiur** [comment]
81 here as well. Just keep it on that number (or lower)
