### ISSUE TITLE
[5.x] y_commands

### ISSUE THREAD

**Issue by dakyskye** [pawn-lang/YSI-Includes#393]
After [this](https://github.com/pawn-lang/YSI-Includes/commit/969df61e72cf73cb37d96dcba81c545564a75ef5) commit in YSI 5.x, I updated my dependencies to the latest versions and suddenly y_commands stopped working. Commands are not executed no-more, server gives `SERVER: UNKNOWN COMMAND`.

**Comment by Y-Less** [comment]
Do you know exactly which commit caused this?  I know you mentioned one, but there have been a few recently.

**Comment by dakyskye** [comment]
I'm not sure, I updated the YSI after this, the last commit.

**Comment by Y-Less** [comment]
Yes, but I mean you could have pulled several at once.

**Comment by dakyskye** [comment]
Yes, I know that. What I say is that I only updated after the last commit and the first time I ensured dependencies was about one to two weeks ago.

**Comment by Y-Less** [comment]
Yes I understood that.  I meant could you do a bisect or something to see if you can find the exact problem commit please?

**Comment by dakyskye** [comment]
Yes for sure, I will try to find the exact problem commit.

**Comment by Y-Less** [comment]
I found it.  I also discovered that my normal test suite was not including (thus not testing) y_commands!

**Comment by dakyskye** [comment]
I’m glad you found it. I had no time this day to dig into commits, sorry.
