### ISSUE TITLE
[5.x] y_als/y_hooks results undefined error on new functions

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#394]
```
// Content of player\auth.inc
#define ALS_R_PlayerTextDraws 1
#define ALS_DO_PlayerTextDraws<%0> %0<PlayerTextDraws,i>(end:playerid)

hook function PlayerTextDraws(playerid)
{
    //...code
    return continue(playerid);
}

// Content of player\ui.inc (included after auth.inc)
hook OnPlayerConnect(playerid)
{
    call OnPlayerTextDraws(playerid);
    return Y_HOOKS_CONTINUE_RETURN_1;
}
```
Results **(error) undefined symbol "PlayerTextDraws"** on _hook function PlayerTextDraws(playerid)_ line...

**Comment by sampwide** [comment]
If you don't know to use it, then don't use it.

**Comment by tr1xy** [comment]
If you don't know how to help, don't answer σ(￣、￣〃)

**Comment by Y-Less** [comment]
You are hooking a function that doesn't exist (`PlayerTextDraws`) then calling it like a callback (`OnPlayerTextDraws`).  I don't know what you're trying to do, but this isn't the way to do anything, nor is it a bug in YSI.

**Comment by yoddachi** [comment]
funny
