### ISSUE TITLE
[YSI 5.1] warning 203 using y_foreach on default pawn compiler

### ISSUE THREAD

**Issue by NexiusTailer** [pawn-lang/YSI-Includes#398]
There is a warning when using y_foreach from YSI 5.1 (from releases section) on default pawn compiler distributed with the samp server (3.2.3664).

So let me give an extended information.

With such code:
```
#include <YSI\y_foreach>
```
and having used "foreach(new i : Player) { blah-blah-blah" in my gamemode I have such warning:
```
F:\gamemodes\test.pwn(674) : warning 203: symbol is never used: "USE@YSI_Data@y_iterate"
```

At the same time if I change it to:
```
#include <YSI\y_iterate>
```
then I'll get even errors like that:
```
F:\gamemodes\test.pwn(138) : error 017: undefined symbol "foreach"
F:\gamemodes\test.pwn(138) : error 029: invalid expression, assumed zero
F:\gamemodes\test.pwn(138) : error 017: undefined symbol "i"
F:\gamemodes\test.pwn(138) : fatal error 107: too many error messages on one line
```
but all that I have it is just:
```
public OnInfoBoxUpdate()
{
	foreach(new i : Player) // line 138
	{
		if(ShowInfoBox[i])
		{
			if(GetPVarInt(i,"InfoBox") < gettime())
			{
				PlayerTextDrawHide(i, INFO_BOX[1]);
				PlayerTextDrawHide(i, INFO_BOX[0]);
				ShowInfoBox[i] = false;
			}
		}
	}
}
```

The only way to use y_iterate without any problems is to declare it like:
```
#include <YSI_Data\y_iterate>
```
However I became curious about the other ways of including, and it seems that they should be put in order.

**Comment by Y-Less** [comment]
The warning is the best I could do:

> The only way to use y_iterate without any problems is to declare it like:
>
> #include <YSI_Data\y_iterate>

So the only way to do it correctly is to "Use YSI_Data\y_iterate".  Sadly you can't have spaces and slashes in symbol names, so I have to use:

> USE@YSI_Data@y_iterate
