### ISSUE TITLE
Compiler issues YSI 5.1

### ISSUE THREAD

**Issue by Abyss-z94** [pawn-lang/YSI-Includes#400]
Im using YSI include version 2.0 and just try to upgrade it to YSI 5.1 then got all warning like this. I think there was a problem creating a new variable or does YSI not like my gamemode or something? :(

`: warning 219: local variable "modelid" shadows a variable at a preceding level

: warning 219: local variable "index" shadows a variable at a preceding level

: warning 219: local variable "index" shadows a variable at a preceding level

: warning 219: local variable "index" shadows a variable at a preceding level

: warning 219: local variable "dist" shadows a variable at a preceding level

: warning 219: local variable "dist" shadows a variable at a preceding level

: warning 219: local variable "dist" shadows a variable at a preceding level

 warning 219: local variable "string" shadows a variable at a preceding level

: warning 219: local variable "giveplayerid" shadows a variable at a preceding level

: warning 219: local variable "weaponid" shadows a variable at a preceding level

: warning 219: local variable "slot" shadows a variable at a preceding level

: warning 219: local variable "weaponid" shadows a variable at a preceding level

: warning 219: local variable "slot" shadows a variable at a preceding level

: warning 219: local variable "weaponid" shadows a variable at a preceding level

: warning 219: local variable "slot" shadows a variable at a preceding level

: warning 219: local variable "count" shadows a variable at a preceding level

: warning 219: local variable "string" shadows a variable at a preceding level

: warning 219: local variable "text" shadows a variable at a preceding level

: warning 219: local variable "string" shadows a variable at a preceding level

: warning 219: local variable "color" shadows a variable at a preceding level

: warning 219: local variable "idx" shadows a variable at a preceding level

: warning 219: local variable "result" shadows a variable at a preceding level

: warning 219: local variable "string" shadows a variable at a preceding level

: warning 219: local variable "string" shadows a variable at a preceding level`

**Comment by Y-Less** [comment]
Those mean you have global variables with names like `string` and `color`, which are terrible global variable names because they are extremely commonly used as local variables.

**Comment by Y-Less** [comment]
Those mean you have global variables with names like `string` and `color`, which are terrible global variable names because they are extremely commonly used as local variables.

**Comment by Abyss-z94** [comment]
All of these was my local variables Y-Less, not global. It just happend while using 5.1 version you know, with my older version still work so that not about my variables on my gamemode, it about YSI new version was incompatible with gamemode using oldest version like me.

**Comment by Y-Less** [comment]
Well can you attach the file and line numbers to the warnings please?
