### ISSUE TITLE
y_inline & y_dialog string length problem

### ISSUE THREAD

**Issue by Bronzal** [pawn-lang/YSI-Includes#402]
while checking string length via `strlen`, on empty text, the length, function returns '1'.

code:
```c
inline _response(playerID, dialogID, response, listitem, string:inputtext[])
{
	#pragma unused playerID, dialogID, listitem 
	if (response)
	{
		printf("length of string : %d", strlen(inputtext));
	}
	Dialog_ShowCallback(playerid, using inline _response, DIALOG_STYLE_INPUT, "Test", "Test", "x", "o");
	return 1;
}
```
output:
![image](https://user-images.githubusercontent.com/51256560/73813240-65241800-47ad-11ea-92d2-4eec358fc0e1.png)

**Comment by Y-Less** [comment]
Yes.  That's common in a lot of places, which is why we have `isnull(inputtext)`.
