### ISSUE TITLE
[5.x] y_commands unknown command

### ISSUE THREAD

**Issue by pawnoholic** [pawn-lang/YSI-Includes#403]
Hi, 

Created a simple command in blank gamemode, I get an error when sending the command: "SERVER: Unknown command."

```
YCMD:vehicle(playerid, params[], help)
{
    new
        Float:x,
        Float:y,
        Float:z,
        Float:a
    ;
    GetPlayerPos(playerid, x, y, z);
    GetPlayerFacingAngle(playerid, a);

    printf("debug");

    CreateVehicle(strval(params), x + 3.0, y + 3.0, z, a);

    return 1;
}
```

**Comment by tr1xy** [comment]
You used any of two callbacks (Performed/Received)?

**Comment by pawnoholic** [comment]
No

**Comment by tr1xy** [comment]
@Y-Less I can confirm that YCMDs are broken, I got same result (no callbacks)!

Also, I noticed that including y_commands_tests will crash the compiler (3.10.10)

#393 

I also noticed that 5.1 from releases page is working.

I lost some edits cuz I forgot to save some edits I made to YSI (shitton of lines), press F.

https://github.com/pawn-lang/YSI-Includes/compare/v5.1...5.x

**Comment by tr1xy** [comment]
Also, I noticed that including y_commands_tests will crash the compiler (3.10.10)

**Comment by tr1xy** [comment]
#393

**Comment by Y-Less** [comment]
Fixed.
