### ISSUE TITLE
Where can I use va_strlen?

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#408]
As I do not find any use to `va_strlen(arg)`, where it is supposed to be used?
Argument is not a string so idk, integers, no?

**Comment by Y-Less** [comment]
It gets the length of a variable parameter:

```pawn
Func(...)
{
    printf("%d", va_strlen(1));
}

Func("short", "a long string");
```

Prints `13`, the length of the second string.
