### ISSUE TITLE
[5.x] Run time error 5: "Invalid memory access" 

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#409]
#377 
I don't really know is it same issue because I did not get anything (and I'm using MySQL now) in the console, but one dude got this because YSI wasn't initialised when Player connected. 
```[debug] The 1st mangled argments (e.g. `<1073741823 arguments>`) below should read `<1 arguments>`
[debug]
[debug] Run time error 5: "Invalid memory access"```
He said that it happens when INI_ParseFile is called (I guess he is using Y_INI for account database).

Any workaround?
I suggested him to create variable which is false until `OnScriptInit` is called and to block IP if variable is false OnIncomingConnection.
Idk if it worked but I'll reply once he tries it, still it's not good practice I suppose.

**Comment by tr1xy** [comment]
It didn't work, F.

**Comment by tr1xy** [comment]
#304 
Please prioritise fixing y_malloc in the future updates, cheers! (as problem is present for 2 years) 
fix is YSI_NO_HEAP_MALLOC

**Comment by Y-Less** [comment]
I did fix y_malloc...  The fix is in the thread you listed.

Also, you need to post the whole stacktrace, not just the top.
