### ISSUE TITLE
[4.x] y_text - Text buffer full!

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#413]
Hello!

So recently I've been using y_text and it appears that there is a limit of 1024 entries (not sure if that's per language or not) I've been trying this using only one language and over 1024 entries, it keeps saying that the text buffer is full in the log, if I try to manually raise the limits, the colors would randomly turn red if they don't have a default color, and game texts are actually rendered in the chat instead of being displayed on the player's screen. The same thing happens if I just keep the 1024 entries limit and play normally, but it wouldn't happen if I just remove some entries from the text files.

Any solutions?

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/YSI-Includes/blob/4.x/YSI_Players/y_text.inc#L187-L197

Sets are sections of the file, like `[properties]`, `TEXT_PER_SET` is fairly obvious.  So you can create any of those defines as you please to increase the various limits.  Note that the 64 there is AVERAGE, so one set can have more while one has less.

**Comment by ghost** [comment]
Thanks for your reply!

It appears to work fine now actually, it's been days I've been trying to find a solution for this problem. So all I had to do was add more sections to the files and load them within the script modules.

Thank you once more.
