### ISSUE TITLE
Run time error 5: "Invalid memory access"

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#418]
```
[debug] AMX backtrace:
[debug] #0 000140b8 in DumpAMX_WriteEncoded (File:file=5134872, data[]=@014239c8 "", &offset=@014239c4 -127, compact=2, c=120, size=48) at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:186
[debug] #1 00014a54 in bool:DumpAMX_WriteAMXCode (File:file=5134872, data[]=@014239c8 "", &offset=@014239c4 -127, size=48, compact=2) at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:252
[debug] #2 00014d80 in bool:DumpAMX_Write (filename[]=@00008888 "YSI_CACHE.amx") at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:282
[debug] #3 000012e4 in ScriptInit_CallOnCodeInit (bool:jit=false) at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:341
[debug] #4 00001ae0 in public YSIM_VERSION@a () <@a:> at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:575
```
@Y-Less this happend after you did y_commands fix I think

**Comment by Y-Less** [comment]
I've tried to reproduce this already and couldn't.  Do you have a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?  And what server version are you?

If you don't care about caching you can compile with:

```pawn
#define YSI_NO_MODE_CACHE
```

**Comment by tr1xy** [comment]
```
YCMD:jp(playerid, params[], help)
{
	SetPlayerSpecialAction(playerid, SPECIAL_ACTION_USEJETPACK);
	return COMMAND_OK;
}
```
I removed this and error was gone, intersting.

EDIT: This is only YCMD I have atm

**Comment by tr1xy** [comment]
Disabling caching removes the error!

**Comment by Y-Less** [comment]
Well I knew that.

**Comment by tr1xy** [comment]
Sorry, @ADRFranklin said to mention that too 👍

**Comment by Y-Less** [comment]
I tested on both Windows and Linux with:

```pawn
//#define YSI_TESTS
#define YSI_NO_HEAP_MALLOC

#include <a_samp>
#include <YSI_Players\y_groups>
#include <YSI_Coding\y_inline>
#include <YSI_Visual\y_commands>

#include "random_module.pwn"

main() {}

YCMD:jp(playerid, params[], help)
{
	SetPlayerSpecialAction(playerid, SPECIAL_ACTION_USEJETPACK);
	return COMMAND_OK;
}
```

Nothing.

**Comment by George480** [comment]
> I've tried to reproduce this already and couldn't. Do you have a MCVE? And what server version are you?

Even this sample gives the run time error 5:
```Pawn
#include <a_samp>
#include <YSI_Players\y_groups>

main() {}
```
Output:
```Pawn
 Run time error 5: "Invalid memory access"
 AMX backtrace:
 #0 000141d0 in DumpAMX_WriteEncoded (File:file=5134872, data[]=@01796850 "", &offset=@0179684c -127, compact=2, c=120, size=48) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:186
 #1 00014b6c in bool:DumpAMX_WriteAMXCode (File:file=5134872, data[]=@01796850 "", &offset=@0179684c -127, size=48, compact=2) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:252
 #2 00014e98 in bool:DumpAMX_Write (filename[]=@00009664 "YSI_CACHE.amx") at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:282
 #3 000011a4 in ScriptInit_CallOnCodeInit (bool:jit=false) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:341
 #4 000019a0 in public YSI_gGroupData@Dist () <@7:> at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:575
```

Only crashdetect (version 4.19.4) plugin was loaded. 
Version of YSI is the latest commit of YSI 5.x
SA-MP server version is 0.3.7-R2
Using samp-stdlib and pawn-stdlib includes
Compiler version 3.10.10
Windows 7 Ultimate, SP1

**Comment by tr1xy** [comment]
Oh boi, I noticed that this code won't even compile at all using default compiler (it generated 6000kb amx file and using 100% cpu):
```
#include <a_samp>
#include <YSI_Visual\y_commands>

main() {}
```
Also, errors are different If I include just y_va instead of y_commands for example:
```
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  PA
[debug]  PA
[debug] Run time error 19: "File or function is not found"
[debug]
[debug]  PA
[debug]  PA
Script[gamemodes/YSI_ERROR_DEBUG.amx]: Run time error 19: "File or function is not found"
```
Build system:
```
{
    "selector": "source.pwn", 
    "file_regex": "(.*?)\\(([0-9]*)[- 0-9]*\\)", 
    "cmd": [
        "pawncc.exe", 
        "$file", 
        "-o$file_path/$file_base_name", 
        "-;+", 
        "-(+", 
        "-d3"
    ], 
    "working_dir": "C:/Compiler"
}
```

EDIT: I even tested compiling with full default pawno.exe, same problem, won't even compile..
https://imgur.com/a/ti5yicv

EDIT 2:

 compiled it somehow, compiler output was same as above and file was 5kb large.
Some random ASCII symbols in error message again:
> [debug] Run time error 19: "File or function is not found"
> [debug]
> [debug]  <Yuñ
> [debug]  <Yuñ
> [debug] Run time error 19: "File or function is not found"
> [debug]
> [debug]  <Yuñ
> [debug]  <Yuñ
> Script[gamemodes/YSI_ERROR_DEBUG.amx]: Run time error 19: "File or function is not found"
> Number of vehicle models: 0
>

**Comment by Y-Less** [comment]
I'm not really bothered about the default compiler.  I do TRY and keep compatible, but if it doesn't work just don't use it.

**Comment by tr1xy** [comment]
I agree, had to test it anyway! 👍 

EDIT: YSI related stuff in the first case (YCMD one):
```
// YSI
#define YSI_NO_HEAP_MALLOC             (1)
#define YSI_NO_VERSION_CHECK           (1)
#define YSI_NO_OPTIMISATION_MESSAGE    (1)
#define YSI_NO_MODE_CACHE              (1)
```

**Comment by tr1xy** [comment]
I traced where the problem IS, I'll edit this message once I confirm the **EXACT** location!

@Y-Less EDIT:
This might help:
y_dumpamx.inc line 186
```
while (index < ENC_MAX) {
	data{offset++ ^ 0x03} = buffer{index++};
	if (offset == size) {
		// Write the whole cell.
		fblockwrite(file, data, size >>> 2);
		offset = 0;
	}
}
```
This will be executed once (succesful iteration) but after it starts going through the while loop second time - It'll fail on this line:
`data{offset++ ^ 0x03} = buffer{index++};`

**Comment by Y-Less** [comment]
I knew it was on that line from the first call stack, but I don't know why:

```
[debug] #0 000140b8 in DumpAMX_WriteEncoded (File:file=5134872, data[]=@014239c8 "", &offset=@014239c4 -127, compact=2, c=120, size=48) at C:\Compiler\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:186
```

The problem is that I don't get anything on that line, while you do.

However, I've just pushed some changes which MAY help.  But who knows (since I still don't know what the root cause is).

**Comment by tr1xy** [comment]
That did not fix it, I'll look into it (I'll try my best XD)

**Comment by Y-Less** [comment]
Could you add this line please and tell me the output:

```pawn
	// straggling bytes
	offset = plain_amxhdr[AMX_HDR_OFFSET_COD / 4] - dat - start;
	printf("%d %d %d", plain_amxhdr[AMX_HDR_OFFSET_COD / 4], dat, start);
```

That's the only place I can see it causing an issue.

**Comment by tr1xy** [comment]
**7880 578064 -570180**

**Comment by George480** [comment]
The run time error 5 is only given after pushing `New crash detect compatibility.`: https://github.com/pawn-lang/YSI-Includes/commit/5ac6030857c48a1c70ebb33b0dfe5bdab69a0836 and `forward OnRuntimeError.`: https://github.com/pawn-lang/YSI-Includes/commit/8fc852d1f8f7e981c7d70504c0974945d4ba657a commits. I did not receive it with previous commits.

After updating to latest commits, the output is:
```Pawn
3976 213012 -209032
```

and sample is still the one from before:
```Pawn
#include <a_samp>
#include <YSI_Players\y_groups>

main() {}
```

**Comment by tr1xy** [comment]
This line, it won't go further:
```
default: { 
	DumpAMX_WriteEncoded(file, data, offset, compact, _:opcode, size); // Run time error 5: "Invalid memory access"
	new n = DisasmGetNumOperands(ctx);
	for (new i = 0; i < n; i++) {
		//data[i + 1] = DisasmGetOperandReloc(ctx, i);
		print("7.1");
		DumpAMX_WriteEncoded(file, data, offset, compact, DisasmGetOperandReloc(ctx, i), size);
		print("7.2");
	}
	//fblockwrite(file, data, n + 1);
}
```

**Comment by Y-Less** [comment]
I KNOW WHY!  I figured it out while waiting.

I updated amx_assembly, but didn't push the changes!  So I've been using a different version to everyone else!

**Comment by Y-Less** [comment]
Try now.

**Comment by tr1xy** [comment]
I fucking wanted to ask on the beginning for your amx version... -_-
Thank you!
(I even went 15 commits back in the amx xD)

**Comment by Y-Less** [comment]
Going backwards wouldn't have helped, since I had a private version (but had you asked, I'd have probably realised instantly).  The annoying thing is an earlier version of the code didn't use the value from amx_assembly because I knew it was wrong, but clearly I lost that in the changes.  This was the root issue:

https://github.com/Zeex/amx_assembly/commit/5f1e235cbdfa206283d9e9f74d922ba28d741a89

That value was wrong, and I was using it in the code.  But I'm now not using it directly so you don't need to update both:

https://github.com/pawn-lang/YSI-Includes/commit/3e000136514d5342be009e560484ee0c54a44b98

**Comment by Y-Less** [comment]
Thank you so much both of you - @tr1xy and @George480 for helping me get to the bottom of this!

**Comment by Y-Less** [comment]
Plus, while trying to solve this issue I found another bug in the code, but it was far more subtle so wouldn't have crashed anything.

**Comment by Y-Less** [comment]
AND found a bug in my new PR for crashdetect.  So all in all, three bugs at once!
