### ISSUE TITLE
y_iterate enhancement

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#419]
Enhancement: **Iter_Skip(Iterator:Name<>, skip);**
**Iterator:Name<>** We all know what this is 😄 
**skip** How many **valid** iterator values to skip.

Example function: using **Iter_Skip**:
```
new String: sList = str_new_static("");
foreach(new spawn_id : Spawn)
{
	str_append(sList, str_format(""SERVER"> "WHITE"%s\n", SpawnName[spawn_id]));
}

if (spawnDialog[E_DIALOG_RESPONSE_Response])
{
	if (spawnDialog[E_DIALOG_RESPONSE_Response])
	{
		PlayerSpawn[playerid] = Iter_Skip(Spawn, spawnDialog[E_DIALOG_RESPONSE_Listitem]);
	}
}
```

EDIT: Y_Less, please accept my friend request (Discord, .rosezz), thank you!

Plase use 👍  and 👎 !!!

**Comment by Y-Less** [comment]
```pawn
Iter_Index(iter, index);
```

Gets the nth valid value.
