### ISSUE TITLE
More meaningful inline function names

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#422]
Crashdetect still reports just
`[debug] #4 0006048c in public FJ37DH3JG_MYSQL_INTERNAL`
for crashes in inline functions, can we do anything with that nowadays to improve error message to include inline function name?

**Comment by Y-Less** [comment]
Where did you get that?

**Comment by Misiur** [comment]
Each time there's a crash inside inline function

**Comment by Y-Less** [comment]
OK, but that's a public.  That's nothing to do with the inlines.

**Comment by Misiur** [comment]
It's standard way MySQL handles inline callbacks, any ideas how to improve that?
https://github.com/maddinat0r/samp-mysql-yinline-include/blob/master/a_mysql_yinline.inc#L617

**Comment by Y-Less** [comment]
Well you don't need that in 5.x any more.
