### ISSUE TITLE
y_text get entry

### ISSUE THREAD

**Issue by JoaquinZc** [pawn-lang/YSI-Includes#423]
I would like to know how to get an entry and save it to a string. I try to use Text_Format, but it ejects "Text Not Found".

I am trying to make Text3DLabels with different languages for users. I am also not aware if that is already integrated into the library, I saw some things in the code, but none are conclusive, I do not know if I overlook something.

Help me pls.

**Comment by Misiur** [comment]
Available with https://github.com/Misiur/YSI-Includes/tree/feature/formatted but only for 4.x
