### ISSUE TITLE
YSI_Data\y_iterate

### ISSUE THREAD

**Issue by qSorin** [pawn-lang/YSI-Includes#424]
Hello, i found a problem with iterate!
ok, i created a 3 commands (/spawncar , /vehicles and /despawncars) with iterate.
only use /despawncars, my server it's crashed.

Code here: https://pastebin.com/dLD8S2pc

**Comment by Misiur** [comment]
Install crashdetect and show what it reported

**Comment by Misiur** [comment]
But the error is obvious, use Iter_SafeRemove in the loop to avoid the crash

**Comment by qSorin** [comment]
Problem solved, Thanks Misiur, i used Iter_SafeRemove thanks you!! <3
