### ISSUE TITLE
y_timers

### ISSUE THREAD

**Issue by qSorin** [pawn-lang/YSI-Includes#425]
Hello, a foud a problem in my code or in ysi_timer!!

My timer it's not working..

public OnPlayerEnterVehicle(playerid, vehicleid, ispassenger) {
	if(PlayerInfo[playerid][user_DriveLic] == false) return SendClientMessage(playerid, COLOR_LIGHTBLUE, "Eroare: {FFFFFF}Nu ai licenta de condus");

	if(GetPlayerState(playerid) == PLAYER_STATE_DRIVER) {
		PlayerTextDrawShow(playerid, Speedometre[playerid][0]);
		PlayerTextDrawShow(playerid, Speedometre[playerid][1]);
		defer Speed(playerid);
	}
	return true;
}

and speed timer: https://pastebin.com/uD3SXB60

**Comment by Y-Less** [comment]
Not working how?  What does it do, and what is it meant to do?

**Comment by qSorin** [comment]
for a player enter vehicle and player is a vehicle driver for a show a speedometre

**Comment by Y-Less** [comment]
And what actually happens?  Are you sure the problem is y_timers, not just a mistake in your code?

**Comment by qSorin** [comment]
timer it's not working, don't play!

**Comment by ui-bin** [comment]
I've experience this error.. 
I already testing it using the following code:
```pawn
ptask OnAntiCheatUpdate[AC_TIMER_DETECTION](playerid) {
     print("This can be called every sec");
     return 1;
}
```

But server didn't show my print 😕 

EDIT: nvm, seems like  i forgot to load/set AC_TIMER_DETECTION value :\

**Comment by qSorin** [comment]
I'am not used ptask, and timer ex: timer gg[1000](playerid) {}

**Comment by George480** [comment]
First of all, the state of player will never be `driver` in `OnPlayerEnterVehicle` because the player is NOT in vehicle yet. Use `OnPlayerStateChange` callback instead.

Second of all, this works:
```Pawn
timer Speed[1000](playerid)
{
    printf("Speed(%d)", playerid);
}

CMD:test(playerid, params[])
{
    defer Speed(playerid);
    return 1;
}
```
`defer` calls the timer once. For a repeating timer, you would have to use `repeat` or `REPEAT__`  keywords.

**Comment by qSorin** [comment]
nope, not working..

public OnPlayerStateChange(playerid, newstate, oldstate) {
	if(PlayerInfo[playerid][user_DriveLic] == false) return SendClientMessage(playerid, COLOR_LIGHTBLUE, "Eroare: {FFFFFF}Nu ai licenta de condus");

	PlayerTextDrawShow(playerid, Speedometre[playerid][0]);
	PlayerTextDrawShow(playerid, Speedometre[playerid][1]);
	repeat Speed(playerid);		
	
	return true;
}

i put printf in Speed timer, and nothing in console..

**Comment by George480** [comment]
The problem is in your code. Test this in an empty gamemode to confirm:
```Pawn
#include <a_samp>

#define YSI_NO_HEAP_MALLOC
#define YSI_NO_MODE_CACHE
#define YSI_NO_CACHE_MESSAGE
#define YSI_NO_OPTIMISATION_MESSAGE
#define YSI_NO_VERSION_CHECK

#include <YSI_Coding\y_timers>
#include <YSI_Coding\y_va>

#include <zcmd>

static
	Timer: gTimer_Speed[MAX_PLAYERS];
	
main() {}

timer Speed[1000](playerid)
{
    va_SendClientMessage(playerid, -1, "Speed(%d)", playerid);
}

CMD:repeat(playerid, params[])
{
    gTimer_Speed[playerid] = repeat Speed(playerid);
    
    SendClientMessage(playerid, -1, "command /repeat");
    return 1;
}

CMD:stop(playerid, params[])
{
	stop gTimer_Speed[playerid];
	
	SendClientMessage(playerid, -1, "command /stop");
	return 1;
}
```

Output of mine:
```Pawn
[21:06:46] command /repeat

[21:06:47] Speed(0)

[21:06:48] Speed(0)

[21:06:49] Speed(0)

[21:06:50] Speed(0)

[21:06:52] Speed(0)

[21:06:52] command /stop
```

**Comment by qSorin** [comment]
not working!

Images!!
1.https://prnt.sc/rwau8c
2.https://prnt.sc/rwaukd
3.https://prnt.sc/rwauxi
4.https://prnt.sc/rwavp3

Console output: https://prnt.sc/rwawad

**Comment by George480** [comment]
As I said, try the code I posted in an empty gamemode to confirm if it really works or not. Without any modification or adding the code in existing script.

**Comment by qSorin** [comment]
Problem is solved,. Thanks you all!!
