### ISSUE TITLE
Update 5.x

### ISSUE THREAD

**Issue by JoaquinZc** [pawn-lang/YSI-Includes#428]
`y_text_impl.inc:1193 (error) undefined symbol "YSI_g_sReturnText"`

I was reviewing the code, and it certainly has changed a lot from 4.0.1, and YSI_g_sReturnText is nowhere to be found. What I do?

**Comment by tr1xy** [comment]
Please close this, there is like 5+ issues about y_text being broken in 5.x
Please explore the issues page before opening one :)
(y_text is broken in 5.x and It **won't** be fixed soon)\

btw you're welcome to fix it and open PR !
