### ISSUE TITLE
YSI y_iterate - missing PlayerText: (per-player textdraws) tag support

### ISSUE THREAD

**Issue by Jedrzej94** [pawn-lang/YSI-Includes#438]
Please provide changes for upcoming YSI branch in files:

- https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Core/y_core/y_globaltags.inc#L84-L88

- https://github.com/Y-Less/indirection/blob/b1065f61e6598c7e77bd26620c6851a94fa476e0/indirection.inc#L82-L84

Add: 

- PlayerText:

tag

---
I don't want to clone the repo and create pull request. Easy change, can be done via issue.

Thanks

**Comment by Y-Less** [comment]
That's exactly what `CUSTOM_TAG_TYPES` is for.  Also, editing a file automatically clones it.
