### ISSUE TITLE
YSI Warning: y_malloc, CallLocalFunction, memory corruption.

### ISSUE THREAD

**Issue by Crayder** [pawn-lang/YSI-Includes#44]
I finally got T-Studio compiled based on Y-Less's latest comment on the hook replacements problem, but I get the following error in the console:

```
*** YSI Warning: y_malloc set up via "CallLocalFunction", memory corruption is a remote possibility
```

**Comment by Y-Less** [comment]
That's not a bug - it does exactly what it is supposed to.

**Comment by Crayder** [comment]
So... I should ignore the error? I wouldn't want to release a script that has this error every time the script is loaded, I'm sure people would be concerned. 

Also, I didn't say it was a bug. I just don't know what is causing it or how to fix it. I'm guessing it is something to do with hooks, because it only happened after I updated. 

Off-topic: TStudio doesn't get along with YSI4, the new streamer, and the new crashdetect. Before those though, I'd like to get YSI4 working with it.

**Comment by Y-Less** [comment]
You posted a github issue for it - that IS saying it is a bug!

**Comment by Crayder** [comment]
Technically an issue on github could be any of the following: bug, duplicate, enhancement, invalid, question, or wontfix. I guess I should've posted this as a question, so...

How do I fix this error and what is causing it?

**Comment by samphunter** [comment]
As I understand this, this is probably caused by ALS hooks/wrong include order.

**Comment by Y-Less** [comment]
Yes, but the "remote possibility" wording is important - it only happens if you use "malloc" in "OnGameModeInit" after y_malloc is set up and it is set up via "CallLocalFunction", then you use that allocated memory later.  Any other usage is fine.

**Comment by Crayder** [comment]
By 'ANY', you mean a filterscript would be fine? I only get this warning with Texture Studio (which is all in a filterscript, bare gamemode). 

@samphunter I remember reading that somewhere too, however, I've tried so many different logical orders but none have sufficed.

**Comment by Y-Less** [comment]
I should have said "OnScriptInit".

**Comment by Crayder** [comment]
I won't beg you to, but can you look at Pottus/Texture-Studio and tell me if it's actually going to be a problem; and if so, how to fix it?

**Comment by Y-Less** [comment]
Probably good.

**Comment by Crayder** [comment]
I figured that, I never had any problems with it (at least that I know of).
