### ISSUE TITLE
Iter_SafeRemove

### ISSUE THREAD

**Issue by qSorin** [pawn-lang/YSI-Includes#440]
Hello guys, i have a problem with Iter_SafeRemove or Iter_Remove

function DestroyVehicleEx(vehicleid) {
	Iter_SafeRemove(TV_SpawnedID, vehicleid,vehicleid);
	VehicleOccupied[vehicleid] = 0;
	DestroyVehicle(vehicleid);
	return true;
}
I have this function for destory a vehicle.
and when the function is called the it's showed a warning in console

![image](https://user-images.githubusercontent.com/63189561/80616626-cfb1c080-8a49-11ea-9806-bc25efa0611f.png)

i try with Iter_Remove and server it's crashed.

here is a command when called the DestroyVehicle
![image](https://user-images.githubusercontent.com/63189561/80616770-f96ae780-8a49-11ea-9660-e8777584f595.png)

sorry for my bad english !!

**Comment by Y-Less** [comment]
You would need to pass `vehicleid` by reference.  Also `Iter_SafeRemove` modifies the variable, so after the call to it it is no longer valid, meaning all the other function and array calls are wrong.  They should go first.
