### ISSUE TITLE
Inline funcs for pawn-requests

### ISSUE THREAD

**Issue by pawnoholic** [pawn-lang/YSI-Includes#445]
Hi everyone, sorry for my bad English.

I would like to hear your opinion.
I have been using rest api in my projects for a long time and I really missed inline functions.

```
#if defined _inc_api_inline
    #undef _inc_api_inline
#endif

#if defined _api_inline_included
    #endinput
#endif
#define _api_inline_included

#if !defined MAX_REQUESTS
    #define MAX_REQUESTS (128)
#endif

#include <YSI_Core\y_als>
#include <YSI_Coding\y_va>
#include <YSI_Coding\y_inline>
#include <YSI_Coding\y_hooks>

#define ALS_DO_GetRequestData<%0> %0<GetRequestData,iisi>(tag:Request:id,tag:E_HTTP_STATUS:status,string:data,end:dataLen)

static
        Func:RequestCallback[MAX_REQUESTS]<iisi>;

hook OnGetRequestData(Request:id, E_HTTP_STATUS:status, data[], dataLen)
{
    new
	    Func:callback<iisi> = RequestCallback[_:id];

    RequestCallback[_:id] = Func:0<iisi>;

    @.callback(id, status, data, dataLen);

    Indirect_Release(callback);

    return Y_HOOKS_CONTINUE_RETURN_1;
}

stock Request:RequestInline(RequestsClient:id, const path[], E_HTTP_METHOD:method, Func:callback<iisi>, body[] = "", Headers:headers = Headers:-1)
{
    new 
        Request:ret = Request(id, path, method, "OnGetRequestData", body, headers);

    Indirect_Claim(callback);

    RequestCallback[_:ret] = callback;

    return ret;
}
```

I implemented them in my project, do you think it is possible to make them better and should I add them to the YSI\y_inline library?

**Comment by Y-Less** [comment]
Nope, that looks about as good as you can get without being able to pass arbitrary parameters to request callbacks.  The `ALS` line is superfluous, and it doesn't actually need to use `hook` instead of `public` (but no harm there).  I guess it could be added to y_inline itself since if you don't call the function you don't need to worry about the dependencies.

**Comment by pawnoholic** [comment]
I finished working on it and added PR #446 

It may also be worth adding a check for the maximum size of the array, so as not to get a runtime error due to array of bounds.

Example:
```
if (IsValidRequest(ret) && ret < Request:MAX_Y_REQUESTS)
{
    // etc...
}
```
