### ISSUE TITLE
(y_dialog) Arbitrary Arguments

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/YSI-Includes#451]
Hello, can we somehow use arbitrary arguments with y_dialog?

Probably using y_va just idk which function :)

Sorry for spamming the Issues page but idk where else to post my questions... 👎

**Comment by tr1xy** [comment]
@Y-Less 🤙

**Comment by Y-Less** [comment]
What do you mean "arbitrary arguments"?

**Comment by tr1xy** [comment]
> What do you mean "arbitrary arguments"?

Like easyDialog's string formatting

`Dialog_ShowCallback(id, using inline UwU, style, title, "%s", b1, b2, PlayerName[playerid])`

@Y-Less

**Comment by Y-Less** [comment]
Generally just `format`.  Wouldn't be too hard to add in though.

**Comment by tr1xy** [comment]
I think that many'd switch to y_dialog if this  was supported UwU

Also, I'd want to ask if it is possible with EMIT magic to use same string size that was passed

For example **MySQL_TQueryInline** is great but it always uses **2048** which is a little problem I think

Enhancement label? No? Pls?

**Comment by Y-Less** [comment]
But you don't pass a string nor a string size.  At that point you're just specifying all the parameters of `format` but not bothering to call it.  Jumping through way more hoops than you would just to call `format`.  It does a job, one job, it doesn't need to be combined with other jobs.

**Comment by Y-Less** [comment]
But you don't pass a string nor a string size.  At that point you're just specifying all the parameters of `format` but not bothering to call it.  Jumping through way more hoops than you would just to call `format`.  It does a job, one job, it doesn't need to be combined with other jobs.
