### ISSUE TITLE
Compatibility with PreviewModelDialog.inc

### ISSUE THREAD

**Issue by PatrickGTR** [pawn-lang/YSI-Includes#453]
https://forum.sa-mp.com/showthread.php?t=570213

I've been playing around with the include and I can't seem to figure out what causes the incompatibility.

Things I've taken into account
- ShowPlayerDialog hook.
- Dialog ID.
- Include order (PreviewModel first y_dialog second).

I remember using both of them in previous version of YSI but recently tried to plug it again with the latest YSI version and there are issue.

Things I've tried
- Converted the whole hooking to use y_hooks ( game mode loaded but dialog text draw aren't showing up. dialog id/list item seem to be messed up.
- Const corrected arguments.

Without changing a thing, the game mode won't even load up, an error prompts 
```c
[debug] Run time error 19: "File or function is not found"
[debug]  Prev_ShowPlayerDialog
[debug] Run time error 19: "File or function is not found"
[debug]  Prev_ShowPlayerDialog
Script[gamemodes/main.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0```

**Comment by Y-Less** [comment]
Change this line:

```pawn
#define ShowPlayerDialog Prev_ShowPlayerDialog
```

To:

```pawn
#define ShowPlayerDialog( Prev_ShowPlayerDialog(
```

**Comment by PatrickGTR** [comment]
Okay an improvement, what's the reasoning behind this fix. I am curios.

ShowPlayerDialog seems to work fine, shows the ``DIALOG_STYLE_PREVIEW_MODEL`` fine

but when I use Dialog_ShowCallback, doesn't seem to show the ``DIALOG_STYLE_PREVIEW_MODEL`` but shows some random dialog id.

Confirmed, it shows the last shown dialogid

**Comment by PatrickGTR** [comment]
I remember it working fine with old version of YSI but I guess the new code changes on how y_dialog functions.

**Comment by Y-Less** [comment]
The change means the replacement doesn't match here:

```pawn
native Something() = ExistingNative;
```

ALS defines will replace the second half, adding the `(` stops that so YSI can rename the original function not the named one (and thus make it const-correct).

**Comment by Y-Less** [comment]
I'll check model previews, TBH I'm not sure I ever tested them, even with just YSI.

**Comment by PatrickGTR** [comment]
This could be the commit https://github.com/pawn-lang/YSI-Includes/commit/d35c57efb0f3ac90cdf1dab48465a151fec293d1 that broke the compatibility. Let me know if I can help testing.

**Comment by PatrickGTR** [comment]
any news

**Comment by Y-Less** [comment]
OK I think this is the problem:

```pawn
native Dialog_ShowPlayerNative(playerid, dialogid, style, const caption[], const info[], const button1[], const button2[]) = ShowPlayerDialog;
```

That declares a new const-correct version of the `ShowPlayerDialog` native for y_dialogs to call, but that bypasses all hooks such as those in model preview.  I've added a check to see if `_ALS_ShowPlayerDialog` already exists, and if so just leave const-correctness to that hook instead.

**Comment by PatrickGTR** [comment]
perfect, solved.
