### ISSUE TITLE
y_malloc\y_malloc_entry.inc(115) :

### ISSUE THREAD

**Issue by ognjenlaaza** [pawn-lang/YSI-Includes#454]
y_malloc\y_malloc_entry.inc(115) : error 076: syntax error in the expression, or invalid function call

**Comment by Y-Less** [comment]
How did you include it?  Are you on the latest version?  y_malloc includes all its dependencies required, including y_prehooks.

**Comment by ognjenlaaza** [comment]
I didn't include y_malloc
#include					< a_samp 		 >
#include 					< SKY 			 >
#include 					< weapon-config  >
#include					< foreach 		 >
#include					< streamer 		 >
#include <YSI_Storage\y_ini>
#include <YSI_Coding\y_timers>
#include <YSI_Visual\y_commands>
#include					< sscanf2 		 >
#include					< eSelection	 >
#include					< mSelection	 >
#include					< a_pause 		 >
#include					< mapandreas	 >
#include					< crashdetect	 >
#include					< ProgressBar    >
#include                    < GhostAC        >
#include 					< fly            >
#include                    < fuckcleo       >
#include                    < altchat        >

**Comment by Y-Less** [comment]
That's a lot of includes.  Do you know which ones trigger the error (i.e does removing one stop it)?  Are you sure you're on the latest git version, not release?

**Comment by ognjenlaaza** [comment]
https://github.com/pawn-lang/YSI-Includes/releases i downloaded ysi from here

**Comment by ognjenlaaza** [comment]
CHAIN_HOOK(Malloc)
is error

**Comment by Y-Less** [comment]
I know.  I've determined the problem is weapon-config.  It recently added prehooks and messed them up.  Include it last and this should go away until @ADRFranklin fixes it!

**Comment by ognjenlaaza** [comment]
Thank you . :)

**Comment by ognjenlaaza** [comment]
YSI\y_hooks.inc(80) : warning 237: user warning: Please use `#include <YSI_Coding\y_hooks>` 
but there is already that include

**Comment by ADRFranklin** [comment]
@Y-Less excuse me sir? I messed up? I followed your exact code lol
as well as double checked the y_prehooks include to make sure everything was good.

https://github.com/oscar-broman/samp-weapon-config/issues/61#issuecomment-268567805

I even asked you in discord to check it, and you said it was fine.

**Comment by ognjenlaaza** [comment]
Thank you both for improving samp!, i'm from Bosnia And Herzegovina.
U are really great ! Thanks for improving SAMP everyday.
