### ISSUE TITLE
YSI_Coding\y_hooks problems

### ISSUE THREAD

**Issue by f0Re3t** [pawn-lang/YSI-Includes#455]
![image](https://user-images.githubusercontent.com/31089900/84573654-8a074800-adaa-11ea-81cc-111cb38cef49.png)
How can I shorten the names of hooked functions?

**Comment by omcho420** [comment]
All are under here

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_hooks/y_hooks_impl.inc#L99

// example
hook OnPlayerEnterCP(...)

**Comment by f0Re3t** [comment]
> All are under here
> 
> https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_hooks/y_hooks_impl.inc#L99
> 
> // example
> hook OnPlayerEnterCP(...)

I tried, but it doesn't work with the hook function
