### ISSUE TITLE
y_groups foreach

### ISSUE THREAD

**Issue by ASGOOD1** [pawn-lang/YSI-Includes#458]
I did a test using the model.
new Group:a = Group_Create("group");

	Group_SetPlayer(a, 5, true);
	Group_SetPlayer(a, 7, true);
	Group_SetPlayer(a, 89, true);
	Group_SetPlayer(a, 50, true);

	foreach (new playerid : Group(a))
	{
		printf("%d", playerid);
	}
at line foreach(new playerid : Group(a)) i get "insufficient memory" error

**Comment by tr1xy** [comment]
@Y-Less Check this one 👍🏿

**Comment by Y-Less** [comment]
Hmm, thank you.  I'll check this.

**Comment by tr1xy** [comment]
> Hmm, thank you.  I'll check this.

Sorry for mentioning tho, I'm just going over each and "removing" duplicates as there are many, especially for y_text :')
