### ISSUE TITLE
y-iterate ( Iter_SafeRemove )

### ISSUE THREAD

**Issue by ASGOOD1** [pawn-lang/YSI-Includes#464]
foreach(new i : PlayerVehicles[playerid]){
		if(IsValidVehicle(cInfo[i][cSpawn])) DestroyVehicle(cInfo[i][cSpawn]);
		Iter_SafeRemove(TotalPlayerVehicles, i, i);
	    memset(cInfo[i], sizeof(cInfo[]), 0);
		cInfo[i][cSpawn] = INVALID_VEHICLE_ID;
	}
	Iter_Clear(PlayerVehicles[playerid]);
The numbers from iterator TotalPlayerVehicles doesn`t disappear.
Iter_safeRemove doesn`t work it doesn`t work for PlayerVehicles[playerid] either, i tested it

**Comment by ASGOOD1** [comment]
solved

**Comment by ASGOOD1** [comment]
The problem is persisting 
foreach(new i : PlayerVehicles[playerid]) {
		if(IsValidVehicle(cInfo[i][cSpawn]))DestroyVehicle(cInfo[i][cSpawn]);
		memset(cInfo[i], sizeof cInfo[], 0);
		cInfo[i][cSpawn] = INVALID_VEHICLE_ID;
		Iter_SafeRemove(PlayerVehicles[playerid],i,i);
	} 
	foreach(new i : TotalPlayerVehicles)
		if(YHash(cInfo[i][cOwner]) == YHash(getName(playerid))) 
			Iter_SafeRemove(TotalPlayerVehicles, i, i);

**Comment by tr1xy** [comment]
https://fiddle.sa-mp.dev/UniqueCoplanarKingbird

It should work if you're using latest YSI version (YSI5)...

**Comment by Y-Less** [comment]
Because you're using `i` after calling `Iter_SafeRemove`, when it is no longer valid.  Use a different output variable or move the `memset` before it.
