### ISSUE TITLE
Using y_properties

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#47]
Hello. 
Today, i was think, than I can use one from the huge include in library. First, what was interested me, was **y_properties**. But, when i stared with basic `CreateBank`, its started list of errors. Many i was solved by loading `#include <YSI\y_utils>`, but is still not enough. Must I load some more specific includes, or some of that undefined symbols i must declare myself, like `PLAYER_BIT_ARRAY`?

**Comment by Misiur** [comment]
y_properties needs to be fully ported. See https://github.com/Misiur/YSI-Includes/issues/48
