### ISSUE TITLE
AMX file much bigger than expected

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#473]
I tried to make a modular base script with YSI, it turns out my AMX file was ~11MB even using these configuration

```
//configuration
#define YSI_NO_MODE_CACHE
#define YSI_YES_HEAP_MALLOC

//YSI Project
#include <YSI_Coding\y_timers>
#include <YSI_Data\y_iterate>
#include <YSI_Visual\y_commands>
```

But without YSI i got ~21KB

Any idea how to solve this problem? or just leave it and pretending it's fine? hmm.

**Comment by Y-Less** [comment]
There are loads of things you can do.  Pretty much every library has config options to control array sizes.  However, 11mb IS fine - my watch has more RAM than that.

**Comment by ghost** [comment]
Hmmmm okay.

**Comment by Misiur** [comment]
I know the pain of continous AMX upload on a slow network, how it got so large without heap space allocated?

**Comment by ghost** [comment]
I dont know, since YSI 5.x my amx file was bigger than using YSI 4.x

That's why i still sticking to YSI 4.x without using sampctl.

**Comment by Y-Less** [comment]
The files also do compress very well.
