### ISSUE TITLE
Using states shows 3 warnings (219) in the YSI library

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#475]
I added two fairly simple states (normal state and a debug state) to be able to turn debug mode on or off in a production environment (it's not on by default when compiled in production environment).
Included entry() functions aswell (for the two states and an undefined state) to send a message to the log stating the new state.
You can imagine it looks like this:
**init.inc** (first file calling hook OnGameModeInit())
```
hook OnGameModeInit()
{
#if ENV < 2 //2 and 3 are production, 0 and 1 debug (output is different per environment. Not relevant for this issue)
    state kstate:debug;
#else
    state kstate:normal;
#endif
}

entry() <kstate:debug>
{
    print(E_NOTICE"Server entered debug state");
}

entry() <kstate:normal>
{
    print(E_NOTICE"Server entered normal state");
}

entry() <>
{
    print(E_WARNING"Server entered invalid state"); //Would probably never show since entering an invalid state would trigger runtime errors due to no functions defined for that state
}
```

**(...)\debug.inc**
```
#define __dprint_PP(%0,%1) __dprint(%0, __file, __line, %1)
#define dprint(%0) __dprint_PP(%0, __file, __line)
__dprint(const format[], const file[], line, va_args<>) <kstate:debug>
{
	static debug_string[500];
	va_format(debug_string, sizeof(debug_string), E_DEBUG"%s", format);
	va_format(debug_string, sizeof(debug_string), debug_string, va_start<3>);
	va_format(debug_string, sizeof(debug_string), "%s --%s:%d", debug_string, file, line);
	print(debug_string);
}

__dprint(const format[], const file[], line, va_args<>) <kstate:normal>
{
	#pragma unused format, file, line
}
```

Warnings:

```
(...)\YSI_Coding\y_hooks\y_hooks_impl.inc(284) : warning 219: local variable "entry" shadows a variable at a preceding level
(...)\YSI_Coding\y_hooks\y_hooks_impl.inc(1179) : warning 219: local variable "entry" shadows a variable at a preceding level
(...)\YSI_Coding\y_timers\y_timers_impl.inc(87) : warning 219: local variable "entry" shadows a variable at a preceding level
```

Any ideas? For now I'm disabling warning 219 before including the YSI includes and enabling it afterwards.

**Comment by Y-Less** [comment]
Use `_DEBUG 0`, YSI already has a runtime debug mode.

How to fix this more generally, I have no idea.

**Comment by Y-Less** [comment]
Oh, wait, they're just local variables, not state entry functions. That's easy to fix - just rename the variables in YSI (and make a PR please - I'm absolutely doing hacktoberfest).

**Comment by ghost** [comment]
They are indeed :P Fixing this "issue" for just myself would be very selfish, hence this reported issue.
PR coming up soon.

**Comment by Y-Less** [comment]
I did a search and found a few more locals called `entry`.  Unfortunately most of them are returns from functions call `AMX_GetSomethingEntry`, which makes `entry` a very good name.  Maybe `publicTableEntry`.

**Comment by ghost** [comment]
Good you said that. I was about to make a PR:

Didn't know a more appropriate name for `entry` so changed them to an unfortunate `entry2`

It shall be done.

**Comment by Y-Less** [comment]
There are also a few in y_races for which `entryCost` would be better.

**Comment by ghost** [comment]
Seems I can't link issues to the PR. Should be fixed (in two other files aswell) #476

**Comment by Y-Less** [comment]
There are some in y_amx as well.

**Comment by ghost** [comment]
This should cover it then :) (names are less appropriate here and there. All `entry` variables in y_amx changed to `entrySearch`)

**Comment by Y-Less** [comment]
`tableEntry` would be better.

**Comment by ghost** [comment]
The wish of the YSI library is my command.
Everything should really be covered now.

**Comment by Y-Less** [comment]
Brilliant.  Thanks.
