### ISSUE TITLE
Redefination Warning

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#477]
It gives us this warning;

`YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\..\..\indirection\indirection.inc(84) : warning 201: redefinition of constant/macro (symbol "GLOBAL_TAG_TYPES")`

**Comment by Y-Less** [comment]
Then you have the wrong version.

**Comment by MaxAndolini** [comment]
> Then you have the wrong version.

I upgraded latest now (not released), and it gives warning now. Try just.

**Comment by Y-Less** [comment]
https://github.com/Y-Less/indirection/blob/27d88aed1bfc260445899c708bc1f0555ab763f3/indirection.inc#L81-L85
https://github.com/pawn-lang/YSI-Includes/blob/7adbca0a275834a6693148c18baad11c528ce535/YSI_Core/y_core/y_globaltags.inc#L84-L88

**Comment by MaxAndolini** [comment]
> https://github.com/Y-Less/indirection/blob/27d88aed1bfc260445899c708bc1f0555ab763f3/indirection.inc#L81-L85
> https://github.com/pawn-lang/YSI-Includes/blob/7adbca0a275834a6693148c18baad11c528ce535/YSI_Core/y_core/y_globaltags.inc#L84-L88

Yea, that's why it gives this warning. You need to update that indirection.

**Comment by Y-Less** [comment]
That indirection, which is identical?

Code from indirection:

```pawn
#if defined CUSTOM_TAG_TYPES
	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D,CUSTOM_TAG_TYPES}
#else
	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D}
#endif
```

Code from YSI:

```pawn
#if defined CUSTOM_TAG_TYPES 
	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D,CUSTOM_TAG_TYPES} 
#else 
	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D} 
#endif 
```

They are identical.

**Comment by MaxAndolini** [comment]
> That indirection, which is identical?
> 
> Code from indirection:
> 
> ```pawn
> #if defined CUSTOM_TAG_TYPES
> 	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D,CUSTOM_TAG_TYPES}
> #else
> 	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D}
> #endif
> ```
> 
> Code from YSI:
> 
> ```pawn
> #if defined CUSTOM_TAG_TYPES 
> 	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D,CUSTOM_TAG_TYPES} 
> #else 
> 	#define GLOBAL_TAG_TYPES {_,Bit,Text,Group,File,Float,Text3D} 
> #endif 
> ```
> 
> They are identical.

Because they are the same, indirection tries to introduce it twice and gives a warning. Just delete one of them and update.

**Comment by Y-Less** [comment]
That's not how the compiler works.  If there are two identical defines it doesn't give a redefinition warning.  You only need to check when they're different.

**Comment by Y-Less** [comment]
If you'd like, I can try find an archived version of my 7 chapter writeup of exactly how the pre-processor works so you can read all about these details.

**Comment by MaxAndolini** [comment]
> If you'd like, I can try find an archived version of my 7 chapter writeup of exactly how the pre-processor works so you can read all about these details.

I just told the warning about YSI latest version. I am using Zeex compiler lastest release.

**Comment by Y-Less** [comment]
Check your includes, because one of them is wrong.  Or clear the cache and re-ensure.
