### ISSUE TITLE
YSI_Cache (sscanf error: System not initialised)

### ISSUE THREAD

**Issue by MatheusAgL** [pawn-lang/YSI-Includes#484]
I have a problem starting the server.

My plugins: crashdetect.so sscanf.so streamer.so pawncmd.so mysql.so log-core.so mapandreas.so

Server Plugins
--------------
 Loading plugin: crashdetect.so
  CrashDetect plugin 4.20
  Loaded.
 Loading plugin: sscanf.so

 ===============================

      sscanf plugin loaded.

         Version:  2.8.3

  (c) 2018 Alex "Y_Less" Cole

 ===============================

  Loaded.
 Loading plugin: streamer.so

*** Streamer Plugin v2.9.4 by Incognito loaded ***

  Loaded.
 Loading plugin: pawncmd.so
[Pawn.CMD] plugin v3.3.3 by urShadow loaded
  Loaded.
 Loading plugin: mysql.so
 >> plugin.mysql: R41-4 successfully loaded.
  Loaded.
 Loading plugin: log-core.so
  Plugin does not conform to architecture.
  Failed.
 Loading plugin: mapandreas.so
  Loaded.
 Loaded 6 plugins.

Ban list
--------
 Loaded: samp.ban

Started server on port: 7777, with maxplayers: 50 lanmode is OFF.

Filterscripts
---------------
  Loaded 0 filterscripts.

  Filterscript '../scriptfiles/callbackfix.amx' loaded.

 ==========================================
 |                                        |
 |  File loaded from YSI code cache.      |
 |                                        |
 | You can disable this message with:     |
 |                                        |
 |   #define YSI_NO_CACHE_MESSAGE         |
 |                                        |
 ==========================================

[debug] Long callback execution detected (hang or performance issue)
[debug] AMX backtrace:
[debug] #0 000983fc in ?? (20796476) in YSI_CACHE.amx
[debug] #1 000cf760 in ?? () in YSI_CACHE.amx
[debug] #2 000312b8 in public ScriptInit_OnGameModeInit () in YSI_CACHE.amx
[debug] #3 0001d2b4 in public SSCANF_OnGameModeInit () in YSI_CACHE.amx
[debug] #4 00015e9c in public FIXES_OnGameModeInit () in YSI_CACHE.amx
[debug] #5 000091cc in public OnGameModeInit () in YSI_CACHE.amx
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.
sscanf error: System not initialised.

--------------------------------------
 Anticheat Nex-AC carregado!
 Anticheat vers▒o: 1.9.53
 Autor: Nexius (PT-BR by NicK_)
--------------------------------------

**Comment by Y-Less** [comment]
Upgrade sscanf.

**Comment by MatheusAgL** [comment]
sscanf plugin loaded.

     Version:  2.8.3

I am using the most updated version.

**Comment by Y-Less** [comment]
The latest version is 2.10.2

**Comment by MatheusAgL** [comment]
I apologize for the inconvenience. I can't find version 2.10.2 anywhere.

**#EDIT:** I managed to find it, and for those who have the same question: https://github.com/Y-Less/sscanf/
