### ISSUE TITLE
invalid assembler instruction "load.u.pri"

### ISSUE THREAD

**Issue by MatheusAgL** [pawn-lang/YSI-Includes#487]
invalid assembler instruction "load.u.pri" after YSI update.

**Comment by Y-Less** [comment]
I thought I fixed that already.  Are you on the latest YSI and compiler?

**Comment by MatheusAgL** [comment]
I using "pawn-lang/YSI-Includes@5.x" and "version": "3.10.8"

**Comment by MatheusAgL** [comment]
What to do?

I tried to use all versions available after 5.x, I did not succeed in compiling, and my compiler apparently does not compile in version 3.10.10

**Comment by MatheusAgL** [comment]
Help-me

**Comment by MatheusAgL** [comment]
I use:

Virtual Studio Code
sampctl
pawn-compiler 3.10.8
YSI 5.x

**Comment by Y-Less** [comment]
Right.  I've fixed this, but in future when a bug happens on an old version of the community compiler, but not the latest, just upgrade.  If there's a new issue with the new compiler you need to report THAT, not the old bug.
