### ISSUE TITLE
Either finish new y_text version or revert to previous one

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#49]
Few components are incompatible with new, y_text version

Related https://github.com/Misiur/YSI-Includes/issues/48

**Comment by Crayder** [comment]
I think the new y_text is fine, but some of the components haven't been updated to use it.

**Comment by Misiur** [comment]
Ah, I think I mistook it for [unfinished new y_commands](https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Visual/y_commands/funcs.txt) (or I'm wrong again about that, the flags got changed)

**Comment by Y-Less** [comment]
Decided to revert, just too many corner-cases to make it work.
