### ISSUE TITLE
y_commands OnPlayerCommandPerformed

### ISSUE THREAD

**Issue by mokiding** [pawn-lang/YSI-Includes#5]
Hello, im getting this error while compiling:

pawno\include\YSI..\YSI_Visual\y_commands/impl.inc(229) : error 025: function heading differs from prototype
gamemodes\SM/Core/Commands/Main.pwn(9) : error 025: function heading differs from prototype

Code that occur this error:

``` pawn
public OnPlayerCommandPerformed(playerid, cmdtext[], success)
{ 
    if(!success) 
    { 
        new string[128]; 
        format(string, sizeof(string), "{030CDE}[SM] {FF0000}Command %s doesn't exist.", cmdtext);
        SendClientMessage(playerid,-1, string); 
    } 
    return true; 
}
```

Using zeex compiler (tested with sa-mp's default one and same error occur)

**Comment by Misiur** [comment]
Since YSI 4.0, this function accepts different arguments, and returns different ones:

``` pawn
forward e_COMMAND_ERRORS:OnPlayerCommandPerformed(playerid, cmdtext[], e_COMMAND_ERRORS:success); 
//(...)
enum e_COMMAND_ERRORS
{
    // The majority of these are even - odd numbers return "1" not "0".
    COMMAND_ZERO_RET      = 0 , // The command returned 0.
    COMMAND_OK            = 1 , // Called corectly.
    COMMAND_UNDEFINED     = 2 , // Command doesn't exist.
    COMMAND_DENIED        = 3 , // Can't use the command.
    COMMAND_HIDDEN        = 4 , // Can't use the command don't let them know it exists.
    COMMAND_NO_PLAYER     = 6 , // Used by a player who shouldn't exist.
    COMMAND_DISABLED      = 7 , // All commands are disabled for this player.
    COMMAND_BAD_PREFIX    = 8 , // Used "/" instead of "#", or something similar.
    COMMAND_INVALID_INPUT = 10, // Didn't type "/something".
}
```

**Comment by m0k1** [comment]
Leave this open, i will close it next 24h when i test it ... Don't have tim right now :dango:

**Comment by mokiding** [comment]
I can't get it working, can you give me some example ?

**Comment by Misiur** [comment]
Sure:

``` pawn
public e_COMMAND_ERRORS:OnPlayerCommandPerformed(playerid, cmdtext[], e_COMMAND_ERRORS:success)
{
    if (success != COMMAND_OK) {
        printf("The command was not successful for player %d", playerid);
        return success;
    }
    return COMMAND_OK;
}
```

**Comment by mokiding** [comment]
I still can't get it working, where im failing ?

``` pawn
public e_COMMAND_ERRORS:OnPlayerCommandPerformed(playerid, cmdtext[], e_COMMAND_ERRORS:success)
{
    if(success == COMMAND_UNDEFINED)
    {
        new string[128]; 
        format(string, sizeof(string), "{030CDE}[SM] {FF0000}Command %s doesn't exist !", cmdtext);
        SendClientMessage(playerid,-1, string); 
        return success;
    }
    return COMMAND_OK;
}
```

Im still getting default sa-mp's "SERVER: Uknown Command!" message ...

**Comment by Misiur** [comment]
Is the "Command %s doesn't exist" sent?

**Comment by mokiding** [comment]
Nope. just default sa-mp uknown command ...

**Comment by Misiur** [comment]
Ok, change `success == COMMAND_UNDEFINED` to `success != COMMAND_OK`, and return `COMMAND_OK` instead of `success`.

**Comment by mokiding** [comment]
Nope, still not working ... Still getting sa-mp default one ...

``` pawn
public e_COMMAND_ERRORS:OnPlayerCommandPerformed(playerid, cmdtext[], e_COMMAND_ERRORS:success)
{
    if(success != COMMAND_OK)
    {
        new string[128]; 
        format(string, sizeof(string), "{030CDE}[SM] {FF0000}Command %s doesn't exist !", cmdtext);
        SendClientMessage(playerid,-1, string); 
        return COMMAND_OK;
    }
    return COMMAND_OK;
}
```

**Comment by Misiur** [comment]
Ok, the cause might be a little different then - it usually happens when runtime error occurs. If you don't have [crashdetect plugin](https://github.com/Zeex/samp-plugin-crashdetect), get it now. Also, it would be helpful if you could paste here your command code.

**Comment by mokiding** [comment]
Yes, i have crashdetect alredy ... It doesn't showing anything.

Example of my cmd

``` pawn
YCMD:testcmd(playerid,params[],help)
{
    SendClientMessage(playerid, -1, "Test cmd called and its working ?");
    return 1;
}
```

and it's printing me the "Test cmd called and its working ?" but when i call /testnone (a command that doesn't exist in Gamemode) im getting "SERVER: Unknown command."

And my OnPlayerCommandPerformed is

``` pawn
public e_COMMAND_ERRORS:OnPlayerCommandPerformed(playerid, cmdtext[], e_COMMAND_ERRORS:success)
{
    if(success != COMMAND_OK)
    {
        new string[128]; 
        format(string, sizeof(string), "{030CDE}[SM] {FF0000}Command %s doesn't exist !", cmdtext);
        SendClientMessage(playerid,-1, string); 
        return COMMAND_OK;
    }
    return COMMAND_OK;
}
```

Just run this gm and it will give same message ... I think thath there is some bug in YSI ...
https://gist.github.com/m0k1/82f6d8bd6e7e69bee5d1

**Comment by Misiur** [comment]
I don't have time to check that now, but it seems what you need is `e_COMMAND_ERRORS:OnPlayerCommandReceived(playerid, cmdtext[], e_COMMAND_ERRORS:success)`, not OnPlayerCommandPerfomed, as the second one is run only when command is... well, performed.

**Comment by mokiding** [comment]
Yeah, that fixed issuse ! Thanks. 

btw, on old YSI 3.1  it was working under OnPlayerCommandPerfomed
