### ISSUE TITLE
Problem with FOREACH_NO_ACTORS+ vehicle sirens

### ISSUE THREAD

**Issue by maximilianopagani** [pawn-lang/YSI-Includes#501]
There's a problem if you disable actors iterator (`#define FOREACH_NO_ACTORS`) and create vehicles with sirens (having vehicle iterators enabled). This is caused by `#if _FOREACH_ACTORS` conditional inside the hook to `CreateVehicle` and `AddStaticVehicleEx`. I believe this was made to detect if samp server version is the one which had sirens and actors added. Maybe there's another way to detect this, such as `#if defined GetActorPos` (used also to define `_FOREACH_ACTORS`)?

```
stock Iter_CreateVehicle(modelid, Float:x, Float:y, Float:z, Float:angle, color1, color2, respawn_delay, addsiren = 0)
{
#if _FOREACH_ACTORS
	new
		ret = CreateVehicle(modelid, x, y, z, angle, color1, color2, respawn_delay, addsiren);
#else
	#pragma unused addsiren
	new
		ret = CreateVehicle(modelid, x, y, z, angle, color1, color2, respawn_delay);
#endif
if (ret)
{
	broadcastfunc Iter_VehicleDo(true, ret);
	#if _FOREACH_LOCALS
		Iter_Add(LocalVehicle, ret);
	#endif
}
return ret;
}
```

**Comment by PrincipeAgustin** [comment]
@Y-Less 

Some solution to this?

**Comment by Y-Less** [comment]
Fixed.  I'll push shortly.
