### ISSUE TITLE
error: couldnt parse variable 'input' in 'bcrypt_verify' function

### ISSUE THREAD

**Issue by arrber** [pawn-lang/YSI-Includes#506]
my code
`
inline on_login_check()
                {
                    new rows;
                    cache_get_row_count(rows);
                    if(rows)
                    {
                        new szPassword[61];
                        cache_get_value_name(0, "password", szPassword);
                        dprint(D_CALL"password:(%s)", szPassword);

                        inline const on_check_password(bool:same)
                        {
                            dprint(D_CALL"on_check_password(%s)", same ? ("yes") : ("no"));

                            if(!same)
                            {
                                ShowDialog(playerid, DIALOG_LOGIN);
                                p_LoginAttempts[playerid]++;
                                //SendClientMessageFormatted(playerid, -1, "Incorrect logins %d/3", p_LoginAttempts[playerid]);
                                SendWarning(playerid, "If this isnt your account please leave!");
                                if(p_LoginAttempts[playerid] >= 3)
                                {
                                    return Kick(playerid);
                                }
                            }
                            else{
                                p_LoggedIn[playerid] = true;
                                p_HasAccount[playerid] = true;
                                cache_get_value_name_int(0, "id", p_AccountId[playerid]);
                            }
                        }
                        BCrypt_CheckInline(inputtext, szPassword, using inline on_check_password);
                    }
                }
                MySQL_TQueryInline(conn, using inline on_login_check, sprintf("SELECT * FROM users WHERE name = '%s';", PlayerName(playerid)));`

**Comment by Y-Less** [comment]
I think the problem is your `inputtext`.  There's a problem with y_inline and strings in closures:

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_inline/features.md#string-inputs

Note that if you're using y_dialogs it shouldn't matter.

**Comment by arrber** [comment]
> I think the problem is your `inputtext`. There's a problem with y_inline and strings in closures:
> 
> https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_inline/features.md#string-inputs
> 
> Note that if you're using y_dialogs it shouldn't matter.

Thanks for you help 
Fixed
