### ISSUE TITLE
Help me a error "YSI_MAYBE_HEAP_MALLOC"

### ISSUE THREAD

**Issue by Joko300105** [pawn-lang/YSI-Includes#507]
How To FIX a
C:\Users\Administrator\Downloads\GM BANG JOKO\gamemodes\GM.pwn(256) : warning 203: symbol is never used: "YSI_MAYBE_HEAP_MALLOC"
?? Help Mee V. New Release

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_malloc/faqs.md
