### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nessa-blue** [pawn-lang/YSI-Includes#508]
https://github.com/pawn-lang/YSI-Includes/blob/346e075c3f0ca10732ca8d01e1d966c0211a72e9/YSI_Storage/y_ini/y_ini_impl.inc#L139

YOU NEED TO SET HERE
```
#error LEARN TO SCRIPT!

**Comment by nessa-blue** [comment]
plsss fix this bug🥇

**Comment by nessa-blue** [comment]
@Y-Less He's probably going to fix this

**Comment by Y-Less** [comment]
You've not said what the bug is.  Plus, I know how to script.

**Comment by Y-Less** [comment]
In the future, if you want help with a bug it helps to ask nicely and describe your problem ("bug" is not descriptive), not demand I fix something while telling me to learn to script.

**Comment by nessa-blue** [comment]
Noo you get it wrong, add this to y ini, if anyone don't know how to fix this , just he/she can't use y ini, this is not dumb, if anyone don't know to fix this he/she will also don't know how to use y ini 📄

**Comment by nessa-blue** [comment]
@Y-Less

**Comment by Y-Less** [comment]
OK, please read this, then include a complete description of the bug:

https://stackoverflow.com/help/minimal-reproducible-example
