### ISSUE TITLE
Newest compiler (3.10.10) throws an error while using YSI 5.4.10.102

### ISSUE THREAD

**Issue by xravendale** [pawn-lang/YSI-Includes#511]
Hello, I encountered strange error exception thrown by newest compiler. 
I'am currently using YSI **5.4.10.102**, and error mentioned in the title is:

`y_compilerdata.inc(504) : error 001: expected token: "-identifier-", but found "forward"`

Error was thrown in line containing this:
`__COMPILER_TAG_DATA(Menu, 255);`

It's clean YSI from repository, nothing was changed at all.

**Comment by Y-Less** [comment]
Do you have anything like `#define Menu`?
