### ISSUE TITLE
Error using samp-bcrypt and y_inline together

### ISSUE THREAD

**Issue by Veseon** [pawn-lang/YSI-Includes#515]
I am getting an error when trying to use [`Sreyas-Sreelal/samp-bcrypt`](https://github.com/Sreyas-Sreelal/samp-bcrypt) with y_inline.

I followed the example in [`features.md#bcrypt`](https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_inline/features.md#bcrypt)

Code:
```pawn
#include <samp_bcrypt>
#include <YSI_Coding\y_inline>
#include <YSI_Extra\y_inline_bcrypt>

HashPassword(const input[])
{
	inline const OnHashed(string:result[])
	{
		printf("Hashed as: %s", result);
	}
	// Use `_` instead of `12` for the default cost parameter.
	BCrypt_HashInline(input, 12, using inline OnHashed);
}
```

Console output:
```
[SampBcrypt] [error]: The argument count mismatch expected :5 provided: 4294967295.
```

**Comment by Y-Less** [comment]
You need the latest version of samp-bcrypt, or an older version.  There was a bug in a recent release, but the new ones don't add anything needed so going backwards is safe.
