### ISSUE TITLE
y_timers slow task

### ISSUE THREAD

**Issue by PlusMixDev** [pawn-lang/YSI-Includes#516]
Hello,
I have some problem with task, my task is 1000 ms , when server is run for a long time (3 - 4 hour) with 300 players up
it's slow like 30 s per task , here is my code

`task BaccaratTask[1000]() {
    if(Baccarat[eB_State] == 0) {
        Baccarat[eB_Time] --;
        BaccaratTD_SetTime(sprintf("%02d:%02d",(Baccarat[eB_Time] / 60) % 60,(Baccarat[eB_Time] % 60)));
        if(Baccarat[eB_Time] <= 0) {
            Baccarat_Work();
        }
    }
}`

**Comment by Y-Less** [comment]
That means your code in the timer is slow.  That's not the fault of the timer itself.

**Comment by PlusMixDev** [comment]
Oh okay thanks , btw my code is just reduce variable values. i'm debugged it,  my code is end for 40 - 100 ms but it waiting for next task too long.

thanks you again.

**Comment by Y-Less** [comment]
It calls `Baccarat_Work` (first time I've seen someone make a baccarat game).

**Comment by PlusMixDev** [comment]
i tested Baccarat_Work too.
 
 Edit: Baccarat[eB_Time] is not equal to 0 that mean Baccarat_Work not call ?
