### ISSUE TITLE
YSI 3.09. Any possibility to upgrade to latest version?

### ISSUE THREAD

**Issue by TahaR9** [pawn-lang/YSI-Includes#517]
I am facing issue with the variables not being picked from a INI user file. Everything complies fine but nor the data is fetched or saved in the user files.  I guess the file saving system has changed in updates coming after YSI 3.09. 

Files are saved as follows:
```
pXP = 400
pKills = 0
pDeaths = 1
pRank = 0
pEvac = 0
pAdminLevel = 0
pHelperLevel = 0
pVipLevel = 0
```

Is there still a possibility for people using old file system (Y_INI) to be able to migrate to latest YSI and be able use the latest features.

**Comment by Y-Less** [comment]
Should do, though you don't set a tag there.
