### ISSUE TITLE
y_pp.inc:241 (warning) redefinition of constant/macro (symbol "main(")

### ISSUE THREAD

**Issue by uchihanox** [pawn-lang/YSI-Includes#518]
![Screenshot_1](https://user-images.githubusercontent.com/34406921/120075575-356ee280-c078-11eb-8d88-6fbd08c57451.png)

I've found an issue in "y_pp.inc" file while I compiling my code with sampctl. There's a way to solve this without ruining all my project?

**Comment by Y-Less** [comment]
Oh, I thought I had the #undef.  One sec.

**Comment by Y-Less** [comment]
Fixed.  Thanks.

**Comment by uchihanox** [comment]
TY. XD
