### ISSUE TITLE
y_classes error

### ISSUE THREAD

**Issue by BitFros7y** [pawn-lang/YSI-Includes#52]
.....\pawno\include\YSI..\YSI_Visual\y_classes/multiclass.inc(769) : error 017: undefined symbol "Player_InSelection"

That is error you get if you use y_classes (and it is very useful library)
Searching forums i found post Y_Less saying "Classes are not working in YSI 4". So i started searching myself just to patch it so it works for my needs (adding/removing classes after game start).

Found out these: //#include "y_classes/classcontrol" inside YSI_Visual/y_classes.inc, removing comment fixed error but gives one warning (warning 203: symbol is never used: "Class_Spawn")
By fast glance at it i think its actually deprecated function as it is commented everywhere and there is SpawnPlayer under it.

If someone could have a look and fix y_classes properly i would appreciate it.

**Comment by Crayder** [comment]
How long has it been since you updated your includes? Both of the issues you reported are fixed already. You have like a dark age version of YSI4.

**Comment by BitFros7y** [comment]
Just updated it...

**Comment by BitFros7y** [comment]
My bad i updated with some wrong version...
