### ISSUE TITLE
y_foreach bug with Iter_Free

### ISSUE THREAD

**Issue by Se8870** [pawn-lang/YSI-Includes#528]
I've been trying to testing out about Iter_Alloc and Iter_Free and found out about this.
So basically i've been trying to see what slot is free after i inserting the value using `Iter_Alloc` but it seems like it's only called 2 prints instead of 3.

```pawn
#include <a_samp>

#include <YSI_Data\y_iterate>

#define MAX_COUNT 100

new 
	Iterator:myIter<MAX_COUNT>;

main() 
{
	SetTimer(#OnInit, 5000, false);
}

forward OnInit();
public OnInit()
{
	printf("Free slot is at: %d", Iter_Alloc(myIter));
	printf("Free slot is at: %d", Iter_Alloc(myIter));
	printf("Free slot is at: %d", Iter_Free(myIter));
	return 1;
}
```

This is the output of that code:
```
Free slot is at: 0
Free slot is at: 1
```

The weird things happen when i change from`Iter_Free` to `Iter_Alloc` in the last print, it would perfectly printed all.
```
Free slot is at: 0
Free slot is at: 1
Free slot is at: 2
```

I'm using lastest version of YSI 5.x branch, testing it on windows 10 using sampctl.

**Comment by Se8870** [comment]
The reason why i put 5 second delay, is because when i check using `Iter_Free` inside `main`, it give me `--` instead of `0` or any number.

**Comment by Y-Less** [comment]
I just ran the code you posted and couldn't reproduce this:

```
Free slot is at: 0
Free slot is at: 1
Free slot is at: 2
```

What OS?

**Comment by Se8870** [comment]
> I just ran the code you posted and couldn't reproduce this:
> 
> ```
> Free slot is at: 0
> Free slot is at: 1
> Free slot is at: 2
> ```
> 
> What OS?

Windows 10 Home with sampctl installed.
I use `sampctl package run --forceBuild` for building and running the project.

**Comment by Se8870** [comment]
I can assume this is because my computer is somehow got viruses or smth and it messes with YSI include. Because when i try to fresh install my windows it's working correctly now.
