### ISSUE TITLE
y_android undefined symbol

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#529]
> YSI_Data\y_foreach\..\..\YSI_Core\y_core\..\..\YSI_Players\y_android\y_android_entry.inc(187) : error 017: undefined symbol "SendClientCheck"; did you mean "SendClientCheck__"?

I installed the latest version and I am getting this error.

**Comment by Y-Less** [comment]
You need to update your SA:MP includes, its a native that was missed from the originals.  Though I thought I switched the code to not needing it (AND I thought fixes.inc covered it).

**Comment by MaxAndolini** [comment]
![image](https://user-images.githubusercontent.com/6771759/123536052-a1547180-d730-11eb-93fa-d660c921043a.png)

I've updated the fixes.inc and the others are up to date as well. The problem still continues. I am using SA-MP 0.3.DL. It might help others if you put a define for it.

**Comment by Y-Less** [comment]
Turns out I HAD fixed it, just not pushed it.  Done now.

**Comment by MaxAndolini** [comment]
> YSI_Data\y_foreach\..\..\YSI_Core\y_core\..\..\YSI_Players\y_android\y_android_entry.inc(101) : warning 231: state specification on forward declaration is ignored

I updated it now and there is this warning now.

**Comment by Y-Less** [comment]
Oh I know why
