### ISSUE TITLE
y_itterate

### ISSUE THREAD

**Issue by BitFros7y** [pawn-lang/YSI-Includes#53]
I use y_itterate instead foreach (its better and i have my own items to loop thru)

If you just include y_itterate it will give you warning warning 203: symbol is never used: "Iter_Func@Range"

Searching for fix http://forum.sa-mp.com/showthread.php?t=569563
Fix: YSI_Data/y_foreach/iterators.inc -> add stock in front of  iterfunc Range(cur, min, max, step = 1)

Sorry for posting it these way, i would fix it myself and send pull request but im not friendly with git.

**Comment by Crayder** [comment]
This has been fixed a long time ago.

**Comment by BitFros7y** [comment]
Sorry, my bad, appears i downloaded some wrong version (probably by samphunter).

**Comment by Crayder** [comment]
Other than those two bugs that have already been fixed, YSI4 is still considered to be in beta. So don't be surprised if there are real bugs. Just make sure you always have the latest version.

(Perhaps you really do have a negative IQ? Lol, JK.)
