### ISSUE TITLE
REVEEEEEEEEERT

### ISSUE THREAD

**Issue by SageSyS** [pawn-lang/YSI-Includes#540]
Revert to b894c68419f828054aad1f4692db0c354da884fe before I commit homicide

**Comment by Y-Less** [comment]
Why?  That's pretty much just an internal commit for testing open.mp code without dialogs.  It does nothing if you don't explicitly enable it.

**Comment by SageSyS** [comment]
Remove this awful 15 line init message is what I meant..
Like, we already know that YSI is there just by having 2TiB amx file
