### ISSUE TITLE
Fix all the warning 208 (function with tag result used before definition)

### ISSUE THREAD

**Issue by rt-2** [pawn-lang/YSI-Includes#553]
Since YSI was updated to 5.x from 4.x, those warnings appeared:
`warning 208: function with tag result used before definition, forcing reparse`

**Comment by ghost** [comment]
Can you a bit more verbose? This happens when a function is used (that's declared with a tag) before it was defined. For example:
```c
main()
{
    printf("Result is: %i", Foo(0));
}

bool:Foo(input)
{
    if (input)
    {
        return true;
    }
    return false;
}
```

I didn't ever get that warning from YSI, even after upgrading. Are you sure it's caused by YSI?
Can you a bit more verbose? What's the code causing the warning?

**Comment by rt-2** [comment]
Is there a way to disable those warnings by any chance?
Thank you.

**Comment by ghost** [comment]
Well, most likely by fixing your code: I never had this problem in multiple scripts after upgrading YSI. It's quite likely it's caused by something you did (not sure, that's why I asked to be a bit more verbose and what code is causing it).
Anyway, you can disable warnings using `#pragma warning disable` (and `enable` to re-enable them).
Eg. 
```c
#include <a_samp>

static enum E_MY_ENUM
{
    E_ENUM_FOO,
    E_ENUM_BAR
};
static s_myArray[E_MY_ENUM] = {1337, 69};

static SaveArrayToFile()
{
    new File:myArrayFile = fopen("myArray.bin", io_write);
#pragma warning disable 229
    fblockwrite(myArrayFile, s_myArray);
#pragma warning enable 229 //RE-ENABLE THE WARNING!! Disabling warnings is a very bad idea. Want to make sure that other mistakes are caught!!!
    fclose(myArrayFile);
}

main()
{
    SaveArrayToFile();
}
```
The problem in this code is that `flockwrite()` will always trigger warning 229 (index tag mismatch). This can be overcome by declaring enumerator `E_MY_ENUM` as `_:E_MY_ENUM`.
However, that tag is there for a reason, thus the need of disabling that warning in that function **and enabling it again afterwards**.

**Comment by rt-2** [comment]
> Well, most likely by fixing your code: I never had this problem in multiple scripts after upgrading YSI. It's quite likely it's caused by something you did (not sure, that's why I asked to be a bit more verbose and what code is causing it).

I have this error more than 500 times in a script that is prob about 200,000 lines long in a project I started more than 10 years ago when I was 15. In this situation I can spend half of my life trying to "fix my script" but I am more than likely to break something in the process and it has not been written for that anyway (there is recursions too at some places). "forcing reparse" is very not an issue for me, I am already doing great speed with compiling with the custom compiler.

That's why I'm just looking to disable those warning. I never saw them before I updated from 4.x to 5.x so I assumed it had smth to do with YSI but I know the warning are pointing and I know what they mean.
rt-2

**Comment by ghost** [comment]
Well, see my previous reply (#pragma warning)

**Comment by rt-2** [comment]
> Well, see my previous reply (#pragma warning)

Can I disable only 1 type of warning by any chance?
Im sorry to ask here but the wiki and forum is down you know :/

**Comment by ghost** [comment]
If you look at that piece of code I sent you'll notice I only disabled and enabled warning 229: `#pragma warning disable 229`
You in fact must specifically tell the compiler which warnings to disable/enable. Eg. `#pragma warning enable 229,219,239`
As for the wiki: There is https://open.mp/ (check out the 'Docs' page). As for the forums, see: https://burgershot.gg/ 
There's also https://team.sa-mp.com/wiki-archive.html (wiki archive from sa-mp), https://sampwiki.blast.hk/wiki/Main_Page (alternative wiki archive) and https://sampforum.blast.hk/ (SA-MP Forums archive).
If you have Discord you also might want to check out the Discord server of open.mp: https://discord.gg/wks6GpQK (note that this invite is deleted in 24 hours)

**Comment by rt-2** [comment]
Im really sorry I didn't read properly. You're example is exactly what I needed.
Thank you.
