### ISSUE TITLE
Problem with y_iterate

### ISSUE THREAD

**Issue by C-far** [pawn-lang/YSI-Includes#56]
Here my logs : 

```
[00:58:37] SendReport 0 (Iter_Free)
[00:58:38] SendReport 1 (Iter_Free)
[00:58:38] SendReport 2 (Iter_Free)
[00:59:20] DialogReportSelect 0 (Iter_Remove)
[00:59:21] DialogReportSelect 1 (Iter_Remove)
[00:59:22] DialogReportSelect 2 (Iter_Remove)
[00:59:31] SendReport 1 (Iter_Free)
```

Logically, I'm supposed to get the value 0 with "Iter_Free" because "Iter_Remove" was deleted it, but I get the value 1.

I've tested foreach renaming "y_iterate" for foreach doesn't use it, and Iter_Free returns me 0 correctly.

**Comment by C-far** [comment]
Another test : 

``` pawn
#include <a_samp>
#include <foreach>

new
    Iterator:Test<10>;

main()
{
    new
        test;

    for(new j = 0; j < 2; j++)
    {
        for(new i = 0; i < 3; i++)  
        {
            test = Iter_Free(Test);
            printf("Iter_Free = %d", test);

            Iter_Add(Test, test);
        }

        for(new i = 0; i < 3; i++)  
        {
            Iter_Remove(Test, i);
        }

        print(" ");
    }
}
```

Logs : 

```
Iter_Free = 0
Iter_Free = 1
Iter_Free = 2

Iter_Free = 1
Iter_Free = 0
Iter_Free = 2
```

**Comment by Crayder** [comment]
That's all correct. Obviously it's going to print the correct free slots when you already cleared them.

**Comment by Crayder** [comment]
Here is a more proper test to prove what I am saying is true.

```
#include <a_samp>
#include <YSI\y_iterate>

new
    Iterator:Test<10>;

main()
{
    new
        test;

    for(new j = 0; j < 2; j++)
    {
        printf("Testing free slots... and adding!");
        for(new i = 0; i < 3; i++)  
        {
            test = Iter_Free(Test);
            printf("Iter_Free = %d", test);

            Iter_Add(Test, test);
        }

        printf("Testing slots... 1");
        foreach(new i: Test) 
        {
            printf("Used Slot = %d", i);
        }

        printf("Removing all...");
        for(new i = 0; i < 3; i++)  
        {
            Iter_Remove(Test, i);
        }

        printf("Testing slots... 2");
        foreach(new i: Test) 
        {
            printf("Used Slot = %d", i);
        }

        print(" ");
    }
}
```

**Comment by C-far** [comment]
I've tested your code, there is an infinite loop.
It prints the value 2 for your second foreach.

**Comment by Crayder** [comment]
There is definitely not, I tested it before I posted. It works perfectly exactly as it should.

**Comment by Crayder** [comment]
In fact, here are the results:

```
Testing free slots... and adding!
Iter_Free = 0
Iter_Free = 1
Iter_Free = 2
Testing slots... 1
Used Slot = 0
Used Slot = 1
Used Slot = 2
Removing all...
Testing slots... 2

Testing free slots... and adding!
Iter_Free = 0
Iter_Free = 1
Iter_Free = 2
Testing slots... 1
Used Slot = 0
Used Slot = 1
Used Slot = 2
Removing all...
Testing slots... 2
```

**Comment by C-far** [comment]
I just update YSI4 and effectively, it works.

**Comment by Crayder** [comment]
So, issue closed?

(edit: not saying that in a rude way, I mean it like I'm asking if you need any further assistance)

**Comment by C-far** [comment]
Warning just, in the file iterators.inc : 

``` pawn
                #if _FOREACH_BOTS
                    Iter_Add(Character, i);
                    if (IsPlayerNPC(i))
                    {
                        Iter_Add(Bot, i);
                    }
                    else
                #endif
                #if _FOREACH_PLAYERS
                    {
                        Iter_Add(Player, i);
                    }
                #endif
```

If FOREACH_NO_PLAYERS is defined before including, there will be an error because there is an "else" without a block.

Same for _FOREACH_BOTS.

**Comment by Y-Less** [comment]
I think you might be correct about that - the `_FOREACH_BOTS` define should depend on the `_FOREACH_PLAYERS` define in "y_iterate.inc", so that you can only have the former with the latter (you can't know if someone is a bot if you don't have any players at all).  Actually, I'm not sure if that is the case.  There are a few interacting macros that go in to this - the ones that start with `_` are internal so shouldn't be set be users.  The problem is easy to fix though by wrapping the `else` in an extra `#if`.

**Comment by Y-Less** [comment]
If you are closing this issue, since the original problem was solved, could you open a new one for the compile settings error you just mentioned?
