### ISSUE TITLE
Experimental y_iterate update

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#57]
https://github.com/Misiur/YSI-Includes/commit/0447dea82779820ab5633b51ab7ab23dacb29689

Fails to compile, at https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Data/y_foreach/impl.inc#L292 as both `F@p` and `F@q` changed. To be investigated.

Add tests as well

**Comment by Misiur** [comment]
Refs https://github.com/Misiur/YSI-Includes/issues/54

**Comment by Y-Less** [comment]
I might have incorrectly identified that macro as no longer needed so re-used the name.  But I also might not have...

**Comment by Misiur** [comment]
Bugtracking log:

https://github.com/Misiur/YSI-Includes/blob/0447dea82779820ab5633b51ab7ab23dacb29689/YSI_Data/y_foreach/impl.inc#L292

This macro used to match

`for(new  i =(_:F@n:iterstart@Reverse!=iterstart@Reverse $);_:( i =!=iterstart@Reverse (_:!=iterstart@Reverse ,iter))!=iterstart@Reverse ;)`

So, the main suspect is changed `F@l` and `_iter_Advance_S`

**Comment by Misiur** [comment]
https://gist.github.com/Misiur/c7ef6b6dc5d26bf1e2db

I think this fixes Reverse iterator, but the experimental changes fail to compile on @iterfunc (such as GroupMember)

**Comment by Y-Less** [comment]
Can I close this?  I think the y_iterate code has changed so much that this doesn't apply any more.  There are tests for `Reverse(iter)` which seem to run fine.

**Comment by Misiur** [comment]
Sure thing
