### ISSUE TITLE
[WARNING] redefinition of constant/macro (symbol "u@$")

### ISSUE THREAD

**Issue by Se8870** [pawn-lang/YSI-Includes#576]
When trying to use the repo version (not release version), i got these error when including YSI lib, for example `y_groups`, `y_commands`, etc.

```
C:\Users\yuusha\Desktop\ysi-test\dependencies\code-parse.inc\code-parse.inc:56 (warning) redefinition of constant/macro (symbol "u@$")
C:\Users\yuusha\Desktop\ysi-test\dependencies\YSI-Includes\YSI_Data\y_foreach\y_foreach_macros.inc:890 (warning) redefinition of constant/macro (symbol "u@$")
WARN: Build default complete with 2 problems
```

**MCVE**
```pawn
// generated by "sampctl package init"
#include <a_samp>

#include <YSI_Data\y_iterate>
#include <YSI_Visual\y_dialog>
//#include <YSI_Player\y_groups>


main()
{
        // write code here and run "sampctl package build" to compile
        // then run "sampctl package run" to run it
}
```

**Steps to reproduce**
1. Get YSI with `sampctl install pawn-lang/YSI-Includes`
2. Include any of YSI lib
3. build it using `sampctl build`

**Comment by Y-Less** [comment]
Update code-parse.inc

**Comment by Se8870** [comment]
It seems like `sampctl` 1.10.1/dev version fetching the latest version and not fetching the up-to-date branch, so it still have this warning until you update the versions.

The quick issues is to specify branch manually using `pawn-lang/YSI-Includes@5.x` otherwise it won't work.
And if you're not sampctl user, just do what Y_Less said.
