### ISSUE TITLE
After updating can't compile (Blank compiler)

### ISSUE THREAD

**Issue by SaboT94** [pawn-lang/YSI-Includes#581]
Hi, after updating to latest version from 5.05.0403, i can't compile, can't even see error.

Compiler is blank. https://imgur.com/PNHoSnC

Using latest compiler 3.10.10 etc.

**Comment by realhus** [comment]
same here

**Comment by SaboT94** [comment]
> same here

https://github.com/pawn-lang/YSI-Includes/issues/585

This is not answer for me, i don't even have IsNumeric, still hang's...

**Comment by SaboT94** [comment]
Found problem!!!

#include	<utils> removed and everything okay!
