### ISSUE TITLE
function heading differs from prototype

### ISSUE THREAD

**Issue by plakapenka** [pawn-lang/YSI-Includes#582]
`C:\Users\plaka\Desktop\noxe\dependencies\YSI-Includes\YSI_Core\y_core\y_scriptinit_impl.inc:853 (error) function heading differs from prototype
C:\Users\plaka\Desktop\noxe\dependencies\YSI-Includes\YSI_Core\y_core\y_scriptinit_impl.inc:853 (warning) state specification on forward declaration is ignored
C:\Users\plaka\Desktop\noxe\dependencies\YSI-Includes\YSI_Core\y_core\y_scriptinit_impl.inc:855 (error) function heading differs from prototype
C:\Users\plaka\Desktop\noxe\dependencies\YSI-Includes\YSI_Core\y_core\y_scriptinit_impl.inc:1213 (warning) redefinition of constant/macro (symbol "OnScriptInit(%0)")
C:\Users\plaka\Desktop\noxe\dependencies\YSI-Includes\YSI_Data\y_foreach\y_foreach_macros.inc:890 (warning) redefinition of constant/macro (symbol "u@$")`

when installing via sampctl. Code from pawn json
`"dependencies": [
		"Zeex/samp-plugin-crashdetect:v4.19.4",
		"sampctl/samp-stdlib",
		"samp-incognito/samp-streamer-plugin:v2.9.5",
		"YashasSamaga/I-ZCMD",
		"Y-Less/sscanf:v2.11.4",
		"ziggi/rustext:v2.0.8",
		"Southclaws/progress2:2.3.0",
		"Open-GTO/mdialog:1.4.3",
		"pBlueG/SA-MP-MySQL:R41-4",
		"pawn-lang/YSI-Includes:v5.05.0505",
		"Pottus/ColAndreas:v1.4.0.3"
	],`

if you remove the version then everything is fine

**Comment by Y-Less** [comment]
Use the latest version.
