### ISSUE TITLE
[Warning] Parameter count does not match specifier in `Script_Call`. callback: Iter_OnGameModeInit - fmat:  - count: 3)

### ISSUE THREAD

**Issue by Abyss-z94** [pawn-lang/YSI-Includes#583]
I've try to use YSI include on my new gamemode for omp but got this warning
![124](https://user-images.githubusercontent.com/18276778/164580667-fcd0e2d2-9c60-432c-8f93-1474aa068b14.png)

**Comment by wnekiro** [comment]
i have the same issue

**Comment by Y-Less** [comment]
That's an old version of YSI.
