### ISSUE TITLE
Compiler hanging issue 

### ISSUE THREAD

**Issue by realhus** [pawn-lang/YSI-Includes#585]
After hours of trying i finally found out why my compiler freezes
There is an issue with redefining  IsNumeric (its already defined in YSI)
```
#include <a_samp>


#include "YSI_Coding\y_hooks.inc"


stock IsNumeric(const string[])
{
	new j = strlen(string);
	if(j == 0) return 0;

	for(new i = 0; i < j; i++)
	{
		if(string[i] > '9' || string[i] < '0') return 0;
	}
	return 1;
}
```

just try running this code and the compiler will crash

**Comment by Y-Less** [comment]
The crash is fixed in 3.10.11.  Otherwise this isn't really a YSI bug.  The problem is two different places declaring different versions of the same function, that's not either place's fault.
