### ISSUE TITLE
NEWEST YSI include problems

### ISSUE THREAD

**Issue by golub018a** [pawn-lang/YSI-Includes#586]
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(94) : error 001: expected token: "-identifier-", but found "-integer value-"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(96) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(102) : error 001: expected token: "-identifier-", but found "-integer value-"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(104) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(106) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(108) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(117) : error 001: expected token: "-identifier-", but found "("
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(120) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(122) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(128) : error 001: expected token: "-identifier-", but found "-integer value-"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(131) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(133) : error 010: invalid function or declaration
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(372) : error 017: undefined symbol "Iterator@Vehicle"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(372) : error 017: undefined symbol "Iterator@Vehicle"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(372) : error 017: undefined symbol "Iter_Single@Vehicle"
C:\Users\Golub\Desktop\Skripta\Los Bosmos v1\pawno\include\YSI_Data\y_foreach\y_foreach_iterators.inc(372) : fatal error 107: too many error messages on one line

Compilation aborted.

Pawn compiler 3.10.4	 	 	Copyright (c) 1997-2006, ITB CompuPhase

16 Errors.
[Finished in 1.4s]

My include order: https://prnt.sc/-9Qz8Ec46SBk

**Comment by Y-Less** [comment]
Fixed.  It was a compatibility mode issue.
