### ISSUE TITLE
[5.x] How i can get group commands?

### ISSUE THREAD

**Issue by godylector** [pawn-lang/YSI-Includes#597]
I try using Group_Command(Group:....) but result is 'constant symbol has no size'

**Comment by xunder-matth** [comment]
Use `Group_Command`
```
foreach(new i : Group_Command(group))
{
    printf("Group %d: /%s", group, Command_GetName(i));
}
```

**Comment by JustinzDev** [comment]
![image](https://user-images.githubusercontent.com/49568707/174928300-4db2b472-10df-4749-ac10-8052684cf576.png)
result is 'constant symbol has no size'

**Comment by godylector** [comment]
> Use `Group_Command`
> 
> ```
> foreach(new i : Group_Command(group))
> {
>     printf("Group %d: /%s", group, Command_GetName(i));
> }
> ```

![image](https://user-images.githubusercontent.com/49568707/174928300-4db2b472-10df-4749-ac10-8052684cf576.png)
result is 'constant symbol has no size'
