### ISSUE TITLE
y_amx questions

### ISSUE THREAD

**Issue by C-far** [pawn-lang/YSI-Includes#60]
Hi,

I would want to know what do you want to mean in this comment ? : 

``` Pawn
// This is based on the AMX version used in SA:MP - it DOES NOT match the code
// found in the PAWN documentation as that's for a later version.
```

The AMX used in SAMP is different of the original AMX ?

**Comment by Crayder** [comment]
Not completely different, but yes. We are using a modified, older version.

**Comment by C-far** [comment]
What is the difference ? 'Cause I don't really understand the purpose in OnScriptInit.

**Comment by Crayder** [comment]
OnScriptInit's main purpose is libraries. Instead of checking for filterscripts and calling either OnGameModeInit or OnFilterScriptInit you just call the all-in-one OnScriptInit. It makes life easier.

**Comment by C-far** [comment]
I understood very well that.
But in the file YSI_Storage\y_amx.inc, at the function OnScriptInit, there is this : 

``` Pawn
public OnScriptInit()
{
    new
        addr,
        data;
    #emit LCTRL                     1
    #emit STOR.S.pri                addr
    // Invert to get the prefix offset relative to the data.
    // Get all the script data.
    addr = -addr;
    // Now read in all the data.
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_SIZE         = data;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_MAGIC        = data & 0xFFFF;
    AMX_HEADER_FILE_VERSION = data >>> 16 & 0xFF;
    AMX_HEADER_AMX_VERSION  = data >>> 24;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_FLAGS        = data & 0xFFFF;
    AMX_HEADER_DEFSIZE      = data >>> 16;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_COD          = data;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    //dat = data;
    AMX_HEADER_DAT          = 0;
    AMX_BASE_ADDRESS = -data;
    AMX_HEADER_COD += AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_HEA          = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_STP          = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_CIP          = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_PUBLICS      = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_NATIVES      = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_LIBRARIES    = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_PUBVARS      = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_TAGS         = data + AMX_BASE_ADDRESS;
    addr += 4;
    #emit LREF.S.pri                addr
    #emit STOR.S.pri                data
    AMX_HEADER_NAMETABLE    = data + AMX_BASE_ADDRESS;
    // Now find the AMX's base address in global memory.  This is VERY handy to
    // have for more advanced functionality (none of which actually exists yet).
    AMX_REAL_ADDRESS = AMX_GetGlobal();
    AMX_REAL_DATA = AMX_REAL_ADDRESS - AMX_BASE_ADDRESS;
    // Call next ALS callback.
    #if defined YSI_LOCK_MODE
        GetServerVarAsString(YSI_gLockData, YSI_gLockData[5], sizeof (YSI_gLockData) - 5);
    #endif
    #if defined AMX_OnScriptInit
        AMX_OnScriptInit();
    #endif
    return 1;
}
```

And I don't understand, what is it exactly.

**Comment by Y-Less** [comment]
It gets the data from the AMX header and stores it all in global variables so that it can all be used within the script.  So, for example, you can find out how many public functions there are in the script.

It is very similar in purpose to this library:

https://github.com/Zeex/amx_assembly/blob/master/amx_header.inc

However, they implement it in slightly different ways.  Also, the y_amx data is offset relative to the data segment, so you can access the data directly, the amx_header one is just the original data so it is more accurate.  Both have their uses, and both are used throughout YSI - I probably would have written everything to use amx_header instead of y_amx, but it didn't exist yet when I wrote a lot of the code.

So, for example `AMX_HEADER_PUBLICS` is an offset to the public functions table, so doing:

``` pawn
AMX_Read(AMX_HEADER_PUBLICS + 8);
```

Will get whatever is 8 bytes in to the public functions table in the AMX header.  If you don't know what that means, read pawn-impl.pdf.  If you still don't know what that means, don't worry about it - you don't need these features for most SA:MP scripts, they are used for actually implementing new features of the PAWN language itself, like the "hook" and "inline" keywords.

**Comment by C-far** [comment]
Ah ok thanks, I understand. I think use it for tests and to learn more.

Just, a second question which isn't linked with the principal sudject : where can I find the source code when a variable is declared ? I don't know if it's placed in the source of the compiler or the AMX.

**Comment by Crayder** [comment]
I'm pretty sure it'd be in the 'compiler' part of pawn's source code.

Specifically, https://github.com/compuphase/pawn/tree/master/compiler

I skimmed somewhat but don't see anything relevant (keyword, _skimmed_).

**Comment by C-far** [comment]
I found in the file sc.h at the line 526 : 

``` C
SC_FUNC symbol *addvariable(const char *name,cell addr,int ident,int vclass,int tag,
                            int dim[],int numdim,int idxtag[]);
```

See in sc2.c addvariable, addsym and addsymbol.

**Comment by Y-Less** [comment]
When you declare a variable the compiler allocates space in the amx.  Other than that, your question doesn't really make much sense.

**Comment by C-far** [comment]
When I see the instructions in some opcodes, there are 95% the data.
So I seek, when the address of the variables are related to the data.

'Cause for me, the address of a variable in the stack is Frame Pointer + Relative address (LCTRL 5 + CONST.alt + ADD).

Example : 

``` Pawn
new
    var = 5;

#emit LCTRL 5 
#emit CONST.alt var
#emit ADD
```

Here, I get the real address of the variable 'var' in the register primary. (I could have used ADDR.pri).
But to get the value I can use LOAD.I and if I see his instructions : 

``` C
pri= * (cell *)(data+(int)pri);
```

There are the data and there, I don't understand why.

Well, I don't know if you understood me.

**Comment by Y-Less** [comment]
I understood the last sentence...

**Comment by C-far** [comment]
Aha !
So I said the DATA is everywhere in the instructions in some opcodes.

In amx.c, at the function amx_Exec, I take in example LOAD.i : 

``` C
case OP_LOAD_I:
    /* verify address */
    if (pri>=hea && pri<stk || (ucell)pri>=(ucell)amx->stp)
    ABORT(amx,AMX_ERR_MEMACCESS);
    pri= * (cell *)(data+(int)pri);
    break;
```

Imagine the register primary contains the address of any variable.
If I use LOAD.I, the register primary will contain then the value at the address.

And there, I didn't understand why we need to add the data with the primary to get an another address.

**Comment by Y-Less** [comment]
"data" is the true location in memory of your amx.  "pri" holds the location of your variable in the amx.  A global variable may have a location of "28" - that means it is located 28 bytes in to the script.  However, the script itself is loaded somewhere in memory, so we must get the true location of that variable to be able to read it.

**Comment by C-far** [comment]
Ok I understand, thanks Alex :D
