### ISSUE TITLE
warning 213: tag mismatch Bitstream

### ISSUE THREAD

**Issue by plakapenka** [pawn-lang/YSI-Includes#604]
`
hook stock OnIncomingCustomPacket(playerid, rpcid, BitStream:bs)
{
	if(rpcid == RPC_SHOW_FACTORY_GAME)
	{
		new exit_type;
		BS_ReadUint8(bs, exit_type);

		if (exit_type) 
		{	// успешно
			Zavod_PlayerBuildSucces(playerid);
		} 
		else 
		{	// закрыл
			SetPVarInt(playerid, "pZavod_State", ZAVOD_PLAYER_STATE_STARTED);
		}
		return ~1;
	}
	return continue(playerid, rpcid, bs);
}
`

Err:
`warning 213: tag mismatch: expected tags "Bit", "Text", "Group", "File", "Float", "Text3D", or none ("_"); but found "BitStream"`

**Comment by xunder-matth** [comment]
Add `BitStream` to `CUSTOM_TAG_TYPES`.

`#define CUSTOM_TAG_TYPES BitStream`

**Comment by plakapenka** [comment]
it works. ty
