### ISSUE TITLE
Run time error 5: "Invalid memory access"

### ISSUE THREAD

**Issue by RonaldoBueno16** [pawn-lang/YSI-Includes#646]
I'm using modules, calling the callbacks with y_hooks.

But I'm getting this crash:

[debug]
[debug] Parameter count corrections:
[debug]
[debug] The 1st mangled argments (e.g. `<1073741823 arguments>`) below should read `<2 arguments>`
[debug] The 2nd mangled argments (e.g. `<1073741823 arguments>`) below should read `<1 arguments>`
[debug]
[debug] Run time error 5: "Invalid memory access"
[debug] AMX backtrace:
[debug] #0 0001a4a8 in public OnRequestGameSpawn (0, 0) at D:\SAMP\Enguica.PVP\pawno\include\YSI_Coding\y_hooks\..\y_cgen\y_cgen.inc:193
[debug] #1 native CallLocalFunction () in samp-server.exe
[debug] #2 0014782c in @yH_OnPlayerSpawn@046 (playerid=0) at modulos/games/base.pwn:224
[debug] #3 0001a0e4 in public OnPlayerSpawn (0) at D:\SAMP\Enguica.PVP\pawno\include\YSI_Coding\y_hooks\..\y_cgen\y_cgen.inc:133

**Comment by Y-Less** [comment]
That crash is in your code, somewhere in `OnRequestGameSpawn`.
