### ISSUE TITLE
 warning 208: function with tag result used before definition, forcing reparse

### ISSUE THREAD

**Issue by ivanboskic1** [pawn-lang/YSI-Includes#647]
How to fix 
C:\Users\Windows 10\Documents\SAMP Projects\spotify-project\pawno\include\ysilib\YSI_Storage\y_ini\y_ini_impl.inc(828) : warning 208: function with tag result used before definition, forcing reparse
C:\Users\Windows 10\Documents\SAMP Projects\spotify-project\pawno\include\ysilib\YSI_Storage\y_ini\y_ini_impl.inc(1258) : warning 208: function with tag result used before definition, forcing reparse
C:\Users\Windows 10\Documents\SAMP Projects\spotify-project\pawno\include\ysilib\YSI_Storage\y_ini\y_ini_impl.inc(1279) : warning 208: function with tag result used before definition, forcing reparse
C:\Users\Windows 10\Documents\SAMP Projects\spotify-project\pawno\include\ysilib\YSI_Storage\y_ini\y_ini_impl.inc(1355) : warning 208: function with tag result used before definition, forcing reparse

Code
https://pastebin.com/6J8hQTsF

**Comment by ivanboskic1** [comment]
Fixed

**Comment by shierru** [comment]
If I were you, I would close the issue if the issue has been resolved. This is confusing when looking at unclosed issues to find a similar situation. Thank you!
