### ISSUE TITLE
y_timers - ptask bug?

### ISSUE THREAD

**Issue by PatrickGTR** [pawn-lang/YSI-Includes#65]
Error
`E:\sfcnr\gamemodes\core/server/robbery/core.pwn(57) : error 047: array sizes do not match, or destination array is too small`

Code
`'ptask RobberyUpdate[1000](playerid)
{
    //codes
    return 1;
}'`

Even when the timer is empty, the error still shows.

**Comment by Crayder** [comment]
One thing you need to do is replace all of the '/' from your `#include` paths with '\'. Yes, that does matter for a lot of things.

For the error, I just tested that code (yes with the latest version), it compiles just fine for me.

**Comment by Y-Less** [comment]
That doesn't matter for non-YSI includes.  The problem is when you redefine MAX_PLAYERS after including YSI instead of before (since it too needs to know of your modification).

**Comment by PatrickGTR** [comment]
Thanks, Y_less, sorted. Crayder thanks for the tip aswell.
