### ISSUE TITLE
y_inline_mysql

### ISSUE THREAD

**Issue by ASGOOD1** [pawn-lang/YSI-Includes#650]
inline addToDatabase()
			{
				pInfo[playerid][pKey] = cache_insert_id();
				printf("(!) New Account: %s(%d) with SQLID - #%d", getName(playerid), playerid, pInfo[playerid][pKey]);
				cvector_push_back_arr(accountNames, getName(playerid));
			}
			MySQL_TQueryInline(SQL, using inline addToDatabase, "INSERT INTO `accounts` (`Username`, `Password`, `Money`) VALUES ('%q', '%q', '10000')", getName(playerid), PWDHash(inputtext));

What is wrong with this code

**Comment by xunder-matth** [comment]
Use `%e` instead of `%q`.
