### ISSUE TITLE
y_text

### ISSUE THREAD

**Issue by AndiChs** [pawn-lang/YSI-Includes#66]
Hello!
Text_Send can't be used with groups,PA, ALL_PLAYERS etc. .

**Comment by AndiChs** [comment]
No one is still developing this library?

**Comment by Crayder** [comment]
Yes, it's still being developed. Rushing an issue isn't going to help you out though.

**Comment by knife-s** [comment]
so this is a bug?
I was wondering why I can't use Text_Send with ALL_PLAYERS, which function I can use then? a foreach loop?

**Comment by Misiur** [comment]
Closed as per https://github.com/Misiur/YSI-Includes/issues/210
