### ISSUE TITLE
What does callbackfix.amx do?

### ISSUE THREAD

**Issue by tek2ldk** [pawn-lang/YSI-Includes#660]
Every time I turn on my SA-MP server, I receive the message: " Filterscript '../scriptfiles/callbackfix.amx' loaded.". Today I became curious about what callbackfix.amx is for.

I would also like to receive information about "/scriptfiles/YSI/fixes/" and "/scriptfiles/YSI/temp/" what is it for?

**Comment by Y-Less** [comment]
It fixes callbacks.  Some callbacks are only called correctly in filterscripts in SA:MP, so callbackfix.amx forwards the calls on to the gamemode.

Those other directories are just places where YSI keeps its various files neatly organised.
