### ISSUE TITLE
Error when updating YSI

### ISSUE THREAD

**Issue by MatheusAgL** [pawn-lang/YSI-Includes#663]
I am currently using "pawn-lang/YSI-Includes#862a56d6bc684e100f5a72bd3fefa36e03e132ee" with sampctl.
Because when I update to the latest version, I receive numerous warnings about it:

`tag mismatch: expected tag "Timer" , but found none ("_" )`

**Comment by medzvel** [comment]
Add tags to your timer functions _:

**Comment by Y-Less** [comment]
Fixed
