### ISSUE TITLE
Command_TouchNamed

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#69]
Hi guys, I'm back for some time. Can someone remind me how to restrict command to group using 

``` pawn
GROUP_ADD<Group> 
{ 
    @YCMD:command; 
}
```

? I don't remember what happended to `Command_Touch`, so either there was some newer method (lost with YSI 4 thread archive), or it doesn't work at all.

**Comment by Y-Less** [comment]
I think this is what you want:

https://github.com/Misiur/YSI-Includes/blob/1cd253af4477589dc8778cb6bf87d92014b38e8c/y_commands.inc#L1123-L1177

Looking at the code, I think it should still be fine as-is.

**Comment by Misiur** [comment]
Neat, works! One more question: After including y_groups all commands started returning "Unknown command" unless explicitly adding player to group with permission set to true. Are all commands not available to global group by default, or should I treat it as a bug? I'll test later with OnCommandReceived what exactly is returned

**Comment by Misiur** [comment]
Ref https://github.com/Misiur/YSI-Includes/commit/2a3f80e1651bc9d339771d840b0d2a363b1412e7

**Comment by Y-Less** [comment]
I actually can't remember what the default is.  However, you can set the default with something like `Group_SetGlobalCommandDefault(true);`.
