### ISSUE TITLE
Y Hooks

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#73]
warning 200: symbol "@yH_OnVehicleSirenStateChange@a" is truncated to 31 characters

YSI doesnt support "OnVehicleSirenStateChange"

static stock
    YSI_g_sReplacements[][E_HOOK_NAME_REPLACEMENT_DATA] =
        {
            {"CP",  "Checkpoint", 2, 10},
            // For "SIF".
            {"Cnt", "Container",  3, 9},
            {"Inv", "Inventory",  3, 9},
            {"Dyn", "Dynamic",    3, 7},
            {"TD",  "TextDraw",   2, 8},
            {"Upd", "Update",     3, 6},
            {"Obj", "Object",     3, 6},
            {"Cmd", "Command",    3, 7}
        };

**Comment by Misiur** [comment]
[YSI 4 requires that change as well](https://github.com/Misiur/YSI-Includes/blob/d763ccc970c872ba902c73f244e90608660c1cc6/YSI_Coding/y_hooks/impl.inc#L160-L167) (well, to be honest replacements overall need fixing, especially https://github.com/Misiur/YSI-Includes/issues/43).

We could change `Vehicle` to `Veh` but that would affect a lot of callbacks. Maybe `Siren` to something else? 

Ref https://github.com/Misiur/YSI-Includes/issues/33

**Comment by MaxAndolini** [comment]
"State" "St" is it possible?

**Comment by Crayder** [comment]
Yeah the hook replacements are pretty messed up still.

**Comment by MaxAndolini** [comment]
Okay. How do i fix it?

**Comment by Southclaws** [comment]
Replace "SirenStateChange" to simply "Siren":
"OnVehicleSiren" makes enough sense.

**Comment by MaxAndolini** [comment]
DEFINE_HOOK_REPLACEMENT(SirenStateChange, Siren);

It worked. Thank you.

**Comment by alokhinDev** [comment]
How did you make it work?
I've tried
```
DEFINE_HOOK_REPLACEMENT(SirenStateChange, Siren);
hook OnVehicleSiren(playerid, vehicleid, newstate)
```
and it didn't work for me, hook is not firing when turning vehicle siren on/off

P.S. I've figured it out by myself. I think the point is you can't replace ending of the callback as it will not fired.
So when I've tried to replace `Vehicle` to `Veh` or `State` to `St` it works

**Comment by PaulAlyokhin** [comment]
@MaxAndolini
