### ISSUE TITLE
y_hook OnPlayerEnterRaceCP

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#80]
Hook:ac_OnPlayerEnterRaceCP(playerid)

Error: YSI Fatal Error: Could not write function name in "Hooks_MakePublicPointer".

**Comment by Y-Less** [comment]
That's the old syntax.  Use:

``` pawn
hook OnPlayerEnterRaceCP(playerid)
{
}
```

**Comment by Y-Less** [comment]
The old syntax SHOULD be supported for backwards compatibility reasons, but I don't know if it actually IS...  I don't remember writing code to support it (very bad of me).

**Comment by MaxAndolini** [comment]
Thank you Y-Less you are amazing :D (Solved).

**Comment by MaxAndolini** [comment]
error 021: symbol already defined: "@yH_OnPlayerConnect@002"
error 021: symbol already defined: "@yH_OnPlayerDisconnect@002"
warning 200: symbol "@yH_OnVehicleDamageStatusUpd@00" is truncated to 31 characters


hook OnPlayerConnect(playerid)

hook OnPlayerDisconnect(playerid, reason)

hook OnVehicleDamageStatusUpd(vehicleid, playerid)
