### ISSUE TITLE
y_hooks Errors

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#81]
error 021: symbol already defined: "@yH_OnPlayerConnect@002"
error 021: symbol already defined: "@yH_OnPlayerDisconnect@002"
warning 200: symbol "@yH_OnVehicleDamageStatusUpd@00" is truncated to 31 characters

hook OnPlayerConnect(playerid)

hook OnPlayerDisconnect(playerid, reason)

hook OnVehicleDamageStatusUpd(vehicleid, playerid)

**Comment by Y-Less** [comment]
You need to include y_hooks in EVERY file.

**Comment by MaxAndolini** [comment]
warning 200: symbol "@yH_OnVehicleDamageStatusUpd@00" is truncated to 31 characters

**Comment by Y-Less** [comment]
Have you read any of the documentation on y_hooks?  Every issue you've mentioned has a well known and documented solution (or isn't even a bug).

**Comment by MaxAndolini** [comment]
It's a bug because.

Normally;

OnVehicleDamageStatusUpdate

I am change this;

OnVehicleDamageStatusUpd

but give error.

**Comment by MaxAndolini** [comment]
DEFINE_HOOK_REPLACEMENT(StatusUpdate, StaUp);

hook OnVehicleDamageStaUp(vehicleid, playerid)

Solved.

**Comment by Y-Less** [comment]
What is wrong with the existing "Vehicle" -> "Veh" replacement?

**Comment by MaxAndolini** [comment]
Ok i am change this.
