### ISSUE TITLE
y_iterate: foreach( new x: itername< > ) + a possible bug ?

### ISSUE THREAD

**Issue by IstuntmanI** [pawn-lang/YSI-Includes#83]
In the past two days I've got in some situations in which I would need something like in the title, for a better performance.

Let's say we have this code:

``` pawn
new Iterator:VehiclePlayers< MAX_VEHICLES, MAX_PLAYERS >;

Iter_Add( VehiclePlayers< 30 >, 5 );
Iter_Add( VehiclePlayers< 50 >, 10 );
```

and somewhere we would need to loop through all players which are in a vehicle:

``` pawn
foreach( new x: VehiclePlayers< > )
{ }
```

but it gives these errors:

> error 029: invalid expression, assumed zero
> error 001: expected token: ")", but found ";"

It could be really useful. I don't know if it can be actually made.

---

By the way, there's a little bug: using

``` pawn
new Iterator:itername< 50, 50 >; // just a random size
Iter_Add( itername< 30 >, 40 );
foreach( new x: itername )
{
    printf( "Currently in loop: %d", x );
}
```

doesn't actually give any compile warning/error and it neither loops through anything. But it works if you add in < 0 >, but loops only through the values which are in < 0 >, not in any other. I guess "new x: itername" is a "synonym" for "new x: itername< 0 >", which isn't alright .

**Comment by Dayvison** [comment]
foreach( new x: VehiclePlayers< **X** > )
You need specific a number here.

**Comment by Crayder** [comment]
I'm pretty sure it wasn't supported before because we didn't have access to which multi-index the values belonged to. Now however, we have `Iter_GetMulti` so it should be.

It would probably be a simple loop through all multi-indexes and for each one that isn't empty it would loop through it's indexes. If it could be done otherwise I'd rather it loop through all indexes in order.

```
By the way, there's a little bug: using ... doesn't actually give any compile warning/error and it neither loops through anything.
```

I wouldn't consider that a bug, it's just something you know you shouldn't do.

**Comment by Crayder** [comment]
@Dayvison No, you clearly didn't get the point. He want's to loop through all of the iterator, not just the values of any specific multi-index.

**Comment by IstuntmanI** [comment]
@Dayvison I know. That's why I made this suggestion, so we could directly loop through ALL values added, not only through all values from the specified ID. With VehiclePlayers< X > you loop through all players which are in that vehicle, but with VehiclePlayers< > you should be able to loop through all players in a vehicle.

@Crayder Well, that usage should have a different behaviour, for sure new y_iterate users could try something like that and they wouldn't understand why it isn't working.

**Comment by Dayvison** [comment]
Ok sorry.

**Comment by Crayder** [comment]
Here is an sketch of how it'd kind of work (btw, this works, so here is a temporary solution too):

```
#include a_samp
#include YSI\y_iterate

main() {
    #define MAX_PLAYERS_ 50
    #define MAX_VEHICLES_ 200

    new Iterator:Multi<MAX_PLAYERS_, MAX_VEHICLES_>;

    Iter_Add(Multi<0>, 2);
    Iter_Add(Multi<0>, 3);
    Iter_Add(Multi<0>, 4);
    Iter_Add(Multi<2>, 7);
    Iter_Add(Multi<8>, 5);

    // Loop through all possible indices (this should be the range of the iterator, not all like it is here)
    for(new i; i < MAX_VEHICLES_; i++)
        // If this index is in the iterator, in any multi-index (internally this could probably be a lot more efficient)
        if(Iter_Contains(Multi<>, i)) // if(Iter_GetMulti(Multi<>, i) != -1)
            printf("multi-index: %i, id: %i", Iter_GetMulti(Multi<>, i), i);
}
```

**Comment by Y-Less** [comment]
Not possible - doing that totally goes against the fundamental way that y_iterate works.  If you want all players in any vehicle, use an iterator for that; if you want all players in ONE vehicle, use the code you started with.

As for not specifying an index, you are correct that that is probably a bug, but detecting it and dealing with it is non-trivial given how complex the macros already are (to the point that I have no idea how to do it, but feel free to look).

**Comment by Crayder** [comment]
> doing that totally goes against the fundamental way that y_iterate works
> If you're referring to the loop through `MAX_VEHICLES`, yes, that does go against it. But that was just to show what would be happening.

If we could just have support for doing this:

```
new Iterator:Multi<MAX_PLAYERS, MAX_VEHICLES>;

Iter_Add(Multi<0>, 2);
Iter_Add(Multi<0>, 3);
Iter_Add(Multi<0>, 4);
Iter_Add(Multi<2>, 7);
Iter_Add(Multi<8>, 5);

// Loop through all possible indices (this should be the range of the iterator, not all like it is here), would present all of the indices added above. With those we could get the multi index from the indices.
for(new i: Multi<>)
        printf("%i, %i", Iter_GetMulti(Multi<>, i), i);
```

Output (in whatever order would be most efficient for the loop):

```
0, 2
0, 3
0, 4
2, 7
8, 5
```

Or, if it's possible to loop through the multi-indexes that are not empty, the users could just do that and loop through the indexes within that loop.

**Comment by Y-Less** [comment]
The simplest way is:

``` pawn
for (new j = 0; j != len; ++j)
foreach (new i : Array<j>)
{
}
```

That will get them in some random order.  The other way is just:

``` pawn
for (new i = 0; i != size; ++i)
if (Iter_Contains(Array<>, i))
{
}
```

That will loop in order.

**Comment by Y-Less** [comment]
So I wrote a special iterator for this:

``` pawn
foreach(new x : All(VehiclePlayers<>))
{
}
```

That is less fundamentally against the way y_iterate works, since special iterators are designed for this sort of thing.  Added by #101 .
