### ISSUE TITLE
y_hooks not passing return values back to caller

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/YSI-Includes#84]
I've spent some of the morning updating my main projects SIF and SS to YSI 4, and I noticed something odd. Both projects rely heavily on passing information in events back to the caller for example, returning 1 on OnPlayerPickUpItem prevents the player from picking up the item.

I've just tested out a module and it seems my return 1 doesn't get passed all the way back to SIF.

The hook is [here](https://github.com/Southclaw/ScavengeSurvive/blob/YSI4-Update/gamemodes/sss/core/char/backpack.pwn#L360) and caller is [here](https://github.com/Southclaw/SIF/blob/YSI4-Update/SIF/Item.pwn#L1963).

Now I haven't actually got around to converting all the ALS hooks to y_hooks so there are still many ALS hooks of OnPlayerPickUpItem and I'm not sure if that's the issue here or if y_hooks just doesn't support this and I'll have to switch back to ALS hooks for returning or think of another method to pass information back to where events are called.

**Comment by Southclaws** [comment]
Sorry, I completely forgot about the return codes! Correct me if I'm wrong:
- return 1 to continue hook chain and pass 1 back to caller
- return 0 to continue hook chain and pass 0 back to caller
- return -1 to stop hook chain and pass 0 back to caller
- return -2 to stop hook chain and pass 1 back to caller

I'll have to write these codes down though, are there any constants in YSI to indicate return type? If not, that would be a very useful addition:

```
#define Y_HOOKS_CONTINUE_RETURN_1   (1)
#define Y_HOOKS_CONTINUE_RETURN_0   (0)
#define Y_HOOKS_BREAK_RETURN_0      (-1)
#define Y_HOOKS_BREAK_RETURN_1      (-2)
```

Then I can easily see what a return is doing to the hook chain and event caller with `return Y_HOOKS_BREAK_RETURN_1;`

**Comment by Y-Less** [comment]
Yeah, that's not really that well documented sorry - the defines would be useful.
