### ISSUE TITLE
y_inline

### ISSUE THREAD

**Issue by lukecourt** [pawn-lang/YSI-Includes#87]
I get this
error 017: undefined symbol "mysql_tquery_inline"
for
[code]
        mysql_tquery_inline(mysql, gQuery, using inline GivePlayerAchievement);
[/code]

I have put y_inline before a_mysql but nothing works.

**Comment by Misiur** [comment]
``` pawn
native mysql_tquery_inline(connHandle, query[], callback:Callback, format[], {Float,_}:...); //y_inline
```

You are missing `format` argument. The error is misleading as the `mysql_tquery_inline` is a macro

**Comment by lukecourt** [comment]
I thought that was included in the a_mysql (BlueG) if you included y_inline before it.

**Comment by lukecourt** [comment]
Why is the format part not like optional?

**Comment by Misiur** [comment]
``` pawn
#define mysql_tquery_inline(%0,%1,%2,"%3"%4) \
    mysql_tquery(%0,%1,"FJ37DH3JG_MYSQL_INTERNAL","d"#%3,MySQL_Internal_SaveInline(%2)%4)
```

As you can see it's a little more complicated than normal `mysql_tquery` call

**Comment by Y-Less** [comment]
Not a YSI bug.
