### ISSUE TITLE
y_dialogs/y_inline problem

### ISSUE THREAD

**Issue by PT-Player** [pawn-lang/YSI-Includes#9]
Afther some time the server online the dialog show to the player dont response, its show for the player but seems like dont response.

On YSI 3.1, this dont happends, YSI 4.0 problem.

**Comment by Crayder** [comment]
Code or proof? This doesn't seem to happen to me.

**Comment by PT-Player** [comment]
Well afther some search looks like and problem of YSI on debian.

On windows this dont happends only when i put the GM on VPS ( Debian ).

**Comment by PT-Player** [comment]
@Y-Less any idea how to fix this?

**Comment by Y-Less** [comment]
Nope, sorry.  More information, and _DEBUG and CrashDetect outputs might help.

**Comment by PT-Player** [comment]
@Y-Less their is the problem the CrashDetect debug dont show anything...

He just stop works..

( Sorry for the later awnser i'm on army, i only come home at weekend ).

**Comment by PT-Player** [comment]
Hey @Y-Less do you think can be something like this: https://github.com/Misiur/YSI-Includes/issues/17

causing the problem?

**Comment by Misiur** [comment]
Hello, is the problem still occurring? If yes, please show example code, I'll set up VM and run some tests.

**Comment by Misiur** [comment]
This could've been result of #21. In case you need this reopened just ask.

**Comment by PT-Player** [comment]
@Misiur looks like was that.

Sorry for the late answer, im on army i dont have many time now.

Nice work.
