### ISSUE TITLE
Problem with including y_ini

### ISSUE THREAD

**Issue by UnholyBeast** [pawn-lang/YSI-Includes#90]
So I recently downloaded your .rar of all YSI work, and I need y_ini for my database, but no matter what I do. I always get this error:

`C:\Users\Mace\Desktop\Unholy Cops and Robbers\pawno\include\YSI\..\YSI_Storage\y_ini.inc(206) : fatal error 100: cannot read from file: "..\amx\os"`

I have extracted all the folders from that .rar into my pawno/include folder. Not exactly sure what amx\os has to do with y_ini. Just thought I'd bring this to your attention. I can't do anything else till this is fixed.

**Comment by Crayder** [comment]
You need to also download this: https://github.com/Zeex/amx_assembly/archive/24c172db8401c6c97425f7c170b5897297e455d0.zip
Put it in the 'amx' folder in your includes.

This would've been done automatically if you used git commands to get the repository, but you downloaded the zip (not rar). That's perfectly fine, you just have to manually get the amx stuff.

**Comment by Y-Less** [comment]
Fixed in #101 - moves all of amx_assembly inclusion to one central place with better error messages.

**Comment by Duderobber** [comment]
Sir i read your all comments and i downloaded the file u gave crayder sir and i also included YSI but its not working till it just shows 1 error.Fatal error 100 cannot read from file YSI/y_in.Pls help me

**Comment by Y-Less** [comment]
Then you didn't read the comments very closely.  Almost every other one is us telling someone to do `YSI\y_ini` not `YSI/y_ini`.
