### ISSUE TITLE
Compile error in y_unique:67 - have I hit some sort of y_hooks limit?

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/YSI-Includes#96]
Just added a [new module](https://github.com/Southclaw/ScavengeSurvive/blob/liquid-update/gamemodes/sss/core/item/liquid-container.pwn) today with y_hooks and I got `invalid function or declaration` on y_unique line 67 (the `static stock const` declaration)

```
    #if UNIQUE_SYMBOL < 100
        static stock const UNIQUE_SYMBOL_LESS_THAN_100 = UNIQUE_SYMBOL;
        #include "y_unique\_000_to_099"
    #elseif UNIQUE_SYMBOL < 200
```

At the moment, Scavenge and Survive includes y_hooks 177 times across various modules but I have no idea why this error suddenly appeared now!

**Comment by kadaradam** [comment]
Look at the first line of the _liquid-container.pwn_ module. :D

**Comment by Southclaws** [comment]
Bollocks.

**Comment by Y-Less** [comment]
So you know, the limit should be 1000.  It can of course be increased, it is just a hassle to do so.  I recently made some changes to this module actually (which made me worry that I broke something and didn't test enough, although I'm not sure if I actually pushed the changes), the limit is now 0-1000 inclusive, previously it was 0-999.

**Comment by Southclaws** [comment]
That's good to know, I'm pretty confident I'll stay well under the limit!
