### ISSUE TITLE
Warning y_iterate

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#97]
YSI..\YSI_Coding..\YSI_Data\y_foreach/iterators.inc(652) : warning 203: symbol is never used: "addsiren"
YSI..\YSI_Coding..\YSI_Data\y_foreach/iterators.inc(693) : warning 203: symbol is never used: "addsiren"

**Comment by Y-Less** [comment]
That is nothing to do with YSI - that's one of your symbols.

**Comment by MaxAndolini** [comment]
If mod isnt 0.3.7 they give warning because addsiren added 0.3.7 :D

**Comment by Y-Less** [comment]
Ahh, yes, you are right - sorry.  That's a fairly simple fix - add `#pragma unused addsiren` under `#else`.
